// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class AR_FCH_TRX 
    {
        [Required]
        public string BAT_ID { get; set; }
        [References(typeof(AR_CUST))]
        [Required]
        public string CUST_NO { get; set; }
        [Required]
        public string DOC_NO { get; set; }
        [Required]
        public DateTime DOC_DAT { get; set; }
        public int? ENTRY_SEQ_NO { get; set; }
        [Required]
        public decimal AMT { get; set; }
        public string CALC_FCH_COD { get; set; }
        public DateTime? CALC_CUTOFF_DAT { get; set; }
        public decimal? CALC_AMT_PAST_DUE { get; set; }
        public decimal? CALC_FCH_AMT { get; set; }
        public string CALC_BY { get; set; }
        public DateTime? CALC_DT { get; set; }
        public string REF { get; set; }
        public DateTime? LST_EDIT_DT { get; set; }
        public string LST_EDIT_USR_ID { get; set; }
        public string EDIT_COMMNT { get; set; }
        public string ERR_REF { get; set; }
        public DateTime? LST_MAINT_DT { get; set; }
        public string LST_MAINT_USR_ID { get; set; }
        public DateTime? LST_LCK_DT { get; set; }
        public byte[] ROW_TS { get; set; }
    }

}
#pragma warning restore 1591
