// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class IM_ADJ_TRX 
    {
        [Required]
        public string BAT_ID { get; set; }
        [Required]
        public string ITEM_NO { get; set; }
        [References(typeof(IM_LOC))]
        [Required]
        public string LOC_ID { get; set; }
        [Required]
        public DateTime TRX_DAT { get; set; }
        [Required]
        public int SEQ_NO { get; set; }
        [Required]
        public decimal QTY { get; set; }
        [Required]
        public string QTY_UNIT { get; set; }
        [Required]
        public decimal QTY_NUMER { get; set; }
        [Required]
        public decimal QTY_DENOM { get; set; }
        [Required]
        public string UNIT { get; set; }
        [Required]
        public string ACCT_NO { get; set; }
        public decimal? COST_ENTD { get; set; }
        [Required]
        public string USE_NORM_COST { get; set; }
        public string DOC_NO { get; set; }
        public string REF { get; set; }
        public string ERR_REF { get; set; }
        [Required]
        public string IS_SINGLE_CELL { get; set; }
        public string CELL_DESCR { get; set; }
        public string DIM_1_UPR { get; set; }
        public string DIM_2_UPR { get; set; }
        public string DIM_3_UPR { get; set; }
        public string SER_NO { get; set; }
        public int? NO_OF_SERS_ENTD { get; set; }
        public DateTime? LST_MAINT_DT { get; set; }
        public string LST_MAINT_USR_ID { get; set; }
        public DateTime? LST_LCK_DT { get; set; }
        public byte[] ROW_TS { get; set; }
        public int? NO_OF_NEW_SERS_ENTD { get; set; }
        public Guid? LIN_GUID { get; set; }
        [References(typeof(IM_ADJ_REAS_COD))]
        public string REAS_COD { get; set; }
    }

}
#pragma warning restore 1591
