// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class OM_CTL 
    {
        [Required]
        [PrimaryKey]
        public int KEY_ID { get; set; }
        [Required]
        public string WHL_DOC { get; set; }
        public string PCK_TKT_FRM_GRP_ID { get; set; }
        public string PCK_VRFY_FRM_GRP_ID { get; set; }
        public string INVC_FRM_GRP_ID { get; set; }
        public string REL_FRM_GRP_ID { get; set; }
        public string PCK_TKT_SUMM_FRM_FIL { get; set; }
        public string PCK_VRFY_SUMM_FRM_FIL { get; set; }
        public string INVC_SUMM_FRM_FIL { get; set; }
        public string REL_SUMM_FRM_FIL { get; set; }
        [Required]
        public string PCK_TKT_SUMM_FRM_PRT_METH { get; set; }
        [Required]
        public string PCK_VRFY_SUMM_FRM_PRT_METH { get; set; }
        [Required]
        public string INVC_SUMM_FRM_PRT_METH { get; set; }
        [Required]
        public string REL_SUMM_FRM_PRT_METH { get; set; }
    }

}
#pragma warning restore 1591
