// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;
    using System.Collections.Generic;

    public partial class PS_DOC_LIN 
    {
        [References(typeof(PS_DOC_HDR))]
        [Required]
        public long DOC_ID { get; set; }
        [Required]
        public int LIN_SEQ_NO { get; set; }
        [Required]
        public string STR_ID { get; set; }
        [Required]
        public string STA_ID { get; set; }
        [Required]
        public string TKT_NO { get; set; }
        [Required]
        public string LIN_TYP { get; set; }
        public string CELL_DESCR { get; set; }
        public decimal? PRC { get; set; }
        [Required]
        public string ITEM_NO { get; set; }
        public decimal? UNIT_RETL_VAL { get; set; }
        public int? NO_OF_SERS_ENTD { get; set; }
        public decimal? CALC_PRC { get; set; }
        public decimal? EXT_COST { get; set; }
        public string STK_LOC_ID { get; set; }
        public decimal? REG_PRC { get; set; }
        public string PRC_LOC_ID { get; set; }
        public string DESCR { get; set; }
        public string CATEG_COD { get; set; }
        public string SUBCAT_COD { get; set; }
        public string ITEM_VEND_NO { get; set; }
        [Required]
        public decimal QTY_SOLD { get; set; }
        [Required]
        public decimal QTY_NUMER { get; set; }
        [Required]
        public decimal QTY_DENOM { get; set; }
        public string QTY_UNIT { get; set; }
        [Required]
        public string SELL_UNIT { get; set; }
        public string RET_REAS { get; set; }
        [Required]
        public decimal EXT_PRC { get; set; }
        [Required]
        public string IS_TXBL { get; set; }
        public string PFT_CTR { get; set; }
        public string SLS_REP { get; set; }
        public string REF { get; set; }
        [Required]
        public string ITEM_TYP { get; set; }
        public decimal? PRC_1 { get; set; }
        public int? QTY_DECS { get; set; }
        public int? PRC_DECS { get; set; }
        public string BARCOD { get; set; }
        [Required]
        public string IS_SINGLE_CELL { get; set; }
        public int? EC_SEQ_NO { get; set; }
        public string RNDM_WEIGHT_BARCOD { get; set; }
        public string NORM_TAX_CATEG { get; set; }
        public string TAX_CATEG { get; set; }
        [Required]
        public string NORM_IS_TXBL { get; set; }
        public string TARE_COD { get; set; }
        [Required]
        public string TRK_METH { get; set; }
        public int? TARE_COD_IDX { get; set; }
        [Required]
        public decimal ORIG_QTY { get; set; }
        [Required]
        public decimal QTY_SHIPPED { get; set; }
        [Required]
        public string IS_FOOD_STMP_ELIG { get; set; }
        public decimal? EC_ORD_TOT_QTY_EXPECTD { get; set; }
        public decimal? TARE_WEIGHT { get; set; }
        public decimal? UNIT_WEIGHT { get; set; }
        public decimal? UNIT_CUBE { get; set; }
        [Required]
        public Guid LIN_GUID { get; set; }
        public Guid? LINK_LIN_GUID { get; set; }
        public string DIM_1_UPR { get; set; }
        public string DIM_2_UPR { get; set; }
        public string DIM_3_UPR { get; set; }
        public decimal? UNIT_COST { get; set; }
        public string SER_NO { get; set; }
        [Required]
        public decimal QTY_RET { get; set; }
        [Required]
        public string IS_VAL_RET { get; set; }
        public long? GFT_RGSTRY_ID { get; set; }
        [Required]
        public decimal GROSS_EXT_PRC { get; set; }
        public decimal? DISP_EXT_PRC { get; set; }
        public Guid? PAR_LIN_GUID { get; set; }
        [Required]
        public string IS_KIT_PAR { get; set; }
        [Required]
        public string HAS_PRC_OVRD { get; set; }
        public string PRC_OVRD_REAS { get; set; }
        public decimal? COST_ENTD { get; set; }
        public decimal? PRESUMED_COST { get; set; }
        public decimal? COST_OF_SLS_PCT { get; set; }
        public string MIX_MATCH_COD { get; set; }
        public decimal? MIX_MATCH_CONTRIB { get; set; }
        [Required]
        public string MIX_MATCH_PRC_BASED_ON { get; set; }
        [Required]
        public string USR_ENTD_PRC { get; set; }
        public decimal? GROSS_DISP_EXT_PRC { get; set; }
        [Required]
        public string IS_DISCNTBL { get; set; }
        [Required]
        public decimal CALC_EXT_PRC { get; set; }
        [Required]
        public decimal QTY_ENTD { get; set; }
        [Required]
        public decimal QTY_PCKD { get; set; }
        [Required]
        public decimal QTY_PCKVRFD { get; set; }
        [Required]
        public decimal QTY_INVCD { get; set; }
        [Required]
        public decimal QTY_TO_FILL { get; set; }
        [Required]
        public decimal QTY_TO_REL { get; set; }
        [Required]
        public decimal QTY_TO_LEAVE { get; set; }
        public Guid? LIN_GRP_GUID { get; set; }
        [Required]
        public string IS_MAN_ENTD_WGHT { get; set; }
        [Required]
        public string IS_WEIGHED { get; set; }
        [Required]
        public decimal TAX_AMT_ALLOC { get; set; }
        [Required]
        public decimal NORM_TAX_AMT_ALLOC { get; set; }
    }

}
#pragma warning restore 1591
