// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class PS_DRW_SESSION_EVENT_DETAIL 
    {
        [References(typeof(PS_DRW_SESSION_EVENT))]
        [Required]
        public string STR_ID { get; set; }
        [References(typeof(PS_DRW_SESSION_EVENT))]
        [Required]
        public string DRW_ID { get; set; }
        [References(typeof(PS_DRW_SESSION_EVENT))]
        [Required]
        public long DRW_SESSION_ID { get; set; }
        [References(typeof(PS_DRW_SESSION_EVENT))]
        [Required]
        public int EVENT_ID { get; set; }
        [References(typeof(SY_PAY_COD))]
        [Required]
        public string PAY_COD { get; set; }
        public decimal? AMT { get; set; }
        public decimal? OVER_SHORT_AMT { get; set; }
        [Required]
        public string CURNCY_COD { get; set; }
        [Required]
        public string CURNCY_COD_DESCR { get; set; }
        [Required]
        public decimal EXCH_RATE_NUMER { get; set; }
        [Required]
        public decimal EXCH_RATE_DENOM { get; set; }
        public decimal? HOME_CURNCY_AMT { get; set; }
        public decimal? OVER_SHORT_HOME_CURNCY_AMT { get; set; }
    }

}
#pragma warning restore 1591
