// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class PS_GFT_RGSTRY_LIN 
    {
        [References(typeof(PS_GFT_RGSTRY_HDR))]
        [Required]
        public long GFT_RGSTRY_ID { get; set; }
        [Required]
        public int SEQ_NO { get; set; }
        [Required]
        public string GFT_ITEM_NO { get; set; }
        [Required]
        public string QTY_REQSTD_UNIT_FLG { get; set; }
        [Required]
        public decimal QTY_REQSTD { get; set; }
        [Required]
        public decimal QTY_FILLED { get; set; }
        [Required]
        public decimal QTY_FILLED_DELTA { get; set; }
        [Required]
        public string DIM_1_UPR { get; set; }
        [Required]
        public string DIM_2_UPR { get; set; }
        [Required]
        public string DIM_3_UPR { get; set; }
        [Required]
        public string ECOMM_NXT_LIN_PUB_MODE { get; set; }
        public DateTime? ECOMM_LST_PUB_DT { get; set; }
        public DateTime? LST_MAINT_DT { get; set; }
        public string LST_MAINT_USR_ID { get; set; }
        public DateTime? LST_LCK_DT { get; set; }
    }

}
#pragma warning restore 1591
