// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class PS_REAS_COD 
    {
        [Required]
        [PrimaryKey]
        public string REAS_COD { get; set; }
        [Required]
        public string DESCR { get; set; }
        public string DESCR_UPR { get; set; }
        [Required]
        public string VAL_RET { get; set; }
        [Required]
        public string VAL_PRC_CHNG { get; set; }
        [Required]
        public string VAL_VOID_COMP_TKT { get; set; }
        [Required]
        public string VAL_TKT_TAX_OVRD { get; set; }
        public DateTime? LST_MAINT_DT { get; set; }
        public string LST_MAINT_USR_ID { get; set; }
        public DateTime? LST_LCK_DT { get; set; }
        public byte[] ROW_TS { get; set; }
        public DateTime? RS_UTC_DT { get; set; }
        [Required]
        public string VAL_SCRAP_INV { get; set; }
        [References(typeof(IM_ADJ_REAS_COD))]
        public string SCRAP_REASON_COD { get; set; }
        [Required]
        public byte RS_STAT { get; set; }
    }

}
#pragma warning restore 1591
