// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class SY_COMMIS_COD 
    {
        [Required]
        [PrimaryKey]
        public string COMMIS_COD { get; set; }
        [Required]
        public string DESCR { get; set; }
        public string DESCR_UPR { get; set; }
        [Required]
        public decimal COMMIS_PCT { get; set; }
        [Required]
        public string COMMIS_METH { get; set; }
        [Required]
        public string CALC_ON_MISC_1 { get; set; }
        [Required]
        public string CALC_ON_MISC_2 { get; set; }
        [Required]
        public string CALC_ON_MISC_3 { get; set; }
        [Required]
        public string CALC_ON_MISC_4 { get; set; }
        [Required]
        public string CALC_ON_MISC_5 { get; set; }
        [Required]
        public string CALC_ON_GFC_AMT { get; set; }
        public DateTime? LST_MAINT_DT { get; set; }
        public string LST_MAINT_USR_ID { get; set; }
        public DateTime? LST_LCK_DT { get; set; }
        public byte[] ROW_TS { get; set; }
        [Required]
        public string CALC_ON_SVC_AMT { get; set; }
        public DateTime? RS_UTC_DT { get; set; }
        [Required]
        public byte RS_STAT { get; set; }
    }

}
#pragma warning restore 1591
