// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class SY_NSP_LOG 
    {
        [Required]
        [PrimaryKey]
        public Guid ACTIVITY_ID { get; set; }
        [Required]
        public string REQ_ACTION { get; set; }
        [Required]
        public DateTime REQ_UTC_DT { get; set; }
        public decimal? REQ_AMT { get; set; }
        public DateTime? RESP_UTC_DT { get; set; }
        public string RESP_SUCCESSFUL { get; set; }
        public string TTID { get; set; }
        public decimal? AUTH_AMT { get; set; }
        public Guid? DOC_GUID { get; set; }
        public string STR_ID { get; set; }
        public string STA_ID { get; set; }
        public string TKT_NO { get; set; }
        public string CUST_NO { get; set; }
        public int? PMT_SEQ_NO { get; set; }
        public string EDC_AUTH_COD { get; set; }
        public string CARD_NO_MSK { get; set; }
        [Required]
        public string TKT_COMPLETED { get; set; }
        public DateTime? RS_UTC_DT { get; set; }
        [Required]
        public byte RS_STAT { get; set; }
    }

}
#pragma warning restore 1591
