// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class SY_PS_SEC_COD 
    {
        [Required]
        [PrimaryKey]
        public string PS_SEC_COD { get; set; }
        [Required]
        public string DESCR { get; set; }
        public string DESCR_UPR { get; set; }
        [Required]
        public string ALLOW_CHNG_PRC { get; set; }
        [Required]
        public string ALLOW_VOID_COMP { get; set; }
        [Required]
        public string ALLOW_VOID_CURR { get; set; }
        [Required]
        public string ALLOW_CR_LIM_OVRD { get; set; }
        [Required]
        public string ALLOW_EDIT_TKT_LINS { get; set; }
        [Required]
        public string ALLOW_TKT_TAX_OVRD { get; set; }
        [Required]
        public string ALLOW_NO_TKTS_OVRD { get; set; }
        [Required]
        public string ALLOW_NO_SAL { get; set; }
        [Required]
        public string ALLOW_MAX_RET_OVRD { get; set; }
        [Required]
        public string ALLOW_NO_PRT_OVRD { get; set; }
        [Required]
        public string ALLOW_REPRT { get; set; }
        [Required]
        public string ALLOW_CHNG_SLS_REP { get; set; }
        [Required]
        public string ALLOW_HOLDS { get; set; }
        [Required]
        public string ALLOW_QUOT { get; set; }
        [Required]
        public string ALLOW_EDIT_ORDS { get; set; }
        [Required]
        public string ALLOW_PICK_ORDS { get; set; }
        [Required]
        public string ALLOW_REL_ORDS { get; set; }
        [Required]
        public string ALLOW_CANCEL_ORDS { get; set; }
        [Required]
        public string ALLOW_ORD_DEPS { get; set; }
        [Required]
        public string ALLOW_NO_ORDS_OVRD { get; set; }
        [Required]
        public string ALLOW_QTY_AVAIL_OVRD { get; set; }
        public DateTime? LST_MAINT_DT { get; set; }
        public string LST_MAINT_USR_ID { get; set; }
        public DateTime? LST_LCK_DT { get; set; }
        public byte[] ROW_TS { get; set; }
        [Required]
        public string ALLOW_PRC_BELOW_MIN { get; set; }
        [Required]
        public string ALLOW_CHNG_TKT_TAX_COD { get; set; }
        [Required]
        public string ALLOW_CHNG_LIN_TAX_CATEG { get; set; }
        [Required]
        public string ALLOW_CHNG_LIN_TXBL_STAT { get; set; }
        [Required]
        public string ALLOW_NO_SIG_CAP { get; set; }
        [Required]
        public string BYPASS_DRW_ALARM { get; set; }
        [Required]
        public string ALLOW_PAY_IN { get; set; }
        [Required]
        public string ALLOW_PAY_OUT { get; set; }
        [Required]
        public string ALLOW_PAY_ON_ACCT { get; set; }
        [Required]
        public string ALLOW_RET_LINS { get; set; }
        [Required]
        public string ALLOW_SAL_LINS { get; set; }
        [Required]
        public string ALLOW_ORD_LINS { get; set; }
        [Required]
        public string ALLOW_BO_LINS { get; set; }
        [Required]
        public string ALLOW_SO_LINS { get; set; }
        [Required]
        public string ALLOW_LWY_LINS { get; set; }
        [Required]
        public string ALLOW_COPY_REL_ORDS { get; set; }
        [Required]
        public string ALLOW_REINSTATE_ORDS { get; set; }
        [Required]
        public string ALLOW_NO_LWYS_OVRD { get; set; }
        [Required]
        public string ALLOW_EDIT_LWYS { get; set; }
        [Required]
        public string ALLOW_PICK_LWYS { get; set; }
        [Required]
        public string ALLOW_LWY_DEPS { get; set; }
        [Required]
        public string ALLOW_REL_LWYS { get; set; }
        [Required]
        public string ALLOW_CANCEL_LWYS { get; set; }
        [Required]
        public string ALLOW_COPY_REL_LWYS { get; set; }
        [Required]
        public string ALLOW_REINSTATE_LWYS { get; set; }
        [Required]
        public string ALLOW_VIEW_ORD_HIST { get; set; }
        [Required]
        public string ALLOW_VIEW_LWY_HIST { get; set; }
        [Required]
        public string ALLOW_DEL_QUOT { get; set; }
        [Required]
        public string ALLOW_DEL_HOLD { get; set; }
        [Required]
        public string ALLOW_PRINT_ORDS { get; set; }
        [Required]
        public string ALLOW_PRINT_LWYS { get; set; }
        [Required]
        public string ALLOW_RDM_LOY_PTS { get; set; }
        [Required]
        public string ALLOW_ORD_DEP_RFND { get; set; }
        [Required]
        public string ALLOW_LWY_DEP_RFND { get; set; }
        [Required]
        public string ALLOW_SVC_ACTIV { get; set; }
        [Required]
        public string ALLOW_SVC_RECHRG { get; set; }
        [Required]
        public string ALLOW_SVC_BAL_INQ { get; set; }
        [Required]
        public string ALLOW_SVC_CASH_BACK { get; set; }
        [Required]
        public string ALLOW_SVC_MIN_ACTIV_OVRD { get; set; }
        [Required]
        public string ALLOW_SVC_MIN_RECHRG_OVRD { get; set; }
        [Required]
        public string ALLOW_SVC_MAX_RFND_OVRD { get; set; }
        [Required]
        public string ALLOW_SVC_MAX_CASH_BACK_OVRD { get; set; }
        [Required]
        public string ALLOW_STK_LOC_CHNG { get; set; }
        [Required]
        public string ALLOW_PRC_LOC_CHNG { get; set; }
        [Required]
        public string ALLOW_PFT_CTR_CHNG { get; set; }
        [Required]
        public string ALLOW_REISSUE_CHNG { get; set; }
        [Required]
        public string ALLOW_CLEAR_PMTS { get; set; }
        [Required]
        public string ALLOW_CLCK_IN_OUT { get; set; }
        [Required]
        public string ALLOW_CUSTOM_ACTN { get; set; }
        [Required]
        public string ALLOW_CUST_LOOKUP { get; set; }
        [Required]
        public string ALLOW_ENTER_PO_NO { get; set; }
        [Required]
        public string ALLOW_ENTER_BILL_TO { get; set; }
        [Required]
        public string ALLOW_ENTER_CUST { get; set; }
        [Required]
        public string ALLOW_ENTER_ITEM_PROMPT { get; set; }
        [Required]
        public string ALLOW_ENTER_MISC_CHRG { get; set; }
        [Required]
        public string ALLOW_ENTER_NOTE { get; set; }
        [Required]
        public string ALLOW_ENTER_PKG_TRK_NO { get; set; }
        [Required]
        public string ALLOW_ENTER_SHIP_TO { get; set; }
        [Required]
        public string ALLOW_RUN_EXE { get; set; }
        [Required]
        public string ALLOW_HOLD_AND_RECALL { get; set; }
        [Required]
        public string ALLOW_ITEM_LOOKUP { get; set; }
        [Required]
        public string ALLOW_MOVE_LIN_UP_DOWN { get; set; }
        [Required]
        public string ALLOW_RE_PRC_LINS { get; set; }
        [Required]
        public string ALLOW_RUN_PG { get; set; }
        [Required]
        public string ALLOW_EDIT_TKT_PROF { get; set; }
        [Required]
        public string ALLOW_CUST_CR_CARD { get; set; }
        public DateTime? RS_UTC_DT { get; set; }
        [Required]
        public string ALLOW_VAL_RET_LINS { get; set; }
        [Required]
        public string ALLOW_TKT_DISC { get; set; }
        [Required]
        public string ALLOW_MAX_DISC_OVRD { get; set; }
        [Required]
        public byte RS_STAT { get; set; }
        [Required]
        public string ALLOW_DROPSHIP_LINS { get; set; }
        [Required]
        public string ALLOW_VAL_RET_FOR_NOF_CUST { get; set; }
    }

}
#pragma warning restore 1591
