// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class SY_WORKSTATION 
    {
        [Required]
        [PrimaryKey]
        public long WORKSTATION_ID { get; set; }
        [Required]
        public string DESCR { get; set; }
        [Required]
        public string MACHINE_NAM { get; set; }
        [Required]
        public string CP_SERV_NAM { get; set; }
        public string WRKGRP_ID { get; set; }
        [Required]
        public string ALLOW_OTHER_WRKGRPS { get; set; }
        [Required]
        public string TOUCH_MODE { get; set; }
        [Required]
        public string SKIP_LOGIN_DLG { get; set; }
        [Required]
        public string ENABLE_TKT_ENTRY_EVENT_LOG { get; set; }
        [Required]
        public string ENABLE_POS_DEVICE_LOG { get; set; }
        public string DRW_ID { get; set; }
        [Required]
        public string ALLOW_DRW_CHNG { get; set; }
        public string STA_ID { get; set; }
        [Required]
        public string ALLOW_STA_CHNG { get; set; }
        public DateTime? FST_MAINT_DT { get; set; }
        public string FST_MAINT_USR_ID { get; set; }
        public DateTime? LST_MAINT_DT { get; set; }
        public string LST_MAINT_USR_ID { get; set; }
        public byte[] ROW_TS { get; set; }
        public DateTime? RS_UTC_DT { get; set; }
        [Required]
        public byte RS_STAT { get; set; }
        public string UDID { get; set; }
    }

}
#pragma warning restore 1591
