// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class USER_VI_BUYBACK_TRADEIN_RCPT 
    {
        [Required]
        public long DOC_ID_EXT { get; set; }
        public string DESCR { get; set; }
        public string USER_BUYBACK_TRADEIN_SER_NO { get; set; }
        public decimal? USER_BUYBACK_TRADEIN_CONSIDERATION { get; set; }
        public string USER_BUYBACK_TRADEIN_ITEM_NO { get; set; }
        [Required]
        public string LONG_STRING { get; set; }
    }

}
#pragma warning restore 1591
