// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class USER_ITEM_IMPORT 
    {
        [Required]
        [PrimaryKey]
        public int ITEM_NO { get; set; }
        public string DESCR { get; set; }
        public string LONG_DESCR { get; set; }
        public string ADDL_DESCR_1 { get; set; }
        public string ADDL_DESCR_2 { get; set; }
        public string ITEM_TYP { get; set; }
        public decimal? PRC_1 { get; set; }
        public decimal? PRC_2 { get; set; }
        public decimal? PRC_3 { get; set; }
        public decimal? REG_PRC { get; set; }
        public string STK_UNIT { get; set; }
        public decimal? LST_COST { get; set; }
        public string IS_TXBL { get; set; }
        public string CATEG_DESCR { get; set; }
        public string SUBCAT_DESCR { get; set; }
        public string VENDOR_NAM { get; set; }
        public string VEND_ITEM_NO { get; set; }
        public string ALT_1_UNIT { get; set; }
        public decimal? ALT_1_NUMER { get; set; }
        public decimal? ALT_1_DENOM { get; set; }
        public decimal? ALT_1_PRC_1 { get; set; }
        public string ALT_2_UNIT { get; set; }
        public decimal? ALT_2_NUMER { get; set; }
        public decimal? ALT_2_DENOM { get; set; }
        public decimal? ALT_2_PRC_1 { get; set; }
        public string ALT_3_UNIT { get; set; }
        public decimal? ALT_3_NUMER { get; set; }
        public decimal? ALT_3_DEMON { get; set; }
        public decimal? ALT_3_PRC_1 { get; set; }
        public string BARCOD1 { get; set; }
        public string BARCOD2 { get; set; }
        public string BARCOD3 { get; set; }
        public string DIM_1_TAG { get; set; }
        public string DIM_2_TAG { get; set; }
        public string DIM_3_TAG { get; set; }
        public string DIM_1 { get; set; }
        public string DIM_2 { get; set; }
        public string DIM_3 { get; set; }
        public decimal? WEIGHT { get; set; }
        public string FREIGHT_CHARGE { get; set; }
        public string TRACKING_METHOD { get; set; }
        public string IS_WEB_ITEM { get; set; }
        [Required]
        public int STYLE_ID { get; set; }
        public string CALIBER_GAUGE { get; set; }
        public string USER_ACTION { get; set; }
        public string MAG_CAPACITY { get; set; }
        public string BARREL_LENGTH { get; set; }
        public string IS_FIREARM { get; set; }
        public string USER_MODEL { get; set; }
        public string USER_IMPORTER { get; set; }
        public string USER_MANUFACTURER { get; set; }
        public string USER_STATE_TYPE { get; set; }
        public string USER_ATF_TYPE { get; set; }
        public string ATTR_1_COD { get; set; }
        public string ATTR_1_COD_DESCR { get; set; }
        public string ATTR_2_COD { get; set; }
        public string ATTR_2_COD_DESCR { get; set; }
        public string ATTR_3_COD { get; set; }
        public string ATTR_3_COD_DESCR { get; set; }
        public string ATTR_4_COD { get; set; }
        public string ATTR_4_COD_DESCR { get; set; }
        public string CATEG_COD { get; set; }
        public string SUBCAT_COD { get; set; }
        [AutoIncrement]
        public int ID { get; set; }
        public string ITEM_VEND_NO { get; set; }
    }

}
#pragma warning restore 1591
