// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class USER_BOUND_BOOK_ITEM_ATF_TYPE 
    {
        [Required]
        [PrimaryKey]
        public string USER_ATF_TYPE { get; set; }
        public string USER_4473_TYPE { get; set; }
    }

}
#pragma warning restore 1591
