// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class USER_VI_POS_TO_EMAIL 
    {
        [Required]
        public string PO_NO { get; set; }
        [Required]
        public string VEND_NO { get; set; }
        public DateTime? LST_MAINT_DT { get; set; }
    }

}
#pragma warning restore 1591
