// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class VI_AR_RPT_RECALC_CUST_BAL 
    {
        [Required]
        public string CUST_NO { get; set; }
        [Required]
        public string NAM { get; set; }
        [Required]
        public string WHATS_WRONG { get; set; }
        [Required]
        public decimal CUST_BAL { get; set; }
        public decimal? TRX_BAL { get; set; }
        [Required]
        public decimal CUST_UNPSTD_BAL { get; set; }
        public decimal? TRX_UNPSTD_BAL { get; set; }
        [Required]
        public int CUST_NO_OF_ORDS { get; set; }
        public int? TRX_NO_OF_ORDS { get; set; }
        [Required]
        public decimal CUST_ORD_BAL { get; set; }
        public decimal? TRX_ORD_BAL { get; set; }
        [Required]
        public int CUST_NO_OF_LWYS { get; set; }
        public int? TRX_NO_OF_LWYS { get; set; }
        [Required]
        public decimal CUST_LWY_BAL { get; set; }
        public decimal? TRX_LWY_BAL { get; set; }
    }

}
#pragma warning restore 1591
