// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class VI_AR_CUST_TRX 
    {
        [Required]
        public string TYPE { get; set; }
        [Required]
        public string TYPE_SORT_ORDER { get; set; }
        public string CUST_NO { get; set; }
        public DateTime? DOC_DAT { get; set; }
        [Required]
        public string DOC_NO { get; set; }
        [Required]
        public string DOC_TYP { get; set; }
        public decimal? BAL { get; set; }
        public decimal? UNPSTD_BAL { get; set; }
        [Required]
        public int NO_OF_ORDS { get; set; }
        [Required]
        public int NO_OF_LWYS { get; set; }
        public decimal? ORD_BAL { get; set; }
        public decimal? LWY_BAL { get; set; }
    }

}
#pragma warning restore 1591
