// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class VI_APPLY_TO_GRPS 
    {
        [Required]
        public string CUST_NO { get; set; }
        [Required]
        public DateTime DOC_DAT { get; set; }
        [Required]
        public string DOC_NO { get; set; }
        [Required]
        public string DOC_TYP { get; set; }
        [Required]
        public string TERMS_COD { get; set; }
        [Required]
        public DateTime DUE_DAT { get; set; }
        [Required]
        public DateTime DISC_DAT { get; set; }
        public decimal? DISC_PCT { get; set; }
        public string SLS_REP { get; set; }
        public string REF { get; set; }
        public string STR_ID { get; set; }
        public string CUST_PO_NO { get; set; }
        [Required]
        public string APPL_IS_OPEN { get; set; }
        public decimal? ORIG_AMT { get; set; }
        public decimal? ORIG_ENTD_AMT { get; set; }
        public decimal? TOT_DISCNTBL_AMT { get; set; }
        public decimal? TOT_DISC_USED { get; set; }
        public decimal? TOT_WRTOFF_AMT { get; set; }
        public decimal? DOC_BAL { get; set; }
        public decimal? ORIG_DISC_AVAIL { get; set; }
        public decimal? DISC_AVAIL { get; set; }
        public int? NO_OF_APPLS { get; set; }
    }

}
#pragma warning restore 1591
