// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class VI_Birthday 
    {
        public string USER_DL_NO { get; set; }
        public string FST_NAM { get; set; }
        public string LST_NAM { get; set; }
        public DateTime? USER_DOB { get; set; }
        public string EMAIL_ADRS_1 { get; set; }
        public string STATE { get; set; }
        [Required]
        public string CUST_NO { get; set; }
    }

}
#pragma warning restore 1591
