// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class VI_DM_FORCST_LOC_ITEM_MNTH 
    {
        public int? MNTH_ID { get; set; }
        public string LOC_ID { get; set; }
        public string ITEM_NO { get; set; }
        public string DIM_1_UPR { get; set; }
        public string DIM_2_UPR { get; set; }
        public string DIM_3_UPR { get; set; }
        public decimal? SLS_QTY { get; set; }
        public decimal? RTN_QTY { get; set; }
        public decimal? ADJ_QTY { get; set; }
        public decimal? XFER_OUT_QTY { get; set; }
        public decimal? XFER_IN_QTY { get; set; }
        public decimal? QXFER_OUT_QTY { get; set; }
        public decimal? QXFER_IN_QTY { get; set; }
        public decimal? QASSEM_QTY { get; set; }
        public DateTime? LST_MAINT_DT { get; set; }
        public decimal? FORC_LEVEL { get; set; }
        public decimal? FORC_TREND { get; set; }
        public decimal? MNTH_INDX { get; set; }
        public int? CUTOFF_MNTH_ID { get; set; }
        public string USE_TI { get; set; }
        public DateTime? FORC_UPD_ON { get; set; }
    }

}
#pragma warning restore 1591
