// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class VI_PO_ADV_WRK_CELL 
    {
        [Required]
        public string SESS_ID { get; set; }
        [Required]
        public string ITEM_NO { get; set; }
        [Required]
        public string LOC_ID { get; set; }
        [Required]
        public string DIM_1_UPR { get; set; }
        [Required]
        public string DIM_2_UPR { get; set; }
        [Required]
        public string DIM_3_UPR { get; set; }
        public decimal? ORIG_SUGG_QTY { get; set; }
        public decimal? ADJ_SUGG_QTY { get; set; }
        public decimal? QTY_SOLD { get; set; }
        public decimal? QTY_ON_HND { get; set; }
        public decimal? QTY_ON_PO { get; set; }
        public decimal? QTY_ON_PREQ { get; set; }
        public decimal? QTY_COMMIT { get; set; }
        public decimal? QTY_ON_BO { get; set; }
        [Required]
        public decimal MIN_QTY { get; set; }
        [Required]
        public decimal MAX_QTY { get; set; }
        public decimal? NET_QTY { get; set; }
        public DateTime? LST_MAINT_DT { get; set; }
        public string LST_MAINT_USR_ID { get; set; }
        public DateTime? LST_LCK_DT { get; set; }
        public byte[] ROW_TS { get; set; }
        public decimal? QTY_ON_SO { get; set; }
        public decimal? QTY_ON_ORD { get; set; }
        public decimal? QTY_ON_LWY { get; set; }
        public int? CURR_DAYS_OF_SUPPLY { get; set; }
        public int? LEAD_DAYS { get; set; }
        public string DisplayLabel1 { get; set; }
        public string DisplayLabel2 { get; set; }
        public string DisplayLabel3 { get; set; }
        public string DisplayDim1Value { get; set; }
        public string DisplayDim2Value { get; set; }
        public string DisplayDim3Value { get; set; }
        public int? DisplayDim1SeqNo { get; set; }
        public int? DisplayDim2SeqNo { get; set; }
        public int? DisplayDim3SeqNo { get; set; }
    }

}
#pragma warning restore 1591
