// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class VI_PS_STR_RCPT 
    {
        [Required]
        public string STR_ID { get; set; }
        [Required]
        public string DESCR { get; set; }
        public string DESCR_UPR { get; set; }
        public string ADRS_1 { get; set; }
        public string ADRS_2 { get; set; }
        public string ADRS_3 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP_COD { get; set; }
        public string CNTRY { get; set; }
        public string PHONE_1 { get; set; }
        public string PHONE_2 { get; set; }
        public string FAX_1 { get; set; }
        public string FAX_2 { get; set; }
        public string CONTCT_1 { get; set; }
        public string CONTCT_2 { get; set; }
        public string EMAIL_ADRS_1 { get; set; }
        public string EMAIL_ADRS_2 { get; set; }
        public string URL_1 { get; set; }
        public string URL_2 { get; set; }
        public DateTime? LST_MAINT_DT { get; set; }
        public string LST_MAINT_USR_ID { get; set; }
        public DateTime? LST_LCK_DT { get; set; }
        public byte[] ROW_TS { get; set; }
        public int? SLS_AREA { get; set; }
        public int? TOT_AREA { get; set; }
        [Required]
        public string USE_PS { get; set; }
        [Required]
        public string USE_OE { get; set; }
        public DateTime? RS_UTC_DT { get; set; }
        [Required]
        public short STR_NO { get; set; }
        [Required]
        public byte RS_STAT { get; set; }
        public string USER_ADD_CUST_FROM_DL { get; set; }
        public string USER_VERIFY_AGE_FROM_DL { get; set; }
        public string USER_UPDATE_CUST_ADRS_FROM_DL { get; set; }
        public string TAX_ID_NO { get; set; }
        public string USER_4473_REQUIRED_VERIFY { get; set; }
        public string USER_E4473_ALLOW_CASH_CUST { get; set; }
        public string USER_REQUIRE_LONG_GUN_REPORTING { get; set; }
        public string PFT_CTR { get; set; }
        [Required]
        public string STK_LOC_ID { get; set; }
        [Required]
        public string PRC_LOC_ID { get; set; }
        public string WALK_IN_CUST_NO { get; set; }
        [Required]
        public string PROMPT_NAM_ADRS { get; set; }
        [Required]
        public string AR_TAX_COD { get; set; }
        [Required]
        public string SHOW_TAX_AUTHS { get; set; }
        [Required]
        public string DFLT_TAX_COD_METH { get; set; }
        [Required]
        public string TKT_NO_METH { get; set; }
        public string NXT_TKT_NO { get; set; }
        [Required]
        public string NXT_TKT_NO_AUTO { get; set; }
        [Required]
        public string ALLOW_SLS_REP_CHNG { get; set; }
        [Required]
        public string USE_PROF_ALPHA_1 { get; set; }
        [Required]
        public string USE_PROF_ALPHA_2 { get; set; }
        [Required]
        public string USE_PROF_ALPHA_3 { get; set; }
        [Required]
        public string USE_PROF_ALPHA_4 { get; set; }
        [Required]
        public string USE_PROF_ALPHA_5 { get; set; }
        [Required]
        public string USE_PROF_COD_1 { get; set; }
        [Required]
        public string USE_PROF_COD_2 { get; set; }
        [Required]
        public string USE_PROF_COD_3 { get; set; }
        [Required]
        public string USE_PROF_COD_4 { get; set; }
        [Required]
        public string USE_PROF_COD_5 { get; set; }
        [Required]
        public string USE_PROF_DAT_1 { get; set; }
        [Required]
        public string USE_PROF_DAT_2 { get; set; }
        [Required]
        public string USE_PROF_DAT_3 { get; set; }
        [Required]
        public string USE_PROF_DAT_4 { get; set; }
        [Required]
        public string USE_PROF_DAT_5 { get; set; }
        [Required]
        public string USE_PROF_NO_1 { get; set; }
        [Required]
        public string USE_PROF_NO_2 { get; set; }
        [Required]
        public string USE_PROF_NO_3 { get; set; }
        [Required]
        public string USE_PROF_NO_4 { get; set; }
        [Required]
        public string USE_PROF_NO_5 { get; set; }
        [Required]
        public string LIN_TAX_DSPLY { get; set; }
        [Required]
        public string USE_MISC_1 { get; set; }
        [Required]
        public string USE_MISC_2 { get; set; }
        [Required]
        public string USE_MISC_3 { get; set; }
        [Required]
        public string USE_MISC_4 { get; set; }
        [Required]
        public string USE_MISC_5 { get; set; }
        [Required]
        public string DISABLE_REPRT { get; set; }
        [Required]
        public string REQ_PRT { get; set; }
        [Required]
        public string AUTO_DRW_ACTIV { get; set; }
        [Required]
        public string AUTO_DRW_CNT { get; set; }
        [Required]
        public string AUTO_DRW_RECON { get; set; }
        [Required]
        public string ALLOW_DRW_REACTIV { get; set; }
        [Required]
        public string LOGIN_PER_TKT { get; set; }
        [Required]
        public string SLS_REP_DFLT_METH { get; set; }
        [Required]
        public string USE_RET_REAS { get; set; }
        [Required]
        public string USE_PRC_CHNG_REAS { get; set; }
        [Required]
        public string USE_VOID_COMP_REAS { get; set; }
        [Required]
        public string USE_TKT_TAX_REAS { get; set; }
        public decimal? MAX_RET_AMT { get; set; }
        [Required]
        public string NO_MAX_RET_AMT { get; set; }
        [Required]
        public string DFLT_LIN_DESCR { get; set; }
        [Required]
        public string DFLT_SAL_MISC_1_TYP { get; set; }
        public decimal? DFLT_SAL_MISC_1_PCT { get; set; }
        public decimal? DFLT_SAL_MISC_1_AMT { get; set; }
        [Required]
        public string DFLT_SAL_MISC_2_TYP { get; set; }
        public decimal? DFLT_SAL_MISC_2_PCT { get; set; }
        public decimal? DFLT_SAL_MISC_2_AMT { get; set; }
        [Required]
        public string DFLT_SAL_MISC_3_TYP { get; set; }
        public decimal? DFLT_SAL_MISC_3_PCT { get; set; }
        public decimal? DFLT_SAL_MISC_3_AMT { get; set; }
        [Required]
        public string DFLT_SAL_MISC_4_TYP { get; set; }
        public decimal? DFLT_SAL_MISC_4_PCT { get; set; }
        public decimal? DFLT_SAL_MISC_4_AMT { get; set; }
        [Required]
        public string DFLT_SAL_MISC_5_TYP { get; set; }
        public decimal? DFLT_SAL_MISC_5_PCT { get; set; }
        public decimal? DFLT_SAL_MISC_5_AMT { get; set; }
        [Required]
        public string DFLT_ORD_MISC_1_TYP { get; set; }
        public decimal? DFLT_ORD_MISC_1_PCT { get; set; }
        public decimal? DFLT_ORD_MISC_1_AMT { get; set; }
        [Required]
        public string DFLT_ORD_MISC_2_TYP { get; set; }
        public decimal? DFLT_ORD_MISC_2_PCT { get; set; }
        public decimal? DFLT_ORD_MISC_2_AMT { get; set; }
        [Required]
        public string DFLT_ORD_MISC_3_TYP { get; set; }
        public decimal? DFLT_ORD_MISC_3_PCT { get; set; }
        public decimal? DFLT_ORD_MISC_3_AMT { get; set; }
        [Required]
        public string DFLT_ORD_MISC_4_TYP { get; set; }
        public decimal? DFLT_ORD_MISC_4_PCT { get; set; }
        public decimal? DFLT_ORD_MISC_4_AMT { get; set; }
        [Required]
        public string DFLT_ORD_MISC_5_TYP { get; set; }
        public decimal? DFLT_ORD_MISC_5_PCT { get; set; }
        public decimal? DFLT_ORD_MISC_5_AMT { get; set; }
        [Required]
        public string DFLT_LWY_MISC_1_TYP { get; set; }
        public decimal? DFLT_LWY_MISC_1_PCT { get; set; }
        public decimal? DFLT_LWY_MISC_1_AMT { get; set; }
        [Required]
        public string DFLT_LWY_MISC_2_TYP { get; set; }
        public decimal? DFLT_LWY_MISC_2_PCT { get; set; }
        public decimal? DFLT_LWY_MISC_2_AMT { get; set; }
        [Required]
        public string DFLT_LWY_MISC_3_TYP { get; set; }
        public decimal? DFLT_LWY_MISC_3_PCT { get; set; }
        public decimal? DFLT_LWY_MISC_3_AMT { get; set; }
        [Required]
        public string DFLT_LWY_MISC_4_TYP { get; set; }
        public decimal? DFLT_LWY_MISC_4_PCT { get; set; }
        public decimal? DFLT_LWY_MISC_4_AMT { get; set; }
        [Required]
        public string DFLT_LWY_MISC_5_TYP { get; set; }
        public decimal? DFLT_LWY_MISC_5_PCT { get; set; }
        public decimal? DFLT_LWY_MISC_5_AMT { get; set; }
        public string EDC_MERCH_NO { get; set; }
        [Required]
        public string EDC_PROCESSOR { get; set; }
        public string SERV_NAM_1 { get; set; }
        public string SERV_NAM_2 { get; set; }
        [Required]
        public string USE_CPGATEWAY { get; set; }
        public string CPGATEWAY_MERCH_ID { get; set; }
        [Required]
        public string USE_AVS { get; set; }
        [Required]
        public string USE_CVV { get; set; }
        [Required]
        public string DFLT_AVS_ADRS { get; set; }
        [Required]
        public string ENT_AVS_ADRS { get; set; }
        [Required]
        public string AVS_MISMATCH_OVRD { get; set; }
        [Required]
        public string AVS_UNAVAIL_OVRD { get; set; }
        [Required]
        public string CVV_MISMATCH_OVRD { get; set; }
        [Required]
        public string CVV_UNAVAIL_OVRD { get; set; }
        [Required]
        public string INDUSTRY_TYP { get; set; }
        public string AUTH_TERM_ID { get; set; }
        public string SETTLE_TERM_ID { get; set; }
        [Required]
        public string REQ_PURCH_CARD_PO_NO { get; set; }
        public string EDC_CONFIG { get; set; }
        [Required]
        public string EDC_MODE { get; set; }
        [Required]
        public string HOLD_NO_METH { get; set; }
        public string NXT_HOLD_NO { get; set; }
        [Required]
        public string NXT_HOLD_NO_AUTO { get; set; }
        [Required]
        public string STA_DFLT_METH { get; set; }
        [Required]
        public string ALLOW_STA_CHNG { get; set; }
        [Required]
        public string DRW_DFLT_METH { get; set; }
        [Required]
        public string ALLOW_DRW_CHNG { get; set; }
        [Required]
        public string QUOT_NO_METH { get; set; }
        public string NXT_QUOT_NO { get; set; }
        [Required]
        public string NXT_QUOT_NO_AUTO { get; set; }
        public int? QUOT_VAL_DAYS { get; set; }
        public string NXT_ORD_NO { get; set; }
        [Required]
        public string NXT_ORD_NO_AUTO { get; set; }
        [Required]
        public string ORD_NO_METH { get; set; }
        public string ORD_DEP_RECVD_ACCT_NO { get; set; }
        [Required]
        public string ORD_DEP_RECVD_METH { get; set; }
        public string ORD_DEP_FORF_ACCT_NO { get; set; }
        [Required]
        public string ORD_DEP_FORF_METH { get; set; }
        [Required]
        public string ALLOW_OTHR_STR_ORDS { get; set; }
        [Required]
        public string SHOW_UNSHIPPED_ORD_LINS { get; set; }
        [Required]
        public string CHK_FOR_ORDS { get; set; }
        [Required]
        public string WARN_ORD_REL_UNPICKD { get; set; }
        [Required]
        public string WARN_ORD_EDIT_PICKD { get; set; }
        [Required]
        public string USE_ORD_SHIP_TO { get; set; }
        [Required]
        public string QTY_OVRD_METH { get; set; }
        [Required]
        public string MIN_PRC_LVL { get; set; }
        [Required]
        public string MIN_PFT_PCT_METH { get; set; }
        public decimal? MIN_PFT_PCT { get; set; }
        [Required]
        public string MIN_PFT_PCT_COST { get; set; }
        [Required]
        public string RNDM_WEIGHT_BARCOD { get; set; }
        [Required]
        public string RNDM_WEIGHT_QTY_1 { get; set; }
        [Required]
        public string USE_OPN_DRW_ALARM { get; set; }
        public int? DRW_ALARM_TIMEOUT { get; set; }
        public string DRW_ALARM_SND { get; set; }
        public int? DRW_ALARM_REPEAT { get; set; }
        [Required]
        public string OFFLINE_GFC_ISSUE { get; set; }
        [Required]
        public string OFFLINE_STC_ISSUE { get; set; }
        [Required]
        public string OFFLINE_GFC_REDEEM { get; set; }
        [Required]
        public string OFFLINE_STC_REDEEM { get; set; }
        [Required]
        public string OFFLINE_PROC_ORDS { get; set; }
        [Required]
        public string SHOW_GC_AS_LINS { get; set; }
        [Required]
        public string PAY_IN_METH { get; set; }
        public string PAY_IN_ACCT_NO { get; set; }
        [Required]
        public string ALLOW_PAY_IN_CHNG { get; set; }
        [Required]
        public string PAY_OUT_METH { get; set; }
        public string PAY_OUT_ACCT_NO { get; set; }
        [Required]
        public string TIP_METH { get; set; }
        public string TIP_ACCT_NO { get; set; }
        [Required]
        public string ALLOW_PAY_OUT_CHNG { get; set; }
        [Required]
        public string USE_AMEX_DIRECT { get; set; }
        public string AMEX_SE_NO { get; set; }
        [Required]
        public string USE_AMEX_AAV { get; set; }
        [Required]
        public string USE_AMEX_CID { get; set; }
        [Required]
        public string USE_DISC_AVS { get; set; }
        [Required]
        public string USE_DISC_CID { get; set; }
        [Required]
        public string USE_ORD { get; set; }
        [Required]
        public string USE_LWY { get; set; }
        [Required]
        public string LWY_NO_METH { get; set; }
        public string NXT_LWY_NO { get; set; }
        [Required]
        public string NXT_LWY_NO_AUTO { get; set; }
        [Required]
        public string OFFLINE_PROC_LWYS { get; set; }
        [Required]
        public string ALLOW_ADD_OFFLINE_LWYS { get; set; }
        [Required]
        public string ALLOW_ADD_OFFLINE_ORDS { get; set; }
        [Required]
        public string ALLOW_OTHR_STR_LWYS { get; set; }
        [Required]
        public string USE_LWY_SHIP_TO { get; set; }
        [Required]
        public string CHK_FOR_LWYS { get; set; }
        [Required]
        public string WARN_LWY_REL_UNPICKD { get; set; }
        [Required]
        public string WARN_LWY_EDIT_PICKD { get; set; }
        public string LWY_DEP_RECVD_ACCT_NO { get; set; }
        [Required]
        public string LWY_DEP_RECVD_METH { get; set; }
        public string LWY_DEP_FORF_ACCT_NO { get; set; }
        [Required]
        public string LWY_DEP_FORF_METH { get; set; }
        [Required]
        public decimal MIN_ORD_DEP_AMT { get; set; }
        [Required]
        public decimal MIN_BO_DEP_AMT { get; set; }
        [Required]
        public decimal MIN_SO_DEP_AMT { get; set; }
        [Required]
        public decimal MIN_LWY_DEP_AMT { get; set; }
        [Required]
        public decimal MIN_ORD_DEP_PCT { get; set; }
        [Required]
        public decimal MIN_BO_DEP_PCT { get; set; }
        [Required]
        public decimal MIN_SO_DEP_PCT { get; set; }
        [Required]
        public decimal MIN_LWY_DEP_PCT { get; set; }
        [Required]
        public string SHOW_UNSHIPPED_LWY_LINS { get; set; }
        [Required]
        public string ORD_QTY_OVRD_METH { get; set; }
        [Required]
        public string LWY_QTY_OVRD_METH { get; set; }
        [Required]
        public string SAL_INSUFF_QTY_LIN_TYP { get; set; }
        [Required]
        public string ORD_INSUFF_QTY_LIN_TYP { get; set; }
        [Required]
        public int SAL_COLOR { get; set; }
        [Required]
        public int RET_COLOR { get; set; }
        [Required]
        public int ORD_COLOR { get; set; }
        [Required]
        public int BO_COLOR { get; set; }
        [Required]
        public int SO_COLOR { get; set; }
        [Required]
        public int LWY_COLOR { get; set; }
        [Required]
        public int GC_COLOR { get; set; }
        [Required]
        public int UNSHIPPED_COLOR { get; set; }
        [Required]
        public int FULLSHIP_COLOR { get; set; }
        [Required]
        public int UNSELECTED_ORD_COLOR { get; set; }
        [Required]
        public int UNSELECTED_BO_COLOR { get; set; }
        [Required]
        public int UNSELECTED_SO_COLOR { get; set; }
        [Required]
        public int UNSELECTED_LWY_COLOR { get; set; }
        [Required]
        public int TND_COLOR { get; set; }
        [Required]
        public int CHNG_COLOR { get; set; }
        [Required]
        public int ORD_FINAL_PMT_COLOR { get; set; }
        [Required]
        public int ORD_DEP_ACTIV_COLOR { get; set; }
        [Required]
        public int LWY_FINAL_PMT_COLOR { get; set; }
        [Required]
        public int LWY_DEP_ACTIV_COLOR { get; set; }
        [Required]
        public int DROPSHIP_ORD_COLOR { get; set; }
        [Required]
        public int DROPSHIP_SAL_COLOR { get; set; }
        [Required]
        public int UNSELECTED_DROPSHIP_ORD_COLOR { get; set; }
        [Required]
        public string LIN_TYP_1 { get; set; }
        [Required]
        public string LIN_TYP_2 { get; set; }
        [Required]
        public string LIN_TYP_3 { get; set; }
        [Required]
        public string LIN_TYP_4 { get; set; }
        [Required]
        public string LIN_TYP_5 { get; set; }
        [Required]
        public string LIN_TYP_6 { get; set; }
        [Required]
        public string LIN_TYP_7 { get; set; }
        [Required]
        public string LIN_TYP_8 { get; set; }
        [Required]
        public string USE_ORD_NO_AS_TKT_NO { get; set; }
        [Required]
        public string USE_LWY_NO_AS_TKT_NO { get; set; }
        [Required]
        public string ORD_REL_STATE { get; set; }
        [Required]
        public string BO_REL_STATE { get; set; }
        [Required]
        public string SO_REL_STATE { get; set; }
        [Required]
        public string LWY_REL_STATE { get; set; }
        public string RCPT_MSG_1 { get; set; }
        public string RCPT_MSG_2 { get; set; }
        public string RCPT_MSG_3 { get; set; }
        public string RCPT_MSG_4 { get; set; }
        public string RCPT_MSG_5 { get; set; }
        public string RCPT_MSG_6 { get; set; }
        public string RCPT_MSG_7 { get; set; }
        public string RCPT_MSG_8 { get; set; }
        public string RCPT_MSG_9 { get; set; }
        public string RCPT_MSG_10 { get; set; }
        [Required]
        public string RCPT_DET_TYP { get; set; }
        [Required]
        public string AOF_ITEM_FROM_NOF_DLG { get; set; }
        [Required]
        public string AOF_ITEM_FROM_LKUP_DLG { get; set; }
        [Required]
        public string AOF_CUST_FROM_NOF_DLG { get; set; }
        [Required]
        public string AOF_CUST_FROM_LKUP_DLG { get; set; }
        [Required]
        public string ALLOW_OTHR_STR_HOLDS { get; set; }
        [Required]
        public string ALLOW_OTHR_STR_QUOTS { get; set; }
        [Required]
        public string RETAIN_CR_CARD_NO_HIST { get; set; }
        [Required]
        public string WARN_DISCONT_ON_SAL { get; set; }
        [Required]
        public string WARN_DISCONT_ON_RET { get; set; }
        [Required]
        public string WARN_DISCONT_ON_ORD { get; set; }
        [Required]
        public string WARN_DISCONT_ON_SO { get; set; }
        [Required]
        public string WARN_DISCONT_ON_BO { get; set; }
        [Required]
        public string WARN_DISCONT_ON_LWY { get; set; }
        [Required]
        public string WARN_DISCONT_ON_DROPSHIP { get; set; }
        [Required]
        public string AUTO_HOLD_RECALL_FOR_LIN_CHNG { get; set; }
        [Required]
        public string AUTO_HOLD_RECALL_BEFORE_PMTS { get; set; }
        [Required]
        public string USE_EBT { get; set; }
        public string EBT_FCS_ID { get; set; }
        [Required]
        public string USE_PREAUTH { get; set; }
        [Required]
        public string SHOW_LONG_DESCR { get; set; }
        [Required]
        public string TOT_DISC_TYP { get; set; }
        [Required]
        public decimal MIN_DISC_PCT_TO_PRT { get; set; }
        [Required]
        public string RECALC_PRC_ON_ORD_EDIT { get; set; }
        [Required]
        public string RECALC_PRC_ON_LWY_EDIT { get; set; }
        [Required]
        public string USE_SVC { get; set; }
        [Required]
        public string ALLOW_HDR_STK_LOC_CHNG { get; set; }
        [Required]
        public string ALLOW_HDR_PRC_LOC_CHNG { get; set; }
        [Required]
        public string ALLOW_HDR_PFT_CTR_CHNG { get; set; }
        [Required]
        public string ALLOW_HDR_PO_NO_CHNG { get; set; }
        [Required]
        public string PROMPT_HDR_STK_LOC { get; set; }
        [Required]
        public string PROMPT_HDR_PRC_LOC { get; set; }
        [Required]
        public string PROMPT_HDR_PFT_CTR { get; set; }
        [Required]
        public string PROMPT_HDR_PO_NO { get; set; }
        [Required]
        public string ALLOW_LIN_STK_LOC_CHNG { get; set; }
        [Required]
        public string ALLOW_LIN_PRC_LOC_CHNG { get; set; }
        [Required]
        public string ALLOW_LIN_PFT_CTR_CHNG { get; set; }
        [Required]
        public string PROMPT_LIN_STK_LOC { get; set; }
        [Required]
        public string PROMPT_LIN_PRC_LOC { get; set; }
        [Required]
        public string PROMPT_LIN_PFT_CTR { get; set; }
        [Required]
        public int SVC_COLOR { get; set; }
        [Required]
        public string ORD_GRID_DLG_TO_SHOW_FST { get; set; }
        [Required]
        public string SAL_GRID_DLG_TO_SHOW_FST { get; set; }
        [Required]
        public string LWY_GRID_DLG_TO_SHOW_FST { get; set; }
        [Required]
        public string PROMPT_PROF_FLDS { get; set; }
        [Required]
        public string USE_ITEM_TOT_QTY_FOR_PRC { get; set; }
        [Required]
        public string ALLOW_REISSUE_CHNG { get; set; }
        [Required]
        public string HOLD_AND_RECALL_REPRICE { get; set; }
        [Required]
        public string CLS_AFTER_ACTIVATE { get; set; }
        [Required]
        public string CLS_AFTER_COUNT { get; set; }
        [Required]
        public string CLS_AFTER_RECON { get; set; }
        [Required]
        public string SUPPRESS_EDC_AUTH_MSG { get; set; }
        [Required]
        public string SUPPRESS_TKT_COMP_MSG { get; set; }
        public string DFLT_RET_REAS { get; set; }
        [Required]
        public int VAL_RET_COLOR { get; set; }
        [Required]
        public string ALLOW_OTHR_STR_VAL_RETS { get; set; }
        [Required]
        public string ALLOW_COMBINED_VAL_RET { get; set; }
        [Required]
        public string CLS_AFTER_DROP { get; set; }
        [Required]
        public string CLS_AFTER_LOAN { get; set; }
        public decimal? MAX_DISC_AMT { get; set; }
        public decimal? MAX_DISC_PCT { get; set; }
        public long? PS_HDR_CUST_FLD_FRM_ID { get; set; }
        public long? PS_PMT_CUST_FLD_FRM_ID { get; set; }
        public string RCPT_SUBJECT { get; set; }
        public string RCPT_BODY { get; set; }
        [Required]
        public string USE_OLD_DEV_FRMWK { get; set; }
        [Required]
        public string ASSGN_DRWS_BY { get; set; }
        [Required]
        public string ASSGN_DRW_DEV { get; set; }
        [Required]
        public string AUTO_REL_DRW_DEV_AT { get; set; }
        public string EDC_POS_PWD { get; set; }
        public string EDC_PORTAL_PWD { get; set; }
        [Required]
        public string RESTRICT_MANUAL_WEIGHT_ENTRY { get; set; }
        [Required]
        public string REQ_CRD_ENC_LVL { get; set; }
        [Required]
        public string OFFLINE_CUST_EDIT { get; set; }
        [Required]
        public string TAX_INCL_STR { get; set; }
        [Required]
        public string ALLOW_5_DIGIT_PLU { get; set; }
    }

}
#pragma warning restore 1591
