// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class VI_PO_RTV_HIST 
    {
        [Required]
        public string RTV_NO { get; set; }
        [Required]
        public string EVENT_NO { get; set; }
        public string BAT_ID { get; set; }
        [Required]
        public string VEND_NO { get; set; }
        public string VEND_FST_NAM { get; set; }
        public string VEND_FST_NAM_UPR { get; set; }
        public string VEND_LST_NAM { get; set; }
        public string VEND_LST_NAM_UPR { get; set; }
        public string VEND_NAM { get; set; }
        public string VEND_NAM_UPR { get; set; }
        public string VEND_SALUTATION { get; set; }
        public string VEND_ADRS_1 { get; set; }
        public string VEND_ADRS_2 { get; set; }
        public string VEND_ADRS_3 { get; set; }
        public string VEND_CITY { get; set; }
        public string VEND_STATE { get; set; }
        public string VEND_ZIP_COD { get; set; }
        public string VEND_CNTRY { get; set; }
        public string VEND_PHONE { get; set; }
        public string VEND_FAX { get; set; }
        public string VEND_CONTCT_1 { get; set; }
        public string VEND_CONTCT_2 { get; set; }
        [Required]
        public decimal RTV_MISC_AMT_1 { get; set; }
        [Required]
        public decimal RTV_MISC_AMT_2 { get; set; }
        [Required]
        public decimal RTV_MISC_AMT_3 { get; set; }
        [Required]
        public decimal RTV_MISC_AMT_4 { get; set; }
        [Required]
        public decimal RTV_MISC_AMT_5 { get; set; }
        [Required]
        public decimal RTV_TOT_MISC { get; set; }
        [Required]
        public decimal RTV_SUB_TOT { get; set; }
        [Required]
        public decimal RTV_TOT { get; set; }
        [Required]
        public DateTime RTV_DAT { get; set; }
        public string RTV_SHIP_VIA_COD { get; set; }
        [Required]
        public string RTV_LOC_ID { get; set; }
        [Required]
        public decimal TOT_QTY_TO_RETN { get; set; }
        public string USR_ID { get; set; }
        [Required]
        public string VCHR_STAT { get; set; }
        public string REF { get; set; }
        public string COMMNT_1 { get; set; }
        public string COMMNT_2 { get; set; }
        public string COMMNT_3 { get; set; }
        public DateTime? LST_MAINT_DT { get; set; }
        public string LST_MAINT_USR_ID { get; set; }
        public DateTime? LST_LCK_DT { get; set; }
        public byte[] ROW_TS { get; set; }
        [Required]
        public string RMA_NO { get; set; }
        [Required]
        public decimal TOT_EXT_COST { get; set; }
        public decimal? RTV_TOT_WEIGHT { get; set; }
        public decimal? RTV_TOT_CUBE { get; set; }
        public decimal? TOT_QTY_RETD_IN_STK_UNITS { get; set; }
        [Required]
        public string CURNCY_COD { get; set; }
        [Required]
        public string MISC_1_CURNCY_COD { get; set; }
        [Required]
        public string MISC_2_CURNCY_COD { get; set; }
        [Required]
        public string MISC_3_CURNCY_COD { get; set; }
        [Required]
        public string MISC_4_CURNCY_COD { get; set; }
        [Required]
        public string MISC_5_CURNCY_COD { get; set; }
        [Required]
        public decimal RTV_EXCH_RATE_NUMER { get; set; }
        [Required]
        public decimal RTV_EXCH_RATE_DENOM { get; set; }
        [Required]
        public decimal RTV_MISC_1_EXCH_RATE_NUMER { get; set; }
        [Required]
        public decimal RTV_MISC_1_EXCH_RATE_DENOM { get; set; }
        [Required]
        public decimal RTV_MISC_2_EXCH_RATE_NUMER { get; set; }
        [Required]
        public decimal RTV_MISC_2_EXCH_RATE_DENOM { get; set; }
        [Required]
        public decimal RTV_MISC_3_EXCH_RATE_NUMER { get; set; }
        [Required]
        public decimal RTV_MISC_3_EXCH_RATE_DENOM { get; set; }
        [Required]
        public decimal RTV_MISC_4_EXCH_RATE_NUMER { get; set; }
        [Required]
        public decimal RTV_MISC_4_EXCH_RATE_DENOM { get; set; }
        [Required]
        public decimal RTV_MISC_5_EXCH_RATE_NUMER { get; set; }
        [Required]
        public decimal RTV_MISC_5_EXCH_RATE_DENOM { get; set; }
        public decimal? RTV_SUB_TOT_HOME { get; set; }
        public decimal? RTV_MISC_AMT_1_HOME { get; set; }
        public decimal? RTV_MISC_AMT_2_HOME { get; set; }
        public decimal? RTV_MISC_AMT_3_HOME { get; set; }
        public decimal? RTV_MISC_AMT_4_HOME { get; set; }
        public decimal? RTV_MISC_AMT_5_HOME { get; set; }
        public decimal? RTV_TOT_MISC_HOME { get; set; }
        public decimal? TOT_RTV_ADJUST_AMT { get; set; }
        public string YOUR_TAX_ID_NO { get; set; }
        public string VEND_TAX_ID_NO { get; set; }
        public string TAX_COD_NORM { get; set; }
        public string TAX_COD { get; set; }
        [Required]
        public string TAX_COD_CHNGD { get; set; }
        [Required]
        public decimal RTV_TAX_AMT_NORM_HOME { get; set; }
        public decimal? RTV_TAX_AMT_NORM { get; set; }
        [Required]
        public string RTV_HAS_TAX_OVRD { get; set; }
        [Required]
        public decimal RTV_TAX_AMT_HOME { get; set; }
        public decimal? RTV_TAX_AMT { get; set; }
        public decimal? RTV_TOT_HOME { get; set; }
        public decimal? VCHR_SUB_TOT { get; set; }
        public decimal? VCHR_MISC_AMT_1 { get; set; }
        public decimal? VCHR_MISC_AMT_2 { get; set; }
        public decimal? VCHR_MISC_AMT_3 { get; set; }
        public decimal? VCHR_MISC_AMT_4 { get; set; }
        public decimal? VCHR_MISC_AMT_5 { get; set; }
        public decimal? VCHR_TOT_MISC { get; set; }
        public decimal? VCHR_TAX_AMT { get; set; }
        public decimal? VCHR_TOT { get; set; }
        public decimal? BAL_SUB_TOT { get; set; }
        public decimal? BAL_MISC_AMT_1 { get; set; }
        public decimal? BAL_MISC_AMT_2 { get; set; }
        public decimal? BAL_MISC_AMT_3 { get; set; }
        public decimal? BAL_MISC_AMT_4 { get; set; }
        public decimal? BAL_MISC_AMT_5 { get; set; }
        public decimal? BAL_TAX_AMT { get; set; }
        public decimal? BAL_TAX_AMT_HOME { get; set; }
        public decimal? VCHR_SUB_TOT_HOME { get; set; }
        public decimal? VCHR_MISC_AMT_1_HOME { get; set; }
        public decimal? VCHR_MISC_AMT_2_HOME { get; set; }
        public decimal? VCHR_MISC_AMT_3_HOME { get; set; }
        public decimal? VCHR_MISC_AMT_4_HOME { get; set; }
        public decimal? VCHR_MISC_AMT_5_HOME { get; set; }
        public decimal? VCHR_TOT_MISC_HOME { get; set; }
        public decimal? VCHR_TAX_AMT_HOME { get; set; }
        public decimal? VCHR_TOT_HOME { get; set; }
        public decimal? VCHR_SUB_TOT_GAIN_LOSS_HOME { get; set; }
        public decimal? VCHR_MISC_1_GAIN_LOSS_HOME { get; set; }
        public decimal? VCHR_MISC_2_GAIN_LOSS_HOME { get; set; }
        public decimal? VCHR_MISC_3_GAIN_LOSS_HOME { get; set; }
        public decimal? VCHR_MISC_4_GAIN_LOSS_HOME { get; set; }
        public decimal? VCHR_MISC_5_GAIN_LOSS_HOME { get; set; }
        public decimal? VCHR_TAX_GAIN_LOSS_HOME { get; set; }
        public decimal? VCHR_TOT_GAIN_LOSS_HOME { get; set; }
        public decimal? VCHR_TOT_WITH_GAIN_LOSS_HOME { get; set; }
        public string VCHR_NO { get; set; }
        public string VCHR_VEND_NO { get; set; }
        public DateTime? VCHR_DAT { get; set; }
        public DateTime? VCHR_TIM { get; set; }
        public string VCHR_BY { get; set; }
        public string VCHR_INVC_NO { get; set; }
        public DateTime? VCHR_INVC_DAT { get; set; }
        public DateTime? VCHR_DIST_DAT { get; set; }
        public string VCHR_REF { get; set; }
        public decimal? BAL_SUB_TOT_HOME { get; set; }
        public decimal? BAL_MISC_AMT_1_HOME { get; set; }
        public decimal? BAL_MISC_AMT_2_HOME { get; set; }
        public decimal? BAL_MISC_AMT_3_HOME { get; set; }
        public decimal? BAL_MISC_AMT_4_HOME { get; set; }
        public decimal? BAL_MISC_AMT_5_HOME { get; set; }
        public decimal? BAL_TOT_MISC_HOME { get; set; }
        public decimal? BAL_TOT_HOME { get; set; }
        public decimal? BAL_TOT_MISC { get; set; }
        public decimal? BAL_TOT { get; set; }
    }

}
#pragma warning restore 1591
