// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class VI_PS_VALIDATED_RETURNS_PMT 
    {
        public DateTime? BUS_DAT { get; set; }
        [Required]
        public long DOC_ID { get; set; }
        [Required]
        public int PMT_SEQ_NO { get; set; }
        public string PAY_COD { get; set; }
        [Required]
        public string PMT_LIN_TYP { get; set; }
        [Required]
        public string PMT_TYP { get; set; }
        [Required]
        public string PAY_COD_TYP { get; set; }
        public string DESCR { get; set; }
        [Required]
        public string PAY_TYP { get; set; }
        [Required]
        public decimal AMT { get; set; }
        [Required]
        public string CURNCY_COD { get; set; }
        [Required]
        public decimal HOME_CURNCY_AMT { get; set; }
        [Required]
        public decimal EXCH_LOSS { get; set; }
        [Required]
        public decimal EXCH_RATE_NUMER { get; set; }
        [Required]
        public decimal EXCH_RATE_DENOM { get; set; }
        [Required]
        public string IS_FOREIGN { get; set; }
        public string CR_CARD_NO_MSK { get; set; }
        public byte[] CR_CARD_NO_ENC { get; set; }
        public byte? CR_CARD_NO_KID { get; set; }
        public string CR_CARD_NAM { get; set; }
        public DateTime? CR_CARD_EXP_DAT { get; set; }
        public string UNIQUE_TRANS_ID { get; set; }
        public string PROCESSOR_TRANS_ID { get; set; }
        public string AVS_ADRS { get; set; }
        public string AVS_ZIP_COD { get; set; }
        public string IS_PURCH_CARD { get; set; }
        public string CHK_ACCT_NO { get; set; }
        public string CHK_TRANSIT_NO { get; set; }
        public string CHK_NO { get; set; }
        public string CHK_DRIV_LIC_NO { get; set; }
        public string CHK_DRIV_LIC_STATE { get; set; }
        public DateTime? CHK_BIRTH_DAT { get; set; }
        public string REF_1 { get; set; }
        public string PROMPT_1 { get; set; }
        public string REF_2 { get; set; }
        public string PROMPT_2 { get; set; }
        public string REF_3 { get; set; }
        public string PROMPT_3 { get; set; }
        public int? LOY_PTS_RDM { get; set; }
    }

}
#pragma warning restore 1591
