// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace KyGunCo.Counterpoint.Sdk.Data
{
    using System;
    using ServiceStack.DataAnnotations;
    using ServiceStack.Model;
    using ServiceStack;

    public partial class VI_TKT_HIST_PAY_COD 
    {
        [Required]
        public string STR_ID { get; set; }
        public string PAY_COD { get; set; }
        [Required]
        public DateTime POST_DAT { get; set; }
        public string DESCR { get; set; }
        public int? TKT_COUNT { get; set; }
        public decimal? TOT_TND { get; set; }
        public decimal? TOT_REF { get; set; }
        public decimal? TOT_CHNG { get; set; }
        public decimal? PAY_IN_AMT { get; set; }
        public decimal? PAY_OUT_AMT { get; set; }
        public int? TND_LINS { get; set; }
        public int? REF_LINS { get; set; }
        public int? CHNG_LINS { get; set; }
        public int? PAY_IN_LINS { get; set; }
        public int? PAY_OUT_LINS { get; set; }
        public decimal? EXCH_LOSS { get; set; }
        public decimal? NET_PMT_AMT { get; set; }
        public string IS_FOREIGN { get; set; }
    }

}
#pragma warning restore 1591
