// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // AR_CTL
    public class ArCtl
    {
        public int KeyId { get; set; } = 1; // KEY_ID (Primary key)
        public string AgeMeth { get; set; } = "I"; // AGE_METH (length: 1)
        public int NoOfAgePrds { get; set; } = 4; // NO_OF_AGE_PRDS
        public int? MaxAgePrd1 { get; set; } = 30; // MAX_AGE_PRD_1
        public string AgePrd1Msg1 { get; set; } // AGE_PRD_1_MSG_1 (length: 30)
        public string AgePrd1Msg2 { get; set; } // AGE_PRD_1_MSG_2 (length: 30)
        public int? MaxAgePrd2 { get; set; } = 60; // MAX_AGE_PRD_2
        public string AgePrd2Msg1 { get; set; } // AGE_PRD_2_MSG_1 (length: 30)
        public string AgePrd2Msg2 { get; set; } // AGE_PRD_2_MSG_2 (length: 30)
        public int? MaxAgePrd3 { get; set; } = 90; // MAX_AGE_PRD_3
        public string AgePrd3Msg1 { get; set; } // AGE_PRD_3_MSG_1 (length: 30)
        public string AgePrd3Msg2 { get; set; } // AGE_PRD_3_MSG_2 (length: 30)
        public int? MaxAgePrd4 { get; set; } = 120; // MAX_AGE_PRD_4
        public string AgePrd4Msg1 { get; set; } // AGE_PRD_4_MSG_1 (length: 30)
        public string AgePrd4Msg2 { get; set; } // AGE_PRD_4_MSG_2 (length: 30)
        public string AgePrd5Msg1 { get; set; } // AGE_PRD_5_MSG_1 (length: 30)
        public string AgePrd5Msg2 { get; set; } // AGE_PRD_5_MSG_2 (length: 30)
        public string AdjJrnlPrtMeth { get; set; } = "P"; // ADJ_JRNL_PRT_METH (length: 1)
        public string CrJrnlPrtMeth { get; set; } = "P"; // CR_JRNL_PRT_METH (length: 1)
        public decimal? MaxWrtoffAmt { get; set; } // MAX_WRTOFF_AMT
        public string NoMaxWrtoffAmt { get; set; } = "Y"; // NO_MAX_WRTOFF_AMT (length: 1)
        public string WrtoffAcctNo { get; set; } // WRTOFF_ACCT_NO (length: 20)
        public string WrtoffMeth { get; set; } = "!"; // WRTOFF_METH (length: 1)
        public string CrAvailInclOrds { get; set; } = "N"; // CR_AVAIL_INCL_ORDS (length: 1)
        public DateTime? LstStmntBegDat { get; set; } // LST_STMNT_BEG_DAT
        public DateTime? LstStmntEndDat { get; set; } // LST_STMNT_END_DAT
        public string CustProfAlpha1 { get; set; } = "N"; // CUST_PROF_ALPHA_1 (length: 1)
        public string CustProfAlpha2 { get; set; } = "N"; // CUST_PROF_ALPHA_2 (length: 1)
        public string CustProfAlpha3 { get; set; } = "N"; // CUST_PROF_ALPHA_3 (length: 1)
        public string CustProfAlpha4 { get; set; } = "N"; // CUST_PROF_ALPHA_4 (length: 1)
        public string CustProfAlpha5 { get; set; } = "N"; // CUST_PROF_ALPHA_5 (length: 1)
        public string CustProfCod1 { get; set; } = "N"; // CUST_PROF_COD_1 (length: 1)
        public string CustProfCod2 { get; set; } = "N"; // CUST_PROF_COD_2 (length: 1)
        public string CustProfCod3 { get; set; } = "N"; // CUST_PROF_COD_3 (length: 1)
        public string CustProfCod4 { get; set; } = "N"; // CUST_PROF_COD_4 (length: 1)
        public string CustProfCod5 { get; set; } = "N"; // CUST_PROF_COD_5 (length: 1)
        public string CustProfDat1 { get; set; } = "N"; // CUST_PROF_DAT_1 (length: 1)
        public string CustProfDat2 { get; set; } = "N"; // CUST_PROF_DAT_2 (length: 1)
        public string CustProfDat3 { get; set; } = "N"; // CUST_PROF_DAT_3 (length: 1)
        public string CustProfDat4 { get; set; } = "N"; // CUST_PROF_DAT_4 (length: 1)
        public string CustProfDat5 { get; set; } = "N"; // CUST_PROF_DAT_5 (length: 1)
        public string CustProfNo1 { get; set; } = "N"; // CUST_PROF_NO_1 (length: 1)
        public string CustProfNo2 { get; set; } = "N"; // CUST_PROF_NO_2 (length: 1)
        public string CustProfNo3 { get; set; } = "N"; // CUST_PROF_NO_3 (length: 1)
        public string CustProfNo4 { get; set; } = "N"; // CUST_PROF_NO_4 (length: 1)
        public string CustProfNo5 { get; set; } = "N"; // CUST_PROF_NO_5 (length: 1)
        public string AdjJrnlDist { get; set; } = "Y"; // ADJ_JRNL_DIST (length: 1)
        public string CrJrnlDist { get; set; } = "Y"; // CR_JRNL_DIST (length: 1)
        public DateTime? LstMaintDt { get; set; } // LST_MAINT_DT
        public string LstMaintUsrId { get; set; } // LST_MAINT_USR_ID (length: 10)
        public DateTime? LstLckDt { get; set; } // LST_LCK_DT
        public byte[] RowTs { get; set; } // ROW_TS
        public string UseSimpleCustAof { get; set; } = "N"; // USE_SIMPLE_CUST_AOF (length: 1)
        public string CrAvailInclLwys { get; set; } = "N"; // CR_AVAIL_INCL_LWYS (length: 1)
        public string UseLoyPgms { get; set; } = "N"; // USE_LOY_PGMS (length: 1)
        public string PtAdjJrnlPrtMeth { get; set; } = "P"; // PT_ADJ_JRNL_PRT_METH (length: 1)
        public string FchJrnlPrtMeth { get; set; } = "P"; // FCH_JRNL_PRT_METH (length: 1)
        public string FchJrnlDist { get; set; } = "Y"; // FCH_JRNL_DIST (length: 1)
        public string AcctMgmtNoteId { get; set; } // ACCT_MGMT_NOTE_ID (length: 20)
        public string SavStmntsToDisk { get; set; } = "N"; // SAV_STMNTS_TO_DISK (length: 1)
        public DateTime? RsUtcDt { get; set; } = DateTime.UtcNow; // RS_UTC_DT
        public string EmailStatements { get; set; } = "Y"; // EMAIL_STATEMENTS (length: 1)
        public string StmntSubject { get; set; } // STMNT_SUBJECT (length: 100)
        public string StmntBody { get; set; } // STMNT_BODY (length: 1000)
        public byte RsStat { get; set; } = 1; // RS_STAT
    }

}
// </auto-generated>
