// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // AR_CUST_CARDS
    public class ArCustCard
    {
        public string CustNo { get; set; } // CUST_NO (Primary key) (length: 15)
        public int CardSeqNo { get; set; } // CARD_SEQ_NO (Primary key)
        public string DefaultCard { get; set; } = "N"; // DEFAULT_CARD (length: 1)
        public string CardDescr { get; set; } // CARD_DESCR (length: 30)
        public string PayCod { get; set; } // PAY_COD (length: 10)
        public string CardNo { get; set; } // CARD_NO (length: 30)
        public string CardNoMsk { get; set; } // CARD_NO_MSK (length: 30)
        public DateTime CardExpDat { get; set; } // CARD_EXP_DAT
        public string CardNam { get; set; } // CARD_NAM (length: 30)
        public byte[] CardNoEnc { get; set; } // CARD_NO_ENC (length: 32)
        public byte CardNoKid { get; set; } // CARD_NO_KID

        // Foreign keys

        /// <summary>
        /// Parent ArCust pointed by [AR_CUST_CARDS].([CustNo]) (FK_AR_CUST_CARDS_AR_CUST)
        /// </summary>
        public virtual ArCust ArCust { get; set; } // FK_AR_CUST_CARDS_AR_CUST
    }

}
// </auto-generated>
