// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // AR_CUST_RECALC_WRK
    public class ArCustRecalcWrk
    {
        public string SessId { get; set; } // SESS_ID (Primary key) (length: 40)
        public string CustNo { get; set; } // CUST_NO (Primary key) (length: 15)
        public string Nam { get; set; } // NAM (length: 40)
        public string WhatsWrong { get; set; } // WHATS_WRONG (length: 255)
        public decimal? CustBal { get; set; } // CUST_BAL
        public decimal? TrxBal { get; set; } // TRX_BAL
        public decimal? CustUnpstdBal { get; set; } // CUST_UNPSTD_BAL
        public decimal? TrxUnpstdBal { get; set; } // TRX_UNPSTD_BAL
        public int? CustNoOfOrds { get; set; } // CUST_NO_OF_ORDS
        public int? TrxNoOfOrds { get; set; } // TRX_NO_OF_ORDS
        public decimal? CustOrdBal { get; set; } // CUST_ORD_BAL
        public decimal? TrxOrdBal { get; set; } // TRX_ORD_BAL
        public int? CustNoOfLwys { get; set; } // CUST_NO_OF_LWYS
        public int? TrxNoOfLwys { get; set; } // TRX_NO_OF_LWYS
        public decimal? CustLwyBal { get; set; } // CUST_LWY_BAL
        public decimal? TrxLwyBal { get; set; } // TRX_LWY_BAL
        public DateTime? LstMaintDt { get; set; } // LST_MAINT_DT
        public string LstMaintUsrId { get; set; } // LST_MAINT_USR_ID (length: 10)
        public DateTime? LstLckDt { get; set; } // LST_LCK_DT
        public byte[] RowTs { get; set; } // ROW_TS
        public decimal? BalDiff { get; private set; } // BAL_DIFF
        public decimal? LwyBalDiff { get; private set; } // LWY_BAL_DIFF
        public int? NoOfLwysDiff { get; private set; } // NO_OF_LWYS_DIFF
        public int? NoOfOrdsDiff { get; private set; } // NO_OF_ORDS_DIFF
        public decimal? OrdBalDiff { get; private set; } // ORD_BAL_DIFF
        public decimal? UnpstdBalDiff { get; private set; } // UNPSTD_BAL_DIFF
    }

}
// </auto-generated>
