// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // DM_AGG_STATS_LOG
    public class DmAggStatsLog
    {
        public int AggExecId { get; set; } // AGG_EXEC_ID (Primary key)
        public int AggId { get; set; } // AGG_ID (Primary key)
        public int AggDurationMs { get; set; } // AGG_DURATION_MS
        public int UpdatedRowCnt { get; set; } // UPDATED_ROW_CNT
        public int InsertedRowCnt { get; set; } // INSERTED_ROW_CNT
        public byte[] RowTs { get; set; } // ROW_TS

        // Foreign keys

        /// <summary>
        /// Parent DmAggLog pointed by [DM_AGG_STATS_LOG].([AggExecId]) (FK_DM_AGG_STATS_LOG_DM_AGG_LOG)
        /// </summary>
        public virtual DmAggLog DmAggLog { get; set; } // FK_DM_AGG_STATS_LOG_DM_AGG_LOG
    }

}
// </auto-generated>
