// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // DM_CAL_SEAS
    public class DmCalSea
    {
        public int SeasId { get; set; } // SEAS_ID (Primary key)
        public int YrId { get; set; } // YR_ID
        public string SeasNam { get; set; } // SEAS_NAM (length: 5)
        public int SeasOfYr { get; set; } // SEAS_OF_YR
        public int? SameSeasLstYr { get; set; } // SAME_SEAS_LST_YR
        public DateTime BegDat { get; set; } // BEG_DAT
        public DateTime EndDat { get; set; } // END_DAT
        public int? NxtSeasId { get; set; } // NXT_SEAS_ID
        public int? PrevSeasId { get; set; } // PREV_SEAS_ID
        public string CalndrId { get; set; } // CALNDR_ID (length: 10)
        public byte[] RowTs { get; set; } // ROW_TS

        // Foreign keys

        /// <summary>
        /// Parent DmCalYr pointed by [DM_CAL_SEAS].([YrId]) (FK_DM_CAL_SEAS_DM_CAL_YR)
        /// </summary>
        public virtual DmCalYr DmCalYr { get; set; } // FK_DM_CAL_SEAS_DM_CAL_YR
    }

}
// </auto-generated>
