// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // DM_TOT_STR_MNTH
    public class DmTotStrMnth
    {
        public int MnthId { get; set; } // MNTH_ID (Primary key)
        public string StrId { get; set; } // STR_ID (Primary key) (length: 10)
        public int TktCnt { get; set; } // TKT_CNT
        public decimal SlsQty { get; set; } // SLS_QTY
        public decimal SlsExtPrc { get; set; } // SLS_EXT_PRC
        public int SlsLinCnt { get; set; } // SLS_LIN_CNT
        public decimal RtnQty { get; set; } // RTN_QTY
        public decimal RtnExtPrc { get; set; } // RTN_EXT_PRC
        public int RtnLinCnt { get; set; } // RTN_LIN_CNT
        public decimal TotExtCost { get; set; } // TOT_EXT_COST
        public decimal TotExtCalcPrc { get; set; } // TOT_EXT_CALC_PRC
        public decimal TotExtRetlVal { get; set; } // TOT_EXT_RETL_VAL
        public decimal TotExtRegPrc { get; set; } // TOT_EXT_REG_PRC
        public decimal TotExtPrc1 { get; set; } // TOT_EXT_PRC_1
        public byte[] RowTs { get; set; } // ROW_TS

        // Foreign keys

        /// <summary>
        /// Parent DmStrHist pointed by [DM_TOT_STR_MNTH].([StrId]) (FK_DM_TOT_STR_MNTH_DM_STR_HIST)
        /// </summary>
        public virtual DmStrHist DmStrHist { get; set; } // FK_DM_TOT_STR_MNTH_DM_STR_HIST
    }

}
// </auto-generated>
