// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // IM_CNT_HIST
    public class ImCntHist
    {
        public string EventNo { get; set; } // EVENT_NO (Primary key) (length: 15)
        public string ItemNo { get; set; } // ITEM_NO (Primary key) (length: 20)
        public string LocId { get; set; } // LOC_ID (Primary key) (length: 10)
        public string Bin1 { get; set; } // BIN_1 (length: 10)
        public string Bin2 { get; set; } // BIN_2 (length: 10)
        public string Bin3 { get; set; } // BIN_3 (length: 10)
        public string Bin4 { get; set; } // BIN_4 (length: 10)
        public string Descr { get; set; } // DESCR (length: 30)
        public string DescrUpr { get; set; } // DESCR_UPR (length: 30)
        public string CategCod { get; set; } // CATEG_COD (length: 10)
        public string SubcatCod { get; set; } // SUBCAT_COD (length: 10)
        public string AcctCod { get; set; } // ACCT_COD (length: 10)
        public string ItemVendNo { get; set; } // ITEM_VEND_NO (length: 15)
        public string VendItemNo { get; set; } // VEND_ITEM_NO (length: 30)
        public string Ref { get; set; } // REF (length: 50)
        public string AddedDuringEnt { get; set; } = "Y"; // ADDED_DURING_ENT (length: 1)
        public string CreateEventNo { get; set; } // CREATE_EVENT_NO (length: 15)
        public decimal? CntQty1 { get; set; } // CNT_QTY_1
        public string CntUnit1 { get; set; } = "0"; // CNT_UNIT_1 (length: 1)
        public decimal? Unit1Numer { get; set; } = 1m; // UNIT_1_NUMER
        public decimal? Unit1Denom { get; set; } = 1m; // UNIT_1_DENOM
        public string Unit1 { get; set; } // UNIT_1 (length: 15)
        public decimal? CntQty2 { get; set; } // CNT_QTY_2
        public string CntUnit2 { get; set; } = "0"; // CNT_UNIT_2 (length: 1)
        public decimal? Unit2Numer { get; set; } = 1m; // UNIT_2_NUMER
        public decimal? Unit2Denom { get; set; } = 1m; // UNIT_2_DENOM
        public string Unit2 { get; set; } // UNIT_2 (length: 15)
        public decimal? CntQty3 { get; set; } // CNT_QTY_3
        public string CntUnit3 { get; set; } = "0"; // CNT_UNIT_3 (length: 1)
        public decimal? Unit3Numer { get; set; } = 1m; // UNIT_3_NUMER
        public decimal? Unit3Denom { get; set; } = 1m; // UNIT_3_DENOM
        public string Unit3 { get; set; } // UNIT_3 (length: 15)
        public decimal? CntQty4 { get; set; } // CNT_QTY_4
        public string CntUnit4 { get; set; } = "0"; // CNT_UNIT_4 (length: 1)
        public decimal? Unit4Numer { get; set; } = 1m; // UNIT_4_NUMER
        public decimal? Unit4Denom { get; set; } = 1m; // UNIT_4_DENOM
        public string Unit4 { get; set; } // UNIT_4 (length: 15)
        public decimal? CntQty5 { get; set; } // CNT_QTY_5
        public string CntUnit5 { get; set; } = "0"; // CNT_UNIT_5 (length: 1)
        public decimal? Unit5Numer { get; set; } = 1m; // UNIT_5_NUMER
        public decimal? Unit5Denom { get; set; } = 1m; // UNIT_5_DENOM
        public string Unit5 { get; set; } // UNIT_5 (length: 15)
        public decimal? CntQty6 { get; set; } // CNT_QTY_6
        public string CntUnit6 { get; set; } = "0"; // CNT_UNIT_6 (length: 1)
        public decimal? Unit6Numer { get; set; } = 1m; // UNIT_6_NUMER
        public decimal? Unit6Denom { get; set; } = 1m; // UNIT_6_DENOM
        public string Unit6 { get; set; } // UNIT_6 (length: 15)
        public DateTime? FrzDat { get; set; } // FRZ_DAT
        public decimal FrzQtyOnHnd { get; set; } // FRZ_QTY_ON_HND
        public decimal? AvgCost { get; set; } // AVG_COST
        public decimal? StdCost { get; set; } = 0m; // STD_COST
        public decimal? LstCost { get; set; } = 0m; // LST_COST
        public decimal? UnitRetlVal { get; set; } // UNIT_RETL_VAL
        public string DocNo { get; set; } = "PHYS-COUNT"; // DOC_NO (length: 15)
        public decimal? Cost { get; set; } // COST
        public decimal? QtyCntd { get; set; } // QTY_CNTD
        public decimal? QtyOnHndBefore { get; set; } // QTY_ON_HND_BEFORE
        public decimal? AvgCostBefore { get; set; } // AVG_COST_BEFORE
        public decimal? AvgCostAfter { get; set; } // AVG_COST_AFTER
        public decimal? ExtCost { get; set; } // EXT_COST
        public decimal? TotCostCorr { get; set; } // TOT_COST_CORR
        public decimal? UnitRetlAtPost { get; set; } // UNIT_RETL_AT_POST
        public string CostUsed { get; set; } = "C"; // COST_USED (length: 1)
        public string ItemTyp { get; set; } = "I"; // ITEM_TYP (length: 1)
        public string TrkMeth { get; set; } = "N"; // TRK_METH (length: 1)
        public string AssumedCnt { get; set; } = "N"; // ASSUMED_CNT (length: 1)
        public DateTime? LstMaintDt { get; set; } // LST_MAINT_DT
        public string LstMaintUsrId { get; set; } // LST_MAINT_USR_ID (length: 10)
        public DateTime? LstLckDt { get; set; } // LST_LCK_DT
        public byte[] RowTs { get; set; } // ROW_TS
        public DateTime PostDat { get; set; } // POST_DAT
        public int? NoOfCnts { get; private set; } // NO_OF_CNTS
        public decimal? TotCntQty { get; private set; } // TOT_CNT_QTY
        public decimal? UnitRetlAtPost1 { get; private set; } // UNIT_RETL_AT_POST_1
        public decimal? UnitRetlAtPost2 { get; private set; } // UNIT_RETL_AT_POST_2
        public decimal? UnitRetlAtPost3 { get; private set; } // UNIT_RETL_AT_POST_3
        public decimal? UnitRetlAtPost4 { get; private set; } // UNIT_RETL_AT_POST_4
        public decimal? UnitRetlAtPost5 { get; private set; } // UNIT_RETL_AT_POST_5
        public decimal? UnitRetlAtPost6 { get; private set; } // UNIT_RETL_AT_POST_6
        public decimal? UnitRetlVal1 { get; private set; } // UNIT_RETL_VAL_1
        public decimal? UnitRetlVal2 { get; private set; } // UNIT_RETL_VAL_2
        public decimal? UnitRetlVal3 { get; private set; } // UNIT_RETL_VAL_3
        public decimal? UnitRetlVal4 { get; private set; } // UNIT_RETL_VAL_4
        public decimal? UnitRetlVal5 { get; private set; } // UNIT_RETL_VAL_5
        public decimal? UnitRetlVal6 { get; private set; } // UNIT_RETL_VAL_6
        public decimal QtyAdj { get; set; } // QTY_ADJ
        public int? NoOfSersAdded { get; set; } // NO_OF_SERS_ADDED
        public int? NoOfSersRmvd { get; set; } // NO_OF_SERS_RMVD
        public decimal? SerCostIncr { get; set; } // SER_COST_INCR
        public decimal? SerCostDecr { get; set; } // SER_COST_DECR
        public int? NoOfSersFrz { get; set; } // NO_OF_SERS_FRZ
        public int? NoOfSersCntd { get; set; } // NO_OF_SERS_CNTD
        public string CntUsr1 { get; set; } // CNT_USR_1 (length: 500)
        public string CntUsr2 { get; set; } // CNT_USR_2 (length: 500)
        public string CntUsr3 { get; set; } // CNT_USR_3 (length: 500)
        public string CntUsr4 { get; set; } // CNT_USR_4 (length: 500)
        public string CntUsr5 { get; set; } // CNT_USR_5 (length: 500)
        public string CntUsr6 { get; set; } // CNT_USR_6 (length: 500)
        public string CntNote1 { get; set; } // CNT_NOTE_1 (length: 500)
        public string CntNote2 { get; set; } // CNT_NOTE_2 (length: 500)
        public string CntNote3 { get; set; } // CNT_NOTE_3 (length: 500)
        public string CntNote4 { get; set; } // CNT_NOTE_4 (length: 500)
        public string CntNote5 { get; set; } // CNT_NOTE_5 (length: 500)
        public string CntNote6 { get; set; } // CNT_NOTE_6 (length: 500)
        public string ImpCntUsr { get; set; } // IMP_CNT_USR (length: 500)
        public string ImpCntNote { get; set; } // IMP_CNT_NOTE (length: 500)
        public string ImpCntUnitOfMeasure { get; set; } // IMP_CNT_UNIT_OF_MEASURE (length: 15)

        // Reverse navigation

        /// <summary>
        /// Child ImCntHistCells where [IM_CNT_HIST_CELL].([EVENT_NO], [ITEM_NO], [LOC_ID]) point to this entity (FK_IM_CNT_HIST_CELL_IM_CNT_HIST)
        /// </summary>
        public virtual IList<ImCntHistCell> ImCntHistCells { get; set; } = new List<ImCntHistCell>(); // IM_CNT_HIST_CELL.FK_IM_CNT_HIST_CELL_IM_CNT_HIST

        /// <summary>
        /// Child ImCntHistSers where [IM_CNT_HIST_SER].([EVENT_NO], [ITEM_NO], [LOC_ID]) point to this entity (FK_IM_CNT_HIST_SER_IM_CNT_HIST)
        /// </summary>
        public virtual IList<ImCntHistSer> ImCntHistSers { get; set; } = new List<ImCntHistSer>(); // IM_CNT_HIST_SER.FK_IM_CNT_HIST_SER_IM_CNT_HIST

        // Foreign keys

        /// <summary>
        /// Parent ImLocHist pointed by [IM_CNT_HIST].([LocId]) (FK_IM_CNT_HIST_IM_LOC_HIST)
        /// </summary>
        public virtual ImLocHist ImLocHist { get; set; } // FK_IM_CNT_HIST_IM_LOC_HIST
    }

}
// </auto-generated>
