// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // IM_GRID_DIM_2
    public class ImGridDim2
    {
        public string ItemNo { get; set; } // ITEM_NO (Primary key) (length: 20)
        public string Dim2Upr { get; set; } // DIM_2_UPR (Primary key) (length: 15)
        public string Dim2 { get; set; } // DIM_2 (length: 15)
        public int? Dim2SeqNo { get; set; } // DIM_2_SEQ_NO
        public DateTime? LstMaintDt { get; set; } // LST_MAINT_DT
        public string LstMaintUsrId { get; set; } // LST_MAINT_USR_ID (length: 10)
        public DateTime? LstLckDt { get; set; } // LST_LCK_DT
        public byte[] RowTs { get; set; } // ROW_TS

        // Reverse navigation

        /// <summary>
        /// Child ImInvCells where [IM_INV_CELL].([DIM_2_UPR], [ITEM_NO]) point to this entity (FK_IM_INV_CELL_IM_GRID_DIM_2)
        /// </summary>
        public virtual IList<ImInvCell> ImInvCells { get; set; } = new List<ImInvCell>(); // IM_INV_CELL.FK_IM_INV_CELL_IM_GRID_DIM_2

        // Foreign keys

        /// <summary>
        /// Parent ImItem pointed by [IM_GRID_DIM_2].([ItemNo]) (FK_IM_GRID_DIM_2_IM_ITEM)
        /// </summary>
        public virtual ImItem ImItem { get; set; } // FK_IM_GRID_DIM_2_IM_ITEM
    }

}
// </auto-generated>
