// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // IM_INV
    public class ImInv
    {
        public string ItemNo { get; set; } // ITEM_NO (Primary key) (length: 20)
        public string LocId { get; set; } // LOC_ID (Primary key) (length: 10)
        public string Bin1 { get; set; } // BIN_1 (length: 10)
        public string Bin2 { get; set; } // BIN_2 (length: 10)
        public string Bin3 { get; set; } // BIN_3 (length: 10)
        public string Bin4 { get; set; } // BIN_4 (length: 10)
        public decimal MinQty { get; set; } = 0m; // MIN_QTY
        public decimal MaxQty { get; set; } = 0m; // MAX_QTY
        public decimal QtyCommit { get; set; } = 0m; // QTY_COMMIT
        public decimal QtyOnHnd { get; set; } = 0m; // QTY_ON_HND
        public decimal QtyOnPo { get; set; } = 0m; // QTY_ON_PO
        public decimal QtyOnBo { get; set; } = 0m; // QTY_ON_BO
        public decimal QtyOnXferOut { get; set; } = 0m; // QTY_ON_XFER_OUT
        public decimal QtyOnXferIn { get; set; } = 0m; // QTY_ON_XFER_IN
        public decimal LstAvgCost { get; set; } = 0m; // LST_AVG_COST
        public decimal LstCost { get; set; } = 0m; // LST_COST
        public decimal StdCost { get; set; } = 0m; // STD_COST
        public decimal CostOfSlsPct { get; set; } = 0m; // COST_OF_SLS_PCT
        public DateTime? FstRecvDat { get; set; } // FST_RECV_DAT
        public DateTime? LstRecvDat { get; set; } // LST_RECV_DAT
        public DateTime? FstSalDat { get; set; } // FST_SAL_DAT
        public DateTime? LstSalDat { get; set; } // LST_SAL_DAT
        public DateTime? LstCntDat { get; set; } // LST_CNT_DAT
        public DateTime? LstOrdDat { get; set; } // LST_ORD_DAT
        public DateTime? NxtExpectdDat { get; set; } // NXT_EXPECTD_DAT
        public string NxtExpectdPo { get; set; } // NXT_EXPECTD_PO (length: 20)
        public decimal GlVal { get; set; } = 0m; // GL_VAL
        public DateTime? LstMaintDt { get; set; } // LST_MAINT_DT
        public string LstMaintUsrId { get; set; } // LST_MAINT_USR_ID (length: 10)
        public DateTime? LstLckDt { get; set; } // LST_LCK_DT
        public byte[] RowTs { get; set; } // ROW_TS
        public decimal QtyOnOrd { get; set; } = 0m; // QTY_ON_ORD
        public decimal QtyOnLwy { get; set; } = 0m; // QTY_ON_LWY
        public decimal QtyOnSo { get; set; } = 0m; // QTY_ON_SO
        public DateTime? RsUtcDt { get; set; } = DateTime.UtcNow; // RS_UTC_DT
        public decimal? AvgCost { get; private set; } // AVG_COST
        public decimal? NetQty { get; private set; } // NET_QTY
        public decimal? QtyAvail { get; private set; } // QTY_AVAIL
        public string StkStatPerQtyOnHnd { get; private set; } // STK_STAT_PER_QTY_ON_HND (length: 1)
        public string StkStatPerQtyAvail { get; private set; } // STK_STAT_PER_QTY_AVAIL (length: 1)
        public string StkStatPerNetQty { get; private set; } // STK_STAT_PER_NET_QTY (length: 1)
        public decimal? ReordPnt { get; set; } // REORD_PNT
        public decimal? Eoq { get; set; } // EOQ
        public decimal? SftyStk { get; set; } // SFTY_STK
        public decimal? SrvcLevl { get; set; } // SRVC_LEVL
        public decimal? AnnlHldCost { get; set; } // ANNL_HLD_COST
        public decimal? AnnlHldCostPerc { get; set; } // ANNL_HLD_COST_PERC
        public decimal? OrdCostPerOrder { get; set; } // ORD_COST_PER_ORDER
        public DateTime? EoqCalcOn { get; set; } // EOQ_CALC_ON
        public byte RsStat { get; set; } = 1; // RS_STAT
        public decimal DropshipQtyOnCustOrd { get; set; } = 0m; // DROPSHIP_QTY_ON_CUST_ORD
        public decimal DropshipQtyOnPo { get; set; } = 0m; // DROPSHIP_QTY_ON_PO

        // Reverse navigation

        /// <summary>
        /// Child ImInvCells where [IM_INV_CELL].([ITEM_NO], [LOC_ID]) point to this entity (FK_IM_INV_CELL_IM_INV)
        /// </summary>
        public virtual IList<ImInvCell> ImInvCells { get; set; } = new List<ImInvCell>(); // IM_INV_CELL.FK_IM_INV_CELL_IM_INV

        // Foreign keys

        /// <summary>
        /// Parent ImItem pointed by [IM_INV].([ItemNo]) (FK_IM_INV_IM_ITEM)
        /// </summary>
        public virtual ImItem ImItem { get; set; } // FK_IM_INV_IM_ITEM

        /// <summary>
        /// Parent ImLoc pointed by [IM_INV].([LocId]) (FK_IM_INV_IM_LOC)
        /// </summary>
        public virtual ImLoc ImLoc { get; set; } // FK_IM_INV_IM_LOC
    }

}
// </auto-generated>
