// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // IM_MINMAX_ADV_WRK_CELL
    public class ImMinmaxAdvWrkCell
    {
        public string SessId { get; set; } // SESS_ID (Primary key) (length: 40)
        public string ItemNo { get; set; } // ITEM_NO (Primary key) (length: 20)
        public string LocId { get; set; } // LOC_ID (Primary key) (length: 10)
        public string Dim1Upr { get; set; } // DIM_1_UPR (Primary key) (length: 15)
        public string Dim2Upr { get; set; } // DIM_2_UPR (Primary key) (length: 15)
        public string Dim3Upr { get; set; } // DIM_3_UPR (Primary key) (length: 15)
        public decimal MinQty { get; set; } = 0m; // MIN_QTY
        public decimal MaxQty { get; set; } = 0m; // MAX_QTY
        public decimal? QtySold { get; set; } // QTY_SOLD
        public decimal? QtySoldPerDay { get; set; } // QTY_SOLD_PER_DAY
        public decimal? QtyOnHnd { get; set; } // QTY_ON_HND
        public int? DaysOnHnd { get; set; } // DAYS_ON_HND
        public decimal? SuggMinQty { get; set; } // SUGG_MIN_QTY
        public decimal? SuggMaxQty { get; set; } // SUGG_MAX_QTY
        public int? LeadDays { get; set; } // LEAD_DAYS

        // Foreign keys

        /// <summary>
        /// Parent ImMinmaxAdvWrk pointed by [IM_MINMAX_ADV_WRK_CELL].([SessId], [ItemNo], [LocId]) (FK_IM_MINMAX_ADV_WRK_CELL_IM_MINMAX_ADV_WRK)
        /// </summary>
        public virtual ImMinmaxAdvWrk ImMinmaxAdvWrk { get; set; } // FK_IM_MINMAX_ADV_WRK_CELL_IM_MINMAX_ADV_WRK
    }

}
// </auto-generated>
