// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // IM_PLAN_PROMO_RUL
    public class ImPlanPromoRul
    {
        public string GrpCod { get; set; } // GRP_COD (Primary key) (length: 10)
        public int SeqNo { get; set; } // SEQ_NO (Primary key)
        public string ItemNo { get; set; } // ITEM_NO (length: 20)
        public decimal? PromoPrc { get; set; } // PROMO_PRC
        public DateTime? LstMaintDt { get; set; } // LST_MAINT_DT
        public string LstMaintUsrId { get; set; } // LST_MAINT_USR_ID (length: 10)
        public DateTime? LstLckDt { get; set; } // LST_LCK_DT
        public byte[] RowTs { get; set; } // ROW_TS

        // Foreign keys

        /// <summary>
        /// Parent ImPlanPromoGrp pointed by [IM_PLAN_PROMO_RUL].([GrpCod]) (FK_IM_PLAN_PROMO_RUL_IM_PLAN_PROMO_GRP)
        /// </summary>
        public virtual ImPlanPromoGrp ImPlanPromoGrp { get; set; } // FK_IM_PLAN_PROMO_RUL_IM_PLAN_PROMO_GRP
    }

}
// </auto-generated>
