// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // IM_PRC_CHANGE_EVENT_HDR
    public class ImPrcChangeEventHdr
    {
        public long PrcEventId { get; set; } // PRC_EVENT_ID (Primary key)
        public string PrcEventCod { get; set; } // PRC_EVENT_COD (length: 10)
        public string PrcEventDescr { get; set; } // PRC_EVENT_DESCR (length: 80)
        public string EventCreatedByUsr { get; set; } // EVENT_CREATED_BY_USR (length: 10)
        public string LocId { get; set; } // LOC_ID (length: 10)
        public string LocGrp { get; set; } // LOC_GRP (length: 10)
        public string PostingErrRef { get; set; } // POSTING_ERR_REF (length: 255)
        public DateTime? LstMaintDt { get; set; } // LST_MAINT_DT
        public string LstMaintUsrId { get; set; } // LST_MAINT_USR_ID (length: 10)

        // Reverse navigation

        /// <summary>
        /// Child ImPrcChangeEventLins where [IM_PRC_CHANGE_EVENT_LIN].[PRC_EVENT_ID] point to this entity (FK_IM_PRC_CHANGE_EVENT_LIN_IM_PRC_CHANGE_EVENT_HDR)
        /// </summary>
        public virtual IList<ImPrcChangeEventLin> ImPrcChangeEventLins { get; set; } = new List<ImPrcChangeEventLin>(); // IM_PRC_CHANGE_EVENT_LIN.FK_IM_PRC_CHANGE_EVENT_LIN_IM_PRC_CHANGE_EVENT_HDR
    }

}
// </auto-generated>
