// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // IM_SER_PROMPT
    public class ImSerPrompt
    {
        public string PromptCod { get; set; } // PROMPT_COD (Primary key) (length: 10)
        public string Descr { get; set; } // DESCR (length: 30)
        public string DescrUpr { get; set; } // DESCR_UPR (length: 30)
        public string PromptTxt { get; set; } // PROMPT_TXT (length: 30)
        public string DataTyp { get; set; } = "A"; // DATA_TYP (length: 1)
        public int? NoOfDecs { get; set; } = 0; // NO_OF_DECS
        public string EntryReq { get; set; } = "N"; // ENTRY_REQ (length: 1)
        public string Constrnt { get; set; } // CONSTRNT (length: 250)
        public string ConstrntErrMsg { get; set; } // CONSTRNT_ERR_MSG (length: 250)
        public string ValForPrompt1 { get; set; } = "N"; // VAL_FOR_PROMPT_1 (length: 1)
        public string ValForPrompt2 { get; set; } = "N"; // VAL_FOR_PROMPT_2 (length: 1)
        public string ValForPrompt3 { get; set; } = "N"; // VAL_FOR_PROMPT_3 (length: 1)
        public string UseForAdj { get; set; } = "N"; // USE_FOR_ADJ (length: 1)
        public string UseForRecv { get; set; } = "N"; // USE_FOR_RECV (length: 1)
        public string UseForSls { get; set; } = "N"; // USE_FOR_SLS (length: 1)
        public string UseForRet { get; set; } = "N"; // USE_FOR_RET (length: 1)
        public string UseForXfer { get; set; } = "N"; // USE_FOR_XFER (length: 1)
        public DateTime? LstMaintDt { get; set; } // LST_MAINT_DT
        public string LstMaintUsrId { get; set; } // LST_MAINT_USR_ID (length: 10)
        public DateTime? LstLckDt { get; set; } // LST_LCK_DT
        public byte[] RowTs { get; set; } // ROW_TS
        public string UseForRtv { get; set; } = "N"; // USE_FOR_RTV (length: 1)
        public DateTime? RsUtcDt { get; set; } = DateTime.UtcNow; // RS_UTC_DT
        public byte RsStat { get; set; } = 1; // RS_STAT
    }

}
// </auto-generated>
