// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // IM_SUBST_ITEM
    public class ImSubstItem
    {
        public string ItemNo { get; set; } // ITEM_NO (Primary key) (length: 20)
        public string SubstItemNo { get; set; } // SUBST_ITEM_NO (Primary key) (length: 20)
        public int? SeqNo { get; set; } // SEQ_NO
        public DateTime? LstMaintDt { get; set; } // LST_MAINT_DT
        public string LstMaintUsrId { get; set; } // LST_MAINT_USR_ID (length: 10)
        public DateTime? LstLckDt { get; set; } // LST_LCK_DT
        public byte[] RowTs { get; set; } // ROW_TS

        // Foreign keys

        /// <summary>
        /// Parent ImItem pointed by [IM_SUBST_ITEM].([ItemNo]) (FK_IM_SUBST_ITEM_IM_ITEM)
        /// </summary>
        public virtual ImItem ImItem { get; set; } // FK_IM_SUBST_ITEM_IM_ITEM
    }

}
// </auto-generated>
