// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // IM_TARE_COD
    public class ImTareCod
    {
        public string TareCod { get; set; } // TARE_COD (Primary key) (length: 10)
        public string Descr { get; set; } // DESCR (length: 30)
        public string DescrUpr { get; set; } // DESCR_UPR (length: 30)
        public string BtnLbl1 { get; set; } // BTN_LBL_1 (length: 10)
        public string BtnImageFil1 { get; set; } // BTN_IMAGE_FIL_1 (length: 100)
        public decimal? TareWeight1 { get; set; } // TARE_WEIGHT_1
        public string BtnLbl2 { get; set; } // BTN_LBL_2 (length: 10)
        public string BtnImageFil2 { get; set; } // BTN_IMAGE_FIL_2 (length: 100)
        public decimal? TareWeight2 { get; set; } // TARE_WEIGHT_2
        public string BtnLbl3 { get; set; } // BTN_LBL_3 (length: 10)
        public string BtnImageFil3 { get; set; } // BTN_IMAGE_FIL_3 (length: 100)
        public decimal? TareWeight3 { get; set; } // TARE_WEIGHT_3
        public string BtnLbl4 { get; set; } // BTN_LBL_4 (length: 10)
        public string BtnImageFil4 { get; set; } // BTN_IMAGE_FIL_4 (length: 100)
        public decimal? TareWeight4 { get; set; } // TARE_WEIGHT_4
        public string BtnLbl5 { get; set; } // BTN_LBL_5 (length: 10)
        public string BtnImageFil5 { get; set; } // BTN_IMAGE_FIL_5 (length: 100)
        public decimal? TareWeight5 { get; set; } // TARE_WEIGHT_5
        public string BtnLbl6 { get; set; } // BTN_LBL_6 (length: 10)
        public string BtnImageFil6 { get; set; } // BTN_IMAGE_FIL_6 (length: 100)
        public decimal? TareWeight6 { get; set; } // TARE_WEIGHT_6
        public DateTime? LstMaintDt { get; set; } // LST_MAINT_DT
        public string LstMaintUsrId { get; set; } // LST_MAINT_USR_ID (length: 10)
        public DateTime? LstLckDt { get; set; } // LST_LCK_DT
        public byte[] RowTs { get; set; } // ROW_TS
        public string AllowWeightEntry1 { get; set; } = "N"; // ALLOW_WEIGHT_ENTRY_1 (length: 1)
        public string AllowWeightEntry2 { get; set; } = "N"; // ALLOW_WEIGHT_ENTRY_2 (length: 1)
        public string AllowWeightEntry3 { get; set; } = "N"; // ALLOW_WEIGHT_ENTRY_3 (length: 1)
        public string AllowWeightEntry4 { get; set; } = "N"; // ALLOW_WEIGHT_ENTRY_4 (length: 1)
        public string AllowWeightEntry5 { get; set; } = "N"; // ALLOW_WEIGHT_ENTRY_5 (length: 1)
        public string AllowWeightEntry6 { get; set; } = "N"; // ALLOW_WEIGHT_ENTRY_6 (length: 1)
        public DateTime? RsUtcDt { get; set; } = DateTime.UtcNow; // RS_UTC_DT
        public byte RsStat { get; set; } = 1; // RS_STAT
    }

}
// </auto-generated>
