// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // IM_XFER_OUT_LIN
    public class ImXferOutLin
    {
        public string XferNo { get; set; } // XFER_NO (Primary key) (length: 15)
        public int XferLinSeqNo { get; set; } // XFER_LIN_SEQ_NO (Primary key)
        public string ItemNo { get; set; } // ITEM_NO (length: 20)
        public decimal XferQty { get; set; } // XFER_QTY
        public string XferUnit { get; set; } // XFER_UNIT (length: 15)
        public string XferQtyUnit { get; set; } = "0"; // XFER_QTY_UNIT (length: 1)
        public decimal XferQtyNumer { get; set; } = 1m; // XFER_QTY_NUMER
        public decimal XferQtyDenom { get; set; } = 1m; // XFER_QTY_DENOM
        public string Commnt1 { get; set; } // COMMNT_1 (length: 50)
        public string Commnt2 { get; set; } // COMMNT_2 (length: 50)
        public string Commnt3 { get; set; } // COMMNT_3 (length: 50)
        public string CellDescr { get; set; } // CELL_DESCR (length: 50)
        public string IsSingleCell { get; set; } = "N"; // IS_SINGLE_CELL (length: 1)
        public string Dim1Upr { get; set; } // DIM_1_UPR (length: 15)
        public string Dim2Upr { get; set; } // DIM_2_UPR (length: 15)
        public string Dim3Upr { get; set; } // DIM_3_UPR (length: 15)
        public int? NoOfSersEntd { get; set; } // NO_OF_SERS_ENTD
        public string SerNo { get; set; } // SER_NO (length: 30)
        public DateTime? LstMaintDt { get; set; } // LST_MAINT_DT
        public string LstMaintUsrId { get; set; } // LST_MAINT_USR_ID (length: 10)
        public DateTime? LstLckDt { get; set; } // LST_LCK_DT
        public byte[] RowTs { get; set; } // ROW_TS
        public decimal? EstUnitCost { get; set; } // EST_UNIT_COST
        public decimal EstExtCost { get; set; } // EST_EXT_COST
        public DateTime? LstXferAdvDt { get; set; } // LST_XFER_ADV_DT

        // Reverse navigation

        /// <summary>
        /// Child ImXferOutCells where [IM_XFER_OUT_CELL].([XFER_LIN_SEQ_NO], [XFER_NO]) point to this entity (FK_IM_XFER_OUT_CELL_IM_XFER_OUT_LIN)
        /// </summary>
        public virtual IList<ImXferOutCell> ImXferOutCells { get; set; } = new List<ImXferOutCell>(); // IM_XFER_OUT_CELL.FK_IM_XFER_OUT_CELL_IM_XFER_OUT_LIN

        /// <summary>
        /// Child ImXferOutSers where [IM_XFER_OUT_SER].([XFER_LIN_SEQ_NO], [XFER_NO]) point to this entity (FK_IM_XFER_OUT_SER_IM_XFER_OUT_LIN)
        /// </summary>
        public virtual IList<ImXferOutSer> ImXferOutSers { get; set; } = new List<ImXferOutSer>(); // IM_XFER_OUT_SER.FK_IM_XFER_OUT_SER_IM_XFER_OUT_LIN

        // Foreign keys

        /// <summary>
        /// Parent ImXferOutHdr pointed by [IM_XFER_OUT_LIN].([XferNo]) (FK_IM_XFER_OUT_LIN_IM_XFER_OUT_HDR)
        /// </summary>
        public virtual ImXferOutHdr ImXferOutHdr { get; set; } // FK_IM_XFER_OUT_LIN_IM_XFER_OUT_HDR
    }

}
// </auto-generated>
