// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // IM_XFER_HDR
    public class ImXferHdr
    {
        public string XferNo { get; set; } // XFER_NO (Primary key) (length: 15)
        public string BatId { get; set; } // BAT_ID (length: 10)
        public string FromLocId { get; set; } // FROM_LOC_ID (length: 10)
        public string ToLocId { get; set; } // TO_LOC_ID (length: 10)
        public DateTime ShipDat { get; set; } = DateTime.Now; // SHIP_DAT
        public string ShipBy { get; set; } // SHIP_BY (length: 10)
        public decimal XferOutSubTot { get; set; } = 0m; // XFER_OUT_SUB_TOT
        public decimal XferOutMiscAmt { get; set; } = 0m; // XFER_OUT_MISC_AMT
        public string Commnt1 { get; set; } // COMMNT_1 (length: 50)
        public string Commnt2 { get; set; } // COMMNT_2 (length: 50)
        public string Commnt3 { get; set; } // COMMNT_3 (length: 50)
        public string Ref { get; set; } // REF (length: 50)
        public string EventNo { get; set; } // EVENT_NO (length: 15)
        public decimal XferInSubTot { get; set; } = 0m; // XFER_IN_SUB_TOT
        public decimal XferInMiscAmt { get; set; } = 0m; // XFER_IN_MISC_AMT
        public int? OpnLinCnt { get; set; } = 0; // OPN_LIN_CNT
        public string XferStat { get; set; } = "O"; // XFER_STAT (length: 1)
        public DateTime? LstMaintDt { get; set; } // LST_MAINT_DT
        public string LstMaintUsrId { get; set; } // LST_MAINT_USR_ID (length: 10)
        public DateTime? LstLckDt { get; set; } // LST_LCK_DT
        public byte[] RowTs { get; set; } // ROW_TS
        public decimal? XferInTot { get; private set; } // XFER_IN_TOT
        public decimal? XferOutTot { get; private set; } // XFER_OUT_TOT

        // Reverse navigation

        /// <summary>
        /// Child ImXferLins where [IM_XFER_LIN].[XFER_NO] point to this entity (FK_IM_XFER_LIN_IM_XFER_HDR)
        /// </summary>
        public virtual IList<ImXferLin> ImXferLins { get; set; } = new List<ImXferLin>(); // IM_XFER_LIN.FK_IM_XFER_LIN_IM_XFER_HDR

        /// <summary>
        /// Child ImXferNotes where [IM_XFER_NOTE].[XFER_NO] point to this entity (FK_IM_XFER_NOTE_IM_XFER_HDR)
        /// </summary>
        public virtual IList<ImXferNote> ImXferNotes { get; set; } = new List<ImXferNote>(); // IM_XFER_NOTE.FK_IM_XFER_NOTE_IM_XFER_HDR

        // Foreign keys

        /// <summary>
        /// Parent ImLoc pointed by [IM_XFER_HDR].([ToLocId]) (FK_IM_XFER_HDR_IM_LOC)
        /// </summary>
        public virtual ImLoc ImLoc { get; set; } // FK_IM_XFER_HDR_IM_LOC
    }

}
// </auto-generated>
