// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // MS_SITE_SER
    public class MsSiteSer
    {
        public int SiteId { get; set; } // SITE_ID (Primary key)
        public string SerNo { get; set; } // SER_NO (length: 10)
    }

}
// </auto-generated>
