// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // PO_ADJ_HIST_SER_LOC
    public class PoAdjHistSerLoc
    {
        public string EventNo { get; set; } // EVENT_NO (Primary key) (length: 15)
        public string RecvrNo { get; set; } // RECVR_NO (Primary key) (length: 15)
        public int SeqNo { get; set; } // SEQ_NO (Primary key)
        public string LocId { get; set; } // LOC_ID (Primary key) (length: 10)
        public string SerNo { get; set; } // SER_NO (Primary key) (length: 30)
        public decimal? CostBefore { get; set; } // COST_BEFORE
        public decimal? CostAfter { get; set; } // COST_AFTER
        public DateTime? LstMaintDt { get; set; } // LST_MAINT_DT
        public string LstMaintUsrId { get; set; } // LST_MAINT_USR_ID (length: 10)
        public DateTime? LstLckDt { get; set; } // LST_LCK_DT
        public byte[] RowTs { get; set; } // ROW_TS

        // Foreign keys

        /// <summary>
        /// Parent PoAdjHistLinLoc pointed by [PO_ADJ_HIST_SER_LOC].([EventNo], [RecvrNo], [SeqNo], [LocId]) (FK_PO_ADJ_HIST_SER_LOC_PO_ADJ_HIST_LIN_LOC)
        /// </summary>
        public virtual PoAdjHistLinLoc PoAdjHistLinLoc { get; set; } // FK_PO_ADJ_HIST_SER_LOC_PO_ADJ_HIST_LIN_LOC

        /// <summary>
        /// Parent PoAdjHistSer pointed by [PO_ADJ_HIST_SER_LOC].([EventNo], [RecvrNo], [SeqNo], [SerNo]) (FK_PO_ADJ_HIST_SER_LOC_PO_ADJ_HIST_SER)
        /// </summary>
        public virtual PoAdjHistSer PoAdjHistSer { get; set; } // FK_PO_ADJ_HIST_SER_LOC_PO_ADJ_HIST_SER
    }

}
// </auto-generated>
