// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // PO_ADJ_HIST_LIN_LOC
    public class PoAdjHistLinLoc
    {
        public string EventNo { get; set; } // EVENT_NO (Primary key) (length: 15)
        public string RecvrNo { get; set; } // RECVR_NO (Primary key) (length: 15)
        public int SeqNo { get; set; } // SEQ_NO (Primary key)
        public string LocId { get; set; } // LOC_ID (Primary key) (length: 10)
        public decimal QtyRecvd { get; set; } // QTY_RECVD
        public decimal QtyAdj { get; set; } // QTY_ADJ
        public DateTime? LstMaintDt { get; set; } // LST_MAINT_DT
        public string LstMaintUsrId { get; set; } // LST_MAINT_USR_ID (length: 10)
        public DateTime? LstLckDt { get; set; } // LST_LCK_DT
        public byte[] RowTs { get; set; } // ROW_TS
        public decimal BsInvAdjAmt { get; set; } // BS_INV_ADJ_AMT
        public decimal? CogsAdjAmt { get; set; } // COGS_ADJ_AMT
        public decimal? MiscItemAdjAmt { get; set; } // MISC_ITEM_ADJ_AMT
        public decimal? AvgCostBefore { get; set; } // AVG_COST_BEFORE
        public decimal? AvgCostAfter { get; set; } // AVG_COST_AFTER
        public decimal? StdCost { get; set; } = 0m; // STD_COST
        public decimal? TotCostCorr { get; set; } // TOT_COST_CORR
        public string LinAdjMeth { get; set; } = "F"; // LIN_ADJ_METH (length: 1)

        // Reverse navigation

        /// <summary>
        /// Child PoAdjHistCellLocs where [PO_ADJ_HIST_CELL_LOC].([EVENT_NO], [LOC_ID], [RECVR_NO], [SEQ_NO]) point to this entity (FK_PO_ADJ_HIST_CELL_LOC_PO_ADJ_HIST_LIN_LOC)
        /// </summary>
        public virtual IList<PoAdjHistCellLoc> PoAdjHistCellLocs { get; set; } = new List<PoAdjHistCellLoc>(); // PO_ADJ_HIST_CELL_LOC.FK_PO_ADJ_HIST_CELL_LOC_PO_ADJ_HIST_LIN_LOC

        /// <summary>
        /// Child PoAdjHistSerLocs where [PO_ADJ_HIST_SER_LOC].([EVENT_NO], [LOC_ID], [RECVR_NO], [SEQ_NO]) point to this entity (FK_PO_ADJ_HIST_SER_LOC_PO_ADJ_HIST_LIN_LOC)
        /// </summary>
        public virtual IList<PoAdjHistSerLoc> PoAdjHistSerLocs { get; set; } = new List<PoAdjHistSerLoc>(); // PO_ADJ_HIST_SER_LOC.FK_PO_ADJ_HIST_SER_LOC_PO_ADJ_HIST_LIN_LOC

        // Foreign keys

        /// <summary>
        /// Parent PoAdjHistLin pointed by [PO_ADJ_HIST_LIN_LOC].([EventNo], [RecvrNo], [SeqNo]) (FK_PO_ADJ_HIST_LIN_LOC_PO_ADJ_HIST_LIN)
        /// </summary>
        public virtual PoAdjHistLin PoAdjHistLin { get; set; } // FK_PO_ADJ_HIST_LIN_LOC_PO_ADJ_HIST_LIN
    }

}
// </auto-generated>
