// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // PO_ORD_LIN_LOC
    public class PoOrdLinLoc
    {
        public string PoNo { get; set; } // PO_NO (Primary key) (length: 20)
        public int SeqNo { get; set; } // SEQ_NO (Primary key)
        public string LocId { get; set; } // LOC_ID (Primary key) (length: 10)
        public decimal OrdQty { get; set; } // ORD_QTY
        public decimal QtyRecvd { get; set; } = 0m; // QTY_RECVD
        public decimal QtyExpectd { get; set; } // QTY_EXPECTD
        public DateTime? LstMaintDt { get; set; } // LST_MAINT_DT
        public string LstMaintUsrId { get; set; } // LST_MAINT_USR_ID (length: 10)
        public DateTime? LstLckDt { get; set; } // LST_LCK_DT
        public byte[] RowTs { get; set; } // ROW_TS

        // Reverse navigation

        /// <summary>
        /// Child PoOrdCellLocs where [PO_ORD_CELL_LOC].([LOC_ID], [PO_NO], [SEQ_NO]) point to this entity (FK_PO_ORD_CELL_LOC_PO_ORD_LIN_LOC)
        /// </summary>
        public virtual IList<PoOrdCellLoc> PoOrdCellLocs { get; set; } = new List<PoOrdCellLoc>(); // PO_ORD_CELL_LOC.FK_PO_ORD_CELL_LOC_PO_ORD_LIN_LOC

        // Foreign keys

        /// <summary>
        /// Parent PoOrdLin pointed by [PO_ORD_LIN_LOC].([PoNo], [SeqNo]) (FK_PO_ORD_LIN_LOC_PO_ORD_LIN)
        /// </summary>
        public virtual PoOrdLin PoOrdLin { get; set; } // FK_PO_ORD_LIN_LOC_PO_ORD_LIN
    }

}
// </auto-generated>
