// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // PO_PREQ_LIN_LOC
    public class PoPreqLinLoc
    {
        public string PreqNo { get; set; } // PREQ_NO (Primary key) (length: 15)
        public int SeqNo { get; set; } // SEQ_NO (Primary key)
        public string LocId { get; set; } // LOC_ID (Primary key) (length: 10)
        public decimal OrdQty { get; set; } // ORD_QTY
        public DateTime? LstMaintDt { get; set; } // LST_MAINT_DT
        public string LstMaintUsrId { get; set; } // LST_MAINT_USR_ID (length: 10)
        public DateTime? LstLckDt { get; set; } // LST_LCK_DT
        public byte[] RowTs { get; set; } // ROW_TS

        // Reverse navigation

        /// <summary>
        /// Child PoPreqCellLocs where [PO_PREQ_CELL_LOC].([LOC_ID], [PREQ_NO], [SEQ_NO]) point to this entity (FK_PO_PREQ_CELL_LOC_PO_PREQ_LIN_LOC)
        /// </summary>
        public virtual IList<PoPreqCellLoc> PoPreqCellLocs { get; set; } = new List<PoPreqCellLoc>(); // PO_PREQ_CELL_LOC.FK_PO_PREQ_CELL_LOC_PO_PREQ_LIN_LOC

        // Foreign keys

        /// <summary>
        /// Parent PoPreqLin pointed by [PO_PREQ_LIN_LOC].([PreqNo], [SeqNo]) (FK_PO_PREQ_LIN_LOC_PO_PREQ_LIN)
        /// </summary>
        public virtual PoPreqLin PoPreqLin { get; set; } // FK_PO_PREQ_LIN_LOC_PO_PREQ_LIN
    }

}
// </auto-generated>
