// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // PO_QRECV_TRX
    public class PoQrecvTrx
    {
        public string BatId { get; set; } // BAT_ID (Primary key) (length: 10)
        public string ItemNo { get; set; } // ITEM_NO (Primary key) (length: 20)
        public string LocId { get; set; } // LOC_ID (Primary key) (length: 10)
        public DateTime TrxDat { get; set; } = DateTime.Now; // TRX_DAT (Primary key)
        public int SeqNo { get; set; } = 1; // SEQ_NO (Primary key)
        public decimal Qty { get; set; } // QTY
        public string QtyUnit { get; set; } = "0"; // QTY_UNIT (length: 1)
        public decimal QtyNumer { get; set; } = 1m; // QTY_NUMER
        public decimal QtyDenom { get; set; } = 1m; // QTY_DENOM
        public string Unit { get; set; } // UNIT (length: 15)
        public decimal CostEntd { get; set; } // COST_ENTD
        public string DocNo { get; set; } // DOC_NO (length: 15)
        public string Ref { get; set; } // REF (length: 50)
        public string VendNo { get; set; } // VEND_NO (length: 15)
        public string ErrRef { get; set; } // ERR_REF (length: 255)
        public string CellDescr { get; set; } // CELL_DESCR (length: 50)
        public string IsSingleCell { get; set; } = "N"; // IS_SINGLE_CELL (length: 1)
        public string Dim1Upr { get; set; } // DIM_1_UPR (length: 15)
        public string Dim2Upr { get; set; } // DIM_2_UPR (length: 15)
        public string Dim3Upr { get; set; } // DIM_3_UPR (length: 15)
        public string SerNo { get; set; } // SER_NO (length: 30)
        public int? NoOfSersEntd { get; set; } // NO_OF_SERS_ENTD
        public DateTime? LstMaintDt { get; set; } // LST_MAINT_DT
        public string LstMaintUsrId { get; set; } // LST_MAINT_USR_ID (length: 10)
        public DateTime? LstLckDt { get; set; } // LST_LCK_DT
        public byte[] RowTs { get; set; } // ROW_TS
        public string UserIntakeDocNo { get; set; } // USER_INTAKE_DOC_NO (length: 15)
        public string UserIntakeType { get; set; } // USER_INTAKE_TYPE (length: 10)

        // Reverse navigation

        /// <summary>
        /// Child PoQrecvTrxCells where [PO_QRECV_TRX_CELL].([BAT_ID], [ITEM_NO], [LOC_ID], [SEQ_NO], [TRX_DAT]) point to this entity (FK_PO_QRECV_TRX_CELL_PO_QRECV_TRX)
        /// </summary>
        public virtual IList<PoQrecvTrxCell> PoQrecvTrxCells { get; set; } = new List<PoQrecvTrxCell>(); // PO_QRECV_TRX_CELL.FK_PO_QRECV_TRX_CELL_PO_QRECV_TRX

        /// <summary>
        /// Child PoQrecvTrxSers where [PO_QRECV_TRX_SER].([BAT_ID], [ITEM_NO], [LOC_ID], [SEQ_NO], [TRX_DAT]) point to this entity (FK_PO_QRECV_TRX_SER_PO_QRECV_TRX)
        /// </summary>
        public virtual IList<PoQrecvTrxSer> PoQrecvTrxSers { get; set; } = new List<PoQrecvTrxSer>(); // PO_QRECV_TRX_SER.FK_PO_QRECV_TRX_SER_PO_QRECV_TRX

        // Foreign keys

        /// <summary>
        /// Parent ImLoc pointed by [PO_QRECV_TRX].([LocId]) (FK_PO_QRECV_TRX_IM_LOC)
        /// </summary>
        public virtual ImLoc ImLoc { get; set; } // FK_PO_QRECV_TRX_IM_LOC
    }

}
// </auto-generated>
