// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // PO_RECVR_HIST_VCHR_ACTIV
    public class PoRecvrHistVchrActiv
    {
        public string RecvrNo { get; set; } // RECVR_NO (Primary key) (length: 15)
        public int SeqNo { get; set; } // SEQ_NO (Primary key)
        public string VchrNo { get; set; } // VCHR_NO (length: 20)
        public string VchrVendNo { get; set; } // VCHR_VEND_NO (length: 15)
        public DateTime? VchrDat { get; set; } // VCHR_DAT
        public DateTime? VchrTim { get; set; } // VCHR_TIM
        public string VchrBy { get; set; } // VCHR_BY (length: 10)
        public string InvcNo { get; set; } // INVC_NO (length: 20)
        public DateTime? InvcDat { get; set; } // INVC_DAT
        public DateTime? DistDat { get; set; } // DIST_DAT
        public string Ref { get; set; } // REF (length: 50)
        public decimal? VchrMiscAmt1 { get; set; } // VCHR_MISC_AMT_1
        public decimal? VchrMiscAmt2 { get; set; } // VCHR_MISC_AMT_2
        public decimal? VchrMiscAmt3 { get; set; } // VCHR_MISC_AMT_3
        public decimal? VchrMiscAmt4 { get; set; } // VCHR_MISC_AMT_4
        public decimal? VchrMiscAmt5 { get; set; } // VCHR_MISC_AMT_5
        public decimal? VchrTotMisc { get; set; } // VCHR_TOT_MISC
        public decimal? VchrSubTot { get; set; } // VCHR_SUB_TOT
        public decimal? VchrTot { get; set; } // VCHR_TOT
        public string ManualVchr { get; set; } = "N"; // MANUAL_VCHR (length: 1)
        public DateTime? LstMaintDt { get; set; } // LST_MAINT_DT
        public string LstMaintUsrId { get; set; } // LST_MAINT_USR_ID (length: 10)
        public DateTime? LstLckDt { get; set; } // LST_LCK_DT
        public byte[] RowTs { get; set; } // ROW_TS
        public decimal ExchRateNumer { get; set; } = 1m; // EXCH_RATE_NUMER
        public decimal ExchRateDenom { get; set; } = 1m; // EXCH_RATE_DENOM
        public decimal VchrMisc1ExchRateNumer { get; set; } = 1m; // VCHR_MISC_1_EXCH_RATE_NUMER
        public decimal VchrMisc1ExchRateDenom { get; set; } = 1m; // VCHR_MISC_1_EXCH_RATE_DENOM
        public decimal VchrMisc2ExchRateNumer { get; set; } = 1m; // VCHR_MISC_2_EXCH_RATE_NUMER
        public decimal VchrMisc2ExchRateDenom { get; set; } = 1m; // VCHR_MISC_2_EXCH_RATE_DENOM
        public decimal VchrMisc3ExchRateNumer { get; set; } = 1m; // VCHR_MISC_3_EXCH_RATE_NUMER
        public decimal VchrMisc3ExchRateDenom { get; set; } = 1m; // VCHR_MISC_3_EXCH_RATE_DENOM
        public decimal VchrMisc4ExchRateNumer { get; set; } = 1m; // VCHR_MISC_4_EXCH_RATE_NUMER
        public decimal VchrMisc4ExchRateDenom { get; set; } = 1m; // VCHR_MISC_4_EXCH_RATE_DENOM
        public decimal VchrMisc5ExchRateNumer { get; set; } = 1m; // VCHR_MISC_5_EXCH_RATE_NUMER
        public decimal VchrMisc5ExchRateDenom { get; set; } = 1m; // VCHR_MISC_5_EXCH_RATE_DENOM
        public decimal? VchrSubTotHome { get; set; } // VCHR_SUB_TOT_HOME
        public decimal? VchrMiscAmt1Home { get; set; } // VCHR_MISC_AMT_1_HOME
        public decimal? VchrMiscAmt2Home { get; set; } // VCHR_MISC_AMT_2_HOME
        public decimal? VchrMiscAmt3Home { get; set; } // VCHR_MISC_AMT_3_HOME
        public decimal? VchrMiscAmt4Home { get; set; } // VCHR_MISC_AMT_4_HOME
        public decimal? VchrMiscAmt5Home { get; set; } // VCHR_MISC_AMT_5_HOME
        public decimal? VchrTotMiscHome { get; set; } // VCHR_TOT_MISC_HOME
        public decimal? VchrTotHome { get; set; } // VCHR_TOT_HOME
        public decimal? VchrTaxAmt { get; set; } // VCHR_TAX_AMT
        public decimal? VchrTaxAmtHome { get; set; } // VCHR_TAX_AMT_HOME
        public decimal? VchrSubTotGainLossHome { get; set; } // VCHR_SUB_TOT_GAIN_LOSS_HOME
        public decimal? VchrMisc1GainLossHome { get; set; } // VCHR_MISC_1_GAIN_LOSS_HOME
        public decimal? VchrMisc2GainLossHome { get; set; } // VCHR_MISC_2_GAIN_LOSS_HOME
        public decimal? VchrMisc3GainLossHome { get; set; } // VCHR_MISC_3_GAIN_LOSS_HOME
        public decimal? VchrMisc4GainLossHome { get; set; } // VCHR_MISC_4_GAIN_LOSS_HOME
        public decimal? VchrMisc5GainLossHome { get; set; } // VCHR_MISC_5_GAIN_LOSS_HOME
        public decimal? VchrTaxGainLossHome { get; set; } // VCHR_TAX_GAIN_LOSS_HOME
        public decimal? VchrTotGainLossHome { get; private set; } // VCHR_TOT_GAIN_LOSS_HOME
        public decimal? VchrTotWithGainLossHome { get; private set; } // VCHR_TOT_WITH_GAIN_LOSS_HOME

        // Foreign keys

        /// <summary>
        /// Parent PoRecvrHist pointed by [PO_RECVR_HIST_VCHR_ACTIV].([RecvrNo]) (FK_PO_RECVR_HIST_VCHR_ACTIV_PO_RECVR_HIST)
        /// </summary>
        public virtual PoRecvrHist PoRecvrHist { get; set; } // FK_PO_RECVR_HIST_VCHR_ACTIV_PO_RECVR_HIST
    }

}
// </auto-generated>
