// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // PO_RTV_LIN
    public class PoRtvLin
    {
        public string RtvNo { get; set; } // RTV_NO (Primary key) (length: 15)
        public int SeqNo { get; set; } // SEQ_NO (Primary key)
        public string ItemNo { get; set; } // ITEM_NO (length: 20)
        public string VendNo { get; set; } // VEND_NO (length: 15)
        public string VendItemNo { get; set; } // VEND_ITEM_NO (length: 30)
        public string Descr { get; set; } // DESCR (length: 50)
        public string DescrUpr { get; set; } // DESCR_UPR (length: 50)
        public string ItemDescr { get; set; } // ITEM_DESCR (length: 50)
        public string ItemDescrUpr { get; set; } // ITEM_DESCR_UPR (length: 50)
        public decimal QtyRetd { get; set; } // QTY_RETD
        public string QtyUnit { get; set; } // QTY_UNIT (length: 15)
        public string QtyRetdUnit { get; set; } = "0"; // QTY_RETD_UNIT (length: 1)
        public decimal QtyRetdNumer { get; set; } = 1m; // QTY_RETD_NUMER
        public decimal QtyRetdDenom { get; set; } = 1m; // QTY_RETD_DENOM
        public string CellDescr { get; set; } // CELL_DESCR (length: 50)
        public string IsSingleCell { get; set; } = "N"; // IS_SINGLE_CELL (length: 1)
        public string Dim1Upr { get; set; } // DIM_1_UPR (length: 15)
        public string Dim2Upr { get; set; } // DIM_2_UPR (length: 15)
        public string Dim3Upr { get; set; } // DIM_3_UPR (length: 15)
        public string SerNo { get; set; } // SER_NO (length: 30)
        public int? NoOfSersEntd { get; set; } // NO_OF_SERS_ENTD
        public string Commnt1 { get; set; } // COMMNT_1 (length: 50)
        public string Commnt2 { get; set; } // COMMNT_2 (length: 50)
        public string Commnt3 { get; set; } // COMMNT_3 (length: 50)
        public DateTime? LstMaintDt { get; set; } // LST_MAINT_DT
        public string LstMaintUsrId { get; set; } // LST_MAINT_USR_ID (length: 10)
        public DateTime? LstLckDt { get; set; } // LST_LCK_DT
        public byte[] RowTs { get; set; } // ROW_TS
        public decimal CreditAmt { get; set; } // CREDIT_AMT
        public decimal ExtCreditAmt { get; set; } // EXT_CREDIT_AMT
        public decimal? UnitWeight { get; set; } // UNIT_WEIGHT
        public decimal? ExtWeight { get; set; } // EXT_WEIGHT
        public decimal? UnitCube { get; set; } // UNIT_CUBE
        public decimal? ExtCube { get; set; } // EXT_CUBE
        public decimal? QtyRetdInStkUnits { get; set; } // QTY_RETD_IN_STK_UNITS
        public string IsTxblNorm { get; set; } = "Y"; // IS_TXBL_NORM (length: 1)
        public string IsTxbl { get; set; } = "Y"; // IS_TXBL (length: 1)
        public string IsTxblChngd { get; private set; } // IS_TXBL_CHNGD (length: 1)
        public string TaxCategNorm { get; set; } // TAX_CATEG_NORM (length: 10)
        public string TaxCateg { get; set; } // TAX_CATEG (length: 10)
        public string TaxCategChngd { get; private set; } // TAX_CATEG_CHNGD (length: 1)
        public decimal RtvNormTaxAmtAllocHome { get; set; } = 0m; // RTV_NORM_TAX_AMT_ALLOC_HOME
        public decimal RtvTaxAmtAllocHome { get; set; } = 0m; // RTV_TAX_AMT_ALLOC_HOME
        public Guid LinGuid { get; set; } // LIN_GUID

        // Reverse navigation

        /// <summary>
        /// Child PoRtvCells where [PO_RTV_CELL].([RTV_NO], [SEQ_NO]) point to this entity (FK_PO_RTV_CELL_PO_RTV_LIN)
        /// </summary>
        public virtual IList<PoRtvCell> PoRtvCells { get; set; } = new List<PoRtvCell>(); // PO_RTV_CELL.FK_PO_RTV_CELL_PO_RTV_LIN

        /// <summary>
        /// Child PoRtvSers where [PO_RTV_SER].([RTV_NO], [SEQ_NO]) point to this entity (FK_PO_RTV_SER_PO_RTV_LIN)
        /// </summary>
        public virtual IList<PoRtvSer> PoRtvSers { get; set; } = new List<PoRtvSer>(); // PO_RTV_SER.FK_PO_RTV_SER_PO_RTV_LIN

        // Foreign keys

        /// <summary>
        /// Parent PoRtvHdr pointed by [PO_RTV_LIN].([RtvNo]) (FK_PO_RTV_LIN_PO_RTV_HDR)
        /// </summary>
        public virtual PoRtvHdr PoRtvHdr { get; set; } // FK_PO_RTV_LIN_PO_RTV_HDR
    }

}
// </auto-generated>
