// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // PS_DOC_PMT_APPLY
    public class PsDocPmtApply
    {
        public long DocId { get; set; } // DOC_ID (Primary key)
        public int PmtSeqNo { get; set; } // PMT_SEQ_NO (Primary key)
        public string ApplTyp { get; set; } // APPL_TYP (Primary key) (length: 1)
        public decimal Amt { get; set; } = 0m; // AMT
        public decimal HomeCurncyAmt { get; set; } = 0m; // HOME_CURNCY_AMT
        public decimal ExchLoss { get; set; } = 0m; // EXCH_LOSS

        // Foreign keys

        /// <summary>
        /// Parent PsDocPmt pointed by [PS_DOC_PMT_APPLY].([DocId], [PmtSeqNo]) (FK_PS_DOC_PMT_APPLY_PS_DOC_PMT)
        /// </summary>
        public virtual PsDocPmt PsDocPmt { get; set; } // FK_PS_DOC_PMT_APPLY_PS_DOC_PMT
    }

}
// </auto-generated>
