// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // PS_DOC_LIN_PRICE
    public class PsDocLinPrice
    {
        public long DocId { get; set; } // DOC_ID (Primary key)
        public int LinSeqNo { get; set; } // LIN_SEQ_NO (Primary key)
        public string PrcJustStr { get; set; } // PRC_JUST_STR (length: 20)
        public string PrcGrpCod { get; set; } // PRC_GRP_COD (length: 10)
        public string PrcGrpDescr { get; set; } // PRC_GRP_DESCR (length: 30)
        public string PrcRulDescr { get; set; } // PRC_RUL_DESCR (length: 30)
        public string PrcGrpTyp { get; set; } = "!"; // PRC_GRP_TYP (length: 1)
        public int? PrcRulSeqNo { get; set; } // PRC_RUL_SEQ_NO
        public string PrcBrkDescr { get; set; } // PRC_BRK_DESCR (length: 50)
        public short PrcSeqNo { get; set; } = 1; // PRC_SEQ_NO (Primary key)
        public decimal QtyPrcd { get; set; } // QTY_PRCD
        public decimal UnitPrc { get; set; } // UNIT_PRC
        public string Dim1Upr { get; set; } // DIM_1_UPR (length: 15)
        public string Dim2Upr { get; set; } // DIM_2_UPR (length: 15)
        public string Dim3Upr { get; set; } // DIM_3_UPR (length: 15)

        // Foreign keys

        /// <summary>
        /// Parent PsDocLin pointed by [PS_DOC_LIN_PRICE].([DocId], [LinSeqNo]) (FK_PS_DOC_LIN_PRICE_PS_DOC_LIN)
        /// </summary>
        public virtual PsDocLin PsDocLin { get; set; } // FK_PS_DOC_LIN_PRICE_PS_DOC_LIN
    }

}
// </auto-generated>
