// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // PS_FILL_BO_DEMAND_WRK
    public class PsFillBoDemandWrk
    {
        public Guid SessId { get; set; } // SESS_ID (Primary key)
        public string Dim1Upr { get; set; } // DIM_1_UPR (Primary key) (length: 15)
        public string Dim2Upr { get; set; } // DIM_2_UPR (Primary key) (length: 15)
        public string Dim3Upr { get; set; } // DIM_3_UPR (Primary key) (length: 15)
        public string ItemNo { get; set; } // ITEM_NO (length: 20)
        public string LocId { get; set; } // LOC_ID (length: 10)
        public DateTime OrdDt { get; set; } // ORD_DT
        public decimal QtySold { get; set; } // QTY_SOLD
        public long DocId { get; set; } // DOC_ID (Primary key)
        public int LinSeqNo { get; set; } // LIN_SEQ_NO (Primary key)
    }

}
// </auto-generated>
