// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // PS_FILL_BO_RSLT_HDR_WRK
    public class PsFillBoRsltHdrWrk
    {
        public Guid SessId { get; set; } // SESS_ID (Primary key)
        public string FillStat { get; set; } = "!"; // FILL_STAT (length: 1)
        public long DocId { get; set; } // DOC_ID (Primary key)
    }

}
// </auto-generated>
