// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // PS_LWY_HIST_TAX
    public class PsLwyHistTax
    {
        public DateTime BusDat { get; set; } // BUS_DAT (Primary key)
        public long DocId { get; set; } // DOC_ID (Primary key)
        public string AuthCod { get; set; } // AUTH_COD (Primary key) (length: 10)
        public string RulCod { get; set; } // RUL_COD (Primary key) (length: 10)
        public decimal? LinAmt { get; set; } // LIN_AMT
        public decimal? TxblLinAmt { get; set; } // TXBL_LIN_AMT
        public decimal? TxblMiscChgAmt1 { get; set; } // TXBL_MISC_CHG_AMT_1
        public decimal? TxblMiscChgAmt2 { get; set; } // TXBL_MISC_CHG_AMT_2
        public decimal? TxblMiscChgAmt3 { get; set; } // TXBL_MISC_CHG_AMT_3
        public decimal? TxblMiscChgAmt4 { get; set; } // TXBL_MISC_CHG_AMT_4
        public decimal? TxblMiscChgAmt5 { get; set; } // TXBL_MISC_CHG_AMT_5
        public decimal? TxblTaxAmt { get; set; } // TXBL_TAX_AMT
        public decimal? TxblQty { get; set; } // TXBL_QTY
        public decimal? TaxAmt { get; set; } // TAX_AMT
        public decimal? NormTaxAmt { get; set; } // NORM_TAX_AMT
        public decimal? TaxAmtExact { get; set; } // TAX_AMT_EXACT
        public decimal? NormTaxAmtExact { get; set; } // NORM_TAX_AMT_EXACT

        // Foreign keys

        /// <summary>
        /// Parent PsLwyHist pointed by [PS_LWY_HIST_TAX].([BusDat], [DocId]) (FK_PS_LWY_HIST_TAX_PS_LWY_HIST)
        /// </summary>
        public virtual PsLwyHist PsLwyHist { get; set; } // FK_PS_LWY_HIST_TAX_PS_LWY_HIST
    }

}
// </auto-generated>
