// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // PS_ORD_HIST_EXT
    public class PsOrdHistExt
    {
        public DateTime BusDatExt { get; set; } // BUS_DAT_EXT (Primary key)
        public long DocIdExt { get; set; } // DOC_ID_EXT (Primary key)
        public string UserNicsDros { get; set; } // USER_NICS_DROS (length: 30)
        public string User4473 { get; set; } // USER_4473 (length: 30)
        public string UserFfl { get; set; } // USER_FFL (length: 30)
        public string UserIntrfacdToShip { get; set; } // USER_INTRFACD_TO_SHIP (length: 1)
        public int? UserShipRespStat { get; set; } // USER_SHIP_RESP_STAT
        public string UserShipResp { get; set; } // USER_SHIP_RESP (length: 2147483647)
        public string UserEcommAuthCode { get; set; } // USER_ECOMM_AUTH_CODE (length: 10)
        public string UserEcommOrdNo { get; set; } // USER_ECOMM_ORD_NO (length: 15)
        public string UserEcommReceiptNo { get; set; } // USER_ECOMM_RECEIPT_NO (length: 10)
        public string UserDlData2D { get; set; } // USER_DL_DATA_2D (length: 2147483647)
        public string E4473SeqNo { get; set; } // E4473_SEQ_NO
        public long? E4473Id { get; set; } // E4473_ID
        public string UserArCategCod { get; set; } // USER_AR_CATEG_COD
        public DateTime? UserMembershipDat { get; set; } // USER_MEMBERSHIP_DAT
        public DateTime? UserMembershipExpDat { get; set; } // USER_MEMBERSHIP_EXP_DAT
        public string UserPaper4473 { get; set; } // USER_PAPER_4473 (length: 1)
        public string UserReplacement4473 { get; set; } // USER_REPLACEMENT_4473 (length: 1)
        public DateTime? UserWaiverDat { get; set; } // USER_WAIVER_DAT
        public DateTime? UserWaiverExpDat { get; set; } // USER_WAIVER_EXP_DAT
        public string UserAmmoLogRangeUse { get; set; } // USER_AMMO_LOG_RANGE_USE (length: 30)
        public string UserAmmoLogUnder21Verified { get; set; } // USER_AMMO_LOG_UNDER_21_VERIFIED (length: 1)
        public string UserAmmoLogId { get; set; } // USER_AMMO_LOG_ID (length: 30)
        public byte? UserShippingEasyStat { get; set; } // USER_SHIPPING_EASY_STAT
        public string UserShippingEasyResponse { get; set; } // USER_SHIPPING_EASY_RESPONSE (length: 1000)
        public long? UserShippingEasyId { get; set; } // USER_SHIPPING_EASY_ID
        public string UserIsLayaway { get; set; } = "N"; // USER_IS_LAYAWAY (length: 1)
        public string UserIsClass3 { get; set; } = "N"; // USER_IS_CLASS_3 (length: 1)
        public string UserIsVirtual { get; set; } = "N"; // USER_IS_VIRTUAL (length: 1)
        public string UserIssueRequiresCheck { get; set; } = "N"; // USER_ISSUE_REQUIRES_CHECK (length: 1)
        public string UserIssueRequiresPayment { get; set; } = "N"; // USER_ISSUE_REQUIRES_PAYMENT (length: 1)
        public string UserIssueRequiresFfl { get; set; } = "N"; // USER_ISSUE_REQUIRES_FFL (length: 1)
        public string UserIssueRequiresDocumentation { get; set; } = "N"; // USER_ISSUE_REQUIRES_DOCUMENTATION (length: 1)
        public string UserIssueIsOnOrder { get; set; } = "N"; // USER_ISSUE_IS_ON_ORDER (length: 1)

        // Foreign keys

        /// <summary>
        /// Parent PsOrdHist pointed by [PS_ORD_HIST_EXT].([BusDatExt], [DocIdExt]) (FK_PS_ORD_HIST_EXT_PS_ORD_HIST)
        /// </summary>
        public virtual PsOrdHist PsOrdHist { get; set; } // FK_PS_ORD_HIST_EXT_PS_ORD_HIST
    }

}
// </auto-generated>
