// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // PS_TKT_HIST_AUDIT_LOG
    public class PsTktHistAuditLog
    {
        public DateTime BusDat { get; set; } // BUS_DAT (Primary key)
        public long DocId { get; set; } // DOC_ID (Primary key)
        public int LogSeqNo { get; set; } // LOG_SEQ_NO (Primary key)
        public string DocTyp { get; set; } // DOC_TYP (length: 1)
        public Guid DocGuid { get; set; } // DOC_GUID
        public DateTime? CurrDt { get; set; } // CURR_DT
        public string CurrStrId { get; set; } // CURR_STR_ID (length: 10)
        public string CurrStaId { get; set; } // CURR_STA_ID (length: 10)
        public string CurrDrwId { get; set; } // CURR_DRW_ID (length: 10)
        public string CurrUsrId { get; set; } // CURR_USR_ID (length: 10)
        public string CurrWkstnNam { get; set; } // CURR_WKSTN_NAM (length: 128)
        public string CurrServNam { get; set; } // CURR_SERV_NAM (length: 128)
        public string CurrDbNam { get; set; } // CURR_DB_NAM (length: 128)
        public string Activ { get; set; } = "N"; // ACTIV (length: 1)
        public string LinkStrId { get; set; } // LINK_STR_ID (length: 10)
        public string LinkStaId { get; set; } // LINK_STA_ID (length: 10)
        public string LinkDocNo { get; set; } // LINK_DOC_NO (length: 15)
        public Guid? LinkDocGuid { get; set; } // LINK_DOC_GUID
        public string LogEntry { get; set; } // LOG_ENTRY (length: 250)

        // Reverse navigation

        /// <summary>
        /// Child PsTktHistAuditLogTots where [PS_TKT_HIST_AUDIT_LOG_TOT].([BUS_DAT], [DOC_ID], [LOG_SEQ_NO]) point to this entity (FK_PS_TKT_HIST_AUDIT_LOG_TOT_PS_TKT_HIST_AUDIT_LOG)
        /// </summary>
        public virtual IList<PsTktHistAuditLogTot> PsTktHistAuditLogTots { get; set; } = new List<PsTktHistAuditLogTot>(); // PS_TKT_HIST_AUDIT_LOG_TOT.FK_PS_TKT_HIST_AUDIT_LOG_TOT_PS_TKT_HIST_AUDIT_LOG

        // Foreign keys

        /// <summary>
        /// Parent PsTktHist pointed by [PS_TKT_HIST_AUDIT_LOG].([BusDat], [DocId]) (FK_PS_TKT_HIST_AUDIT_LOG_PS_TKT_HIST)
        /// </summary>
        public virtual PsTktHist PsTktHist { get; set; } // FK_PS_TKT_HIST_AUDIT_LOG_PS_TKT_HIST
    }

}
// </auto-generated>
