// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // RS_DEL_SY_EDC_TRX
    public class RsDelSyEdcTrx
    {
        public int DelId { get; set; } // DEL_ID (Primary key)
        public byte? RsStat { get; set; } = 1; // RS_STAT
        public DateTime? DeleteDt { get; set; } = DateTime.UtcNow; // DELETE_DT
        public string TrxSrc { get; set; } // TRX_SRC (length: 1)
        public long? DocId { get; set; } // DOC_ID
        public int? SeqNo { get; set; } // SEQ_NO
    }

}
// </auto-generated>
