// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // RS_DEL_PS_DEV_LD_MSG_SET
    public class RsDelPsDevLdMsgSet
    {
        public int DelId { get; set; } // DEL_ID (Primary key)
        public byte? RsStat { get; set; } = 1; // RS_STAT
        public DateTime? DeleteDt { get; set; } = DateTime.UtcNow; // DELETE_DT
        public long? LdMsgSetId { get; set; } // LD_MSG_SET_ID
    }

}
// </auto-generated>
