// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // SY_EXT_EDC_HIST_TOT
    public class SyExtEdcHistTot
    {
        public string EventNo { get; set; } // EVENT_NO (Primary key) (length: 15)
        public string TotTyp { get; set; } // TOT_TYP (Primary key) (length: 1)
        public int SeqNo { get; set; } // SEQ_NO (Primary key)
        public string Descr { get; set; } // DESCR (length: 30)
        public decimal? Amt { get; set; } // AMT
        public decimal? Qty { get; set; } // QTY
        public int? Cnt { get; set; } // CNT

        // Foreign keys

        /// <summary>
        /// Parent SyExtEdcHist pointed by [SY_EXT_EDC_HIST_TOT].([EventNo]) (FK_SY_EXT_EDC_HIST_TOT_SY_EXT_EDC_HIST)
        /// </summary>
        public virtual SyExtEdcHist SyExtEdcHist { get; set; } // FK_SY_EXT_EDC_HIST_TOT_SY_EXT_EDC_HIST
    }

}
// </auto-generated>
