// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // USER_VI_ITEM_REPLACEMENT_DOCUMENTS
    public class UserViItemReplacementDocument
    {
        public long DocId { get; set; } // DOC_ID
        public string TktNo { get; set; } // TKT_NO (length: 15)
        public DateTime? TktDt { get; set; } // TKT_DT
        public string CustNo { get; set; } // CUST_NO (length: 15)
        public string BillNam { get; set; } // BILL_NAM (length: 40)
        public string BillAdrs1 { get; set; } // BILL_ADRS_1 (length: 40)
        public string BillCity { get; set; } // BILL_CITY (length: 20)
        public string BillState { get; set; } // BILL_STATE (length: 10)
        public string BillPhone1 { get; set; } // BILL_PHONE_1 (length: 25)
        public string BillZipCod { get; set; } // BILL_ZIP_COD (length: 15)
        public string ReplcTyp { get; set; } // REPLC_TYP (length: 20)
    }

}
// </auto-generated>
