// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // USER_ITEM_REPLACEMENT
    public class UserItemReplacement
    {
        public long DocId { get; set; } // DOC_ID (Primary key)
        public int LinSeqNo { get; set; } // LIN_SEQ_NO (Primary key)
        public string SerNo { get; set; } // SER_NO (length: 30)
        public string ItemNo { get; set; } // ITEM_NO (length: 20)
    }

}
// </auto-generated>
