// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // USER_BOUND_BOOK_ITEM_IMPORTER
    public class UserBoundBookItemImporter
    {
        public string UserImporter { get; set; } // USER_IMPORTER (Primary key) (length: 30)
    }

}
// </auto-generated>
