// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // USER_BOUND_BOOK_ITEM_STATE_TYPE
    public class UserBoundBookItemStateType
    {
        public string UserStateType { get; set; } // USER_STATE_TYPE (Primary key) (length: 30)
    }

}
// </auto-generated>
