// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // USER_VI_RENTAL_FIREARM
    public class UserViRentalFirearm
    {
        public string ItemNo { get; set; } // ITEM_NO (length: 20)
        public string Descr { get; set; } // DESCR (length: 30)
        public decimal? Prc1 { get; set; } // PRC_1
        public int? QtyRentalA { get; set; } // QTY_RENTAL_A
        public int? QtyRoundsA { get; set; } // QTY_ROUNDS_A
        public int? MaxRentalA { get; set; } // MAX_RENTAL_A
        public int? MaxRoundsA { get; set; } // MAX_ROUNDS_A
        public int? QtyRentalB { get; set; } // QTY_RENTAL_B
        public int? QtyRoundsB { get; set; } // QTY_ROUNDS_B
        public int? MaxRentalB { get; set; } // MAX_RENTAL_B
        public int? MaxRoundsB { get; set; } // MAX_ROUNDS_B
        public int? QtyRentalC { get; set; } // QTY_RENTAL_C
        public int? QtyRoundsC { get; set; } // QTY_ROUNDS_C
        public int? MaxRentalC { get; set; } // MAX_RENTAL_C
        public int? MaxRoundsC { get; set; } // MAX_ROUNDS_C
        public int? QtyRentalLifetime { get; set; } // QTY_RENTAL_LIFETIME
        public int? QtyRoundsLifetime { get; set; } // QTY_ROUNDS_LIFETIME
        public int? MaxRentalLifetime { get; set; } // MAX_RENTAL_LIFETIME
        public int? MaxRoundsLifetime { get; set; } // MAX_ROUNDS_LIFETIME
        public string MaintLblA { get; set; } // MAINT_LBL_A (length: 50)
        public string MaintLblB { get; set; } // MAINT_LBL_B (length: 50)
        public string MaintLblC { get; set; } // MAINT_LBL_C (length: 50)
        public string MaintLblLifetime { get; set; } // MAINT_LBL_LIFETIME (length: 50)
        public string DashLbl { get; set; } // DASH_LBL (length: 1)
        public string MaintNote { get; set; } // MAINT_NOTE (length: 2147483647)
    }

}
// </auto-generated>
