// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // USER_CHECK_NO_VIEW
    public class UserCheckNoView
    {
        public long DocId { get; set; } // DOC_ID
        public string TktNo { get; set; } // TKT_NO (length: 15)
        public DateTime? BusDat { get; set; } // BUS_DAT
        public int PmtSeqNo { get; set; } // PMT_SEQ_NO
        public decimal Amt { get; set; } // AMT
        public string ChkNo { get; set; } // CHK_NO (length: 10)
    }

}
// </auto-generated>
