// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // USER_BOUND_BOOK_ITEM_HAND
    public class UserBoundBookItemHand
    {
        public string UserHand { get; set; } // USER_HAND (Primary key) (length: 30)
    }

}
// </auto-generated>
