// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // VI_Birthday
    public class ViBirthday
    {
        public string UserDlNo { get; set; } // USER_DL_NO (length: 25)
        public string FstNam { get; set; } // FST_NAM (length: 15)
        public string LstNam { get; set; } // LST_NAM (length: 25)
        public DateTime? UserDob { get; set; } // USER_DOB
        public string EmailAdrs1 { get; set; } // EMAIL_ADRS_1 (length: 50)
        public string State { get; set; } // STATE (length: 10)
        public string CustNo { get; set; } // CUST_NO (length: 15)
    }

}
// </auto-generated>
