// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // VI_IM_ITEM_CELL
    public class ViImItemCell
    {
        public string ItemNo { get; set; } // ITEM_NO (length: 20)
        public string DisplayLabel1 { get; set; } // DisplayLabel1 (length: 10)
        public string DisplayLabel2 { get; set; } // DisplayLabel2 (length: 10)
        public string DisplayLabel3 { get; set; } // DisplayLabel3 (length: 10)
    }

}
// </auto-generated>
