// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // VI_INV_PRC_CELL_EXT_NO_PRCS
    public class ViInvPrcCellExtNoPrc
    {
        public string ItemNo { get; set; } // ITEM_NO (length: 20)
        public string LocId { get; set; } // LOC_ID (length: 10)
        public string Dim1Upr { get; set; } // DIM_1_UPR (length: 15)
        public string Dim2Upr { get; set; } // DIM_2_UPR (length: 15)
        public string Dim3Upr { get; set; } // DIM_3_UPR (length: 15)
        public decimal MinQty { get; set; } // MIN_QTY
        public decimal MaxQty { get; set; } // MAX_QTY
        public decimal QtyCommit { get; set; } // QTY_COMMIT
        public decimal QtyOnHnd { get; set; } // QTY_ON_HND
        public decimal QtyOnPo { get; set; } // QTY_ON_PO
        public decimal QtyOnBo { get; set; } // QTY_ON_BO
        public decimal QtyOnSo { get; set; } // QTY_ON_SO
        public decimal QtyOnOrd { get; set; } // QTY_ON_ORD
        public decimal QtyOnLwy { get; set; } // QTY_ON_LWY
        public decimal QtyOnXferOut { get; set; } // QTY_ON_XFER_OUT
        public decimal QtyOnXferIn { get; set; } // QTY_ON_XFER_IN
        public decimal? QtyAvail { get; set; } // QTY_AVAIL
        public decimal DropshipQtyOnCustOrd { get; set; } // DROPSHIP_QTY_ON_CUST_ORD
        public decimal DropshipQtyOnPo { get; set; } // DROPSHIP_QTY_ON_PO
        public decimal? NetQty { get; set; } // NET_QTY
        public decimal? AvgCost { get; set; } // AVG_COST
        public decimal LstCost { get; set; } // LST_COST
        public decimal? ExtCost { get; set; } // EXT_COST
        public string Dim1 { get; set; } // DIM_1 (length: 15)
        public string Dim2 { get; set; } // DIM_2 (length: 15)
        public string Dim3 { get; set; } // DIM_3 (length: 15)
    }

}
// </auto-generated>
