// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // VI_PO_VCHRABLE_DOC_LIN
    public class ViPoVchrableDocLin
    {
        public string DocTyp { get; set; } // DOC_TYP (length: 1)
        public string RecvrNo { get; set; } // RECVR_NO (length: 15)
        public int SeqNo { get; set; } // SEQ_NO
        public string ItemNo { get; set; } // ITEM_NO (length: 20)
        public string ItemDescr { get; set; } // ITEM_DESCR (length: 50)
        public string ItemTyp { get; set; } // ITEM_TYP (length: 1)
        public string TrkMeth { get; set; } // TRK_METH (length: 1)
        public string ItemVendNo { get; set; } // ITEM_VEND_NO (length: 15)
        public string VendItemNo { get; set; } // VEND_ITEM_NO (length: 30)
        public string CategCod { get; set; } // CATEG_COD (length: 10)
        public string VendNo { get; set; } // VEND_NO (length: 10)
        public string Descr { get; set; } // DESCR (length: 50)
        public decimal QtyRecvd { get; set; } // QTY_RECVD
        public string QtyUnit { get; set; } // QTY_UNIT (length: 15)
        public string QtyRecvdUnit { get; set; } // QTY_RECVD_UNIT (length: 1)
        public decimal QtyRecvdNumer { get; set; } // QTY_RECVD_NUMER
        public decimal QtyRecvdDenom { get; set; } // QTY_RECVD_DENOM
        public decimal RecvdCost { get; set; } // RECVD_COST
        public decimal RecvdExtCost { get; set; } // RECVD_EXT_COST
        public string CellDescr { get; set; } // CELL_DESCR (length: 50)
        public string Dim1Upr { get; set; } // DIM_1_UPR (length: 15)
        public string Dim2Upr { get; set; } // DIM_2_UPR (length: 15)
        public string Dim3Upr { get; set; } // DIM_3_UPR (length: 15)
        public string IsSingleCell { get; set; } // IS_SINGLE_CELL (length: 1)
        public int? NoOfSersEntd { get; set; } // NO_OF_SERS_ENTD
        public string SerNo { get; set; } // SER_NO (length: 30)
        public string IsTxblNorm { get; set; } // IS_TXBL_NORM (length: 1)
        public string IsTxbl { get; set; } // IS_TXBL (length: 1)
        public string IsTxblChngd { get; set; } // IS_TXBL_CHNGD (length: 1)
        public string TaxCategNorm { get; set; } // TAX_CATEG_NORM (length: 10)
        public string TaxCateg { get; set; } // TAX_CATEG (length: 10)
        public string TaxCategChngd { get; set; } // TAX_CATEG_CHNGD (length: 1)
        public string Commnt1 { get; set; } // COMMNT_1 (length: 50)
        public string Commnt2 { get; set; } // COMMNT_2 (length: 50)
        public string Commnt3 { get; set; } // COMMNT_3 (length: 50)
        public string PoNo { get; set; } // PO_NO (length: 20)
        public string PsOrdTktNo { get; set; } // PS_ORD_TKT_NO (length: 15)
    }

}
// </auto-generated>
