// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // VI_PS_DRW_RECAP
    public class ViPsDrwRecap
    {
        public string StrId { get; set; } // STR_ID (length: 10)
        public string DrwId { get; set; } // DRW_ID (length: 10)
        public long? DrwSessionId { get; set; } // DRW_SESSION_ID
        public decimal? SalTot { get; set; } // SAL_TOT
        public decimal? RetTot { get; set; } // RET_TOT
        public decimal? VoidSalTot { get; set; } // VOID_SAL_TOT
        public decimal? VoidRetTot { get; set; } // VOID_RET_TOT
    }

}
// </auto-generated>
