// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // VI_PS_CUST_MONTHLY_HIST
    public class ViPsCustMonthlyHist
    {
        public string CustNo { get; set; } // CUST_NO (length: 15)
        public string MonthAndYear { get; set; } // Month_and_Year (length: 40)
        public decimal? Sales { get; set; } // Sales
        public int? Tickets { get; set; } // Tickets
        public decimal? AvgTicket { get; set; } // Avg_Ticket
        public int PriorMonths { get; set; } // PriorMonths
    }

}
// </auto-generated>
