// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // VI_SY_STC_WITH_CUST
    public class ViSyStcWithCust
    {
        public string StcNo { get; set; } // STC_NO (length: 30)
        public string Descr { get; set; } // DESCR (length: 30)
        public string DescrUpr { get; set; } // DESCR_UPR (length: 30)
        public DateTime? OrigDat { get; set; } // ORIG_DAT
        public string OrigStrId { get; set; } // ORIG_STR_ID (length: 10)
        public string OrigStaId { get; set; } // ORIG_STA_ID (length: 10)
        public string OrigDocNo { get; set; } // ORIG_DOC_NO (length: 15)
        public string OrigCustNo { get; set; } // ORIG_CUST_NO (length: 15)
        public string GfcCod { get; set; } // GFC_COD (length: 10)
        public string PayCod { get; set; } // PAY_COD (length: 10)
        public DateTime? ExpDat { get; set; } // EXP_DAT
        public string NoExpDat { get; set; } // NO_EXP_DAT (length: 1)
        public decimal OrigAmt { get; set; } // ORIG_AMT
        public decimal CurrAmt { get; set; } // CURR_AMT
        public string CreateMeth { get; set; } // CREATE_METH (length: 1)
        public string LiabAcctNo { get; set; } // LIAB_ACCT_NO (length: 20)
        public string RdmAcctNo { get; set; } // RDM_ACCT_NO (length: 20)
        public string RdmMeth { get; set; } // RDM_METH (length: 1)
        public string ForfAcctNo { get; set; } // FORF_ACCT_NO (length: 20)
        public string IsVoid { get; set; } // IS_VOID (length: 1)
        public DateTime? LstActivDat { get; set; } // LST_ACTIV_DAT
        public string ErrRef { get; set; } // ERR_REF (length: 255)
        public string CustNo { get; set; } // CUST_NO (length: 15)
        public string Nam { get; set; } // NAM (length: 40)
        public string NamUpr { get; set; } // NAM_UPR (length: 40)
        public string FstNam { get; set; } // FST_NAM (length: 15)
        public string FstNamUpr { get; set; } // FST_NAM_UPR (length: 15)
        public string LstNam { get; set; } // LST_NAM (length: 25)
        public string LstNamUpr { get; set; } // LST_NAM_UPR (length: 25)
        public string Salutation { get; set; } // SALUTATION (length: 10)
        public string CustTyp { get; set; } // CUST_TYP (length: 1)
        public string Adrs1 { get; set; } // ADRS_1 (length: 40)
        public string Adrs2 { get; set; } // ADRS_2 (length: 40)
        public string Adrs3 { get; set; } // ADRS_3 (length: 40)
        public string City { get; set; } // CITY (length: 20)
        public string State { get; set; } // STATE (length: 10)
        public string ZipCod { get; set; } // ZIP_COD (length: 15)
        public string Cntry { get; set; } // CNTRY (length: 20)
        public string Phone1 { get; set; } // PHONE_1 (length: 25)
        public string Phone2 { get; set; } // PHONE_2 (length: 25)
        public string Fax1 { get; set; } // FAX_1 (length: 25)
        public string Fax2 { get; set; } // FAX_2 (length: 25)
        public string Contct1 { get; set; } // CONTCT_1 (length: 40)
        public string Contct2 { get; set; } // CONTCT_2 (length: 40)
        public string EmailAdrs1 { get; set; } // EMAIL_ADRS_1 (length: 50)
        public string EmailAdrs2 { get; set; } // EMAIL_ADRS_2 (length: 50)
        public string Url1 { get; set; } // URL_1 (length: 100)
        public string Url2 { get; set; } // URL_2 (length: 100)
        public string PromptNamAdrs { get; set; } // PROMPT_NAM_ADRS (length: 1)
        public string SlsRep { get; set; } // SLS_REP (length: 10)
        public string CategCod { get; set; } // CATEG_COD (length: 10)
        public string ShipViaCod { get; set; } // SHIP_VIA_COD (length: 10)
        public string ShipZoneCod { get; set; } // SHIP_ZONE_COD (length: 10)
        public string StrId { get; set; } // STR_ID (length: 10)
        public string StmntCod { get; set; } // STMNT_COD (length: 10)
        public string TaxCod { get; set; } // TAX_COD (length: 10)
        public string TermsCod { get; set; } // TERMS_COD (length: 10)
        public string Commnt { get; set; } // COMMNT (length: 50)
        public string TaxExemptNo { get; set; } // TAX_EXEMPT_NO (length: 30)
        public DateTime? TaxExemptDat { get; set; } // TAX_EXEMPT_DAT
        public string AllowArChrg { get; set; } // ALLOW_AR_CHRG (length: 1)
        public string AllowTkts { get; set; } // ALLOW_TKTS (length: 1)
        public string NoCrLim { get; set; } // NO_CR_LIM (length: 1)
        public decimal? CrLim { get; set; } // CR_LIM
        public string CrRate { get; set; } // CR_RATE (length: 10)
        public string NoMaxChkAmt { get; set; } // NO_MAX_CHK_AMT (length: 1)
        public decimal? MaxChkAmt { get; set; } // MAX_CHK_AMT
        public decimal? UnpstdBal { get; set; } // UNPSTD_BAL
        public string BalMeth { get; set; } // BAL_METH (length: 1)
        public string ArAcctNo { get; set; } // AR_ACCT_NO (length: 20)
        public decimal? Bal { get; set; } // BAL
        public decimal? OrdBal { get; set; } // ORD_BAL
        public int? NoOfOrds { get; set; } // NO_OF_ORDS
        public string UseOrdShipTo { get; set; } // USE_ORD_SHIP_TO (length: 1)
        public string AllowOrds { get; set; } // ALLOW_ORDS (length: 1)
        public DateTime? LstAgeDat { get; set; } // LST_AGE_DAT
        public decimal? LstAgeBal { get; set; } // LST_AGE_BAL
        public decimal? LstAgeBal1 { get; set; } // LST_AGE_BAL_1
        public decimal? LstAgeBal2 { get; set; } // LST_AGE_BAL_2
        public decimal? LstAgeBal3 { get; set; } // LST_AGE_BAL_3
        public decimal? LstAgeBal4 { get; set; } // LST_AGE_BAL_4
        public decimal? LstAgeBal5 { get; set; } // LST_AGE_BAL_5
        public decimal? LstAgeBal25 { get; set; } // LST_AGE_BAL_2_5
        public decimal? LstAgeBal35 { get; set; } // LST_AGE_BAL_3_5
        public decimal? LstAgeBal45 { get; set; } // LST_AGE_BAL_4_5
        public decimal? LstAgeBalOpn { get; set; } // LST_AGE_BAL_OPN
        public string LstAgeFutrDocs { get; set; } // LST_AGE_FUTR_DOCS (length: 1)
        public string LstAgeMeth { get; set; } // LST_AGE_METH (length: 1)
        public DateTime? LstAgeAsOfDat { get; set; } // LST_AGE_AS_OF_DAT
        public DateTime? LstAgeCutoffDat { get; set; } // LST_AGE_CUTOFF_DAT
        public int? LstAgeMaxPrd1 { get; set; } // LST_AGE_MAX_PRD_1
        public int? LstAgeMaxPrd2 { get; set; } // LST_AGE_MAX_PRD_2
        public int? LstAgeMaxPrd3 { get; set; } // LST_AGE_MAX_PRD_3
        public int? LstAgeMaxPrd4 { get; set; } // LST_AGE_MAX_PRD_4
        public int? LstAgeNoOfPrds { get; set; } // LST_AGE_NO_OF_PRDS
        public string LstAgeEventNo { get; set; } // LST_AGE_EVENT_NO (length: 15)
        public string LstAgeNoCutoff { get; set; } // LST_AGE_NO_CUTOFF (length: 1)
        public decimal? LstAgePastCutoff { get; set; } // LST_AGE_PAST_CUTOFF
        public string LstAgeNonStd { get; set; } // LST_AGE_NON_STD (length: 1)
        public DateTime? LstStmntDat { get; set; } // LST_STMNT_DAT
        public decimal? LstStmntBal { get; set; } // LST_STMNT_BAL
        public decimal? LstStmntBal1 { get; set; } // LST_STMNT_BAL_1
        public decimal? LstStmntBal2 { get; set; } // LST_STMNT_BAL_2
        public decimal? LstStmntBal3 { get; set; } // LST_STMNT_BAL_3
        public decimal? LstStmntBal4 { get; set; } // LST_STMNT_BAL_4
        public decimal? LstStmntBal5 { get; set; } // LST_STMNT_BAL_5
        public decimal? LstStmntBal25 { get; set; } // LST_STMNT_BAL_2_5
        public decimal? LstStmntBal35 { get; set; } // LST_STMNT_BAL_3_5
        public decimal? LstStmntBal45 { get; set; } // LST_STMNT_BAL_4_5
        public decimal? LstStmntBalOpn { get; set; } // LST_STMNT_BAL_OPN
        public string LstStmntMeth { get; set; } // LST_STMNT_METH (length: 1)
        public DateTime? LstStmntBegDat { get; set; } // LST_STMNT_BEG_DAT
        public DateTime? LstStmntEndDat { get; set; } // LST_STMNT_END_DAT
        public int? LstStmntMaxPrd1 { get; set; } // LST_STMNT_MAX_PRD_1
        public int? LstStmntMaxPrd2 { get; set; } // LST_STMNT_MAX_PRD_2
        public int? LstStmntMaxPrd3 { get; set; } // LST_STMNT_MAX_PRD_3
        public int? LstStmntMaxPrd4 { get; set; } // LST_STMNT_MAX_PRD_4
        public int? LstStmntNoOfPrds { get; set; } // LST_STMNT_NO_OF_PRDS
        public decimal? LstStmntPastCtoff { get; set; } // LST_STMNT_PAST_CTOFF
        public DateTime? FstSalDat { get; set; } // FST_SAL_DAT
        public DateTime? LstSalDat { get; set; } // LST_SAL_DAT
        public decimal? LstSalAmt { get; set; } // LST_SAL_AMT
        public DateTime? LstPmtDat { get; set; } // LST_PMT_DAT
        public decimal? LstPmtAmt { get; set; } // LST_PMT_AMT
        public string ProfAlpha1 { get; set; } // PROF_ALPHA_1 (length: 30)
        public string ProfAlpha2 { get; set; } // PROF_ALPHA_2 (length: 30)
        public string ProfAlpha3 { get; set; } // PROF_ALPHA_3 (length: 30)
        public string ProfAlpha4 { get; set; } // PROF_ALPHA_4 (length: 30)
        public string ProfAlpha5 { get; set; } // PROF_ALPHA_5 (length: 30)
        public string ProfCod1 { get; set; } // PROF_COD_1 (length: 10)
        public string ProfCod2 { get; set; } // PROF_COD_2 (length: 10)
        public string ProfCod3 { get; set; } // PROF_COD_3 (length: 10)
        public string ProfCod4 { get; set; } // PROF_COD_4 (length: 10)
        public string ProfCod5 { get; set; } // PROF_COD_5 (length: 10)
        public DateTime? ProfDat1 { get; set; } // PROF_DAT_1
        public DateTime? ProfDat2 { get; set; } // PROF_DAT_2
        public DateTime? ProfDat3 { get; set; } // PROF_DAT_3
        public DateTime? ProfDat4 { get; set; } // PROF_DAT_4
        public DateTime? ProfDat5 { get; set; } // PROF_DAT_5
        public decimal? ProfNo1 { get; set; } // PROF_NO_1
        public decimal? ProfNo2 { get; set; } // PROF_NO_2
        public decimal? ProfNo3 { get; set; } // PROF_NO_3
        public decimal? ProfNo4 { get; set; } // PROF_NO_4
        public decimal? ProfNo5 { get; set; } // PROF_NO_5
        public DateTime? LstMaintDt { get; set; } // LST_MAINT_DT
        public string LstMaintUsrId { get; set; } // LST_MAINT_USR_ID (length: 10)
        public DateTime? LstLckDt { get; set; } // LST_LCK_DT
        public byte[] RowTs { get; set; } // ROW_TS
        public string WrkStmntActiv { get; set; } // WRK_STMNT_ACTIV (length: 1)
        public decimal? LwyBal { get; set; } // LWY_BAL
        public int? NoOfLwys { get; set; } // NO_OF_LWYS
        public string UseLwyShipTo { get; set; } // USE_LWY_SHIP_TO (length: 1)
        public string AllowLwys { get; set; } // ALLOW_LWYS (length: 1)
        public string IsEcommCust { get; set; } // IS_ECOMM_CUST (length: 1)
        public string EcommCustNo { get; set; } // ECOMM_CUST_NO (length: 10)
        public string EcommAffilCod { get; set; } // ECOMM_AFFIL_COD (length: 10)
        public decimal? DiscPct { get; set; } // DISC_PCT
        public string EcommInitPwd { get; set; } // ECOMM_INIT_PWD (length: 40)
        public string EcommNxtPubUpdt { get; set; } // ECOMM_NXT_PUB_UPDT (length: 1)
        public string EcommNxtPubFull { get; set; } // ECOMM_NXT_PUB_FULL (length: 1)
        public DateTime? EcommLstPubDt { get; set; } // ECOMM_LST_PUB_DT
        public string EcommLstPubTyp { get; set; } // ECOMM_LST_PUB_TYP (length: 1)
        public DateTime? EcommLstImpDt { get; set; } // ECOMM_LST_IMP_DT
        public string EcommCreatedCust { get; set; } // ECOMM_CREATED_CUST (length: 1)
        public string EcommLstOrdNo { get; set; } // ECOMM_LST_ORD_NO (length: 15)
        public DateTime? EcommLstOrdDt { get; set; } // ECOMM_LST_ORD_DT
        public string EcommLstImpTyp { get; set; } // ECOMM_LST_IMP_TYP (length: 1)
        public string EcommLstImpEventNo { get; set; } // ECOMM_LST_IMP_EVENT_NO (length: 15)
        public string PromptForCustomFlds { get; set; } // PROMPT_FOR_CUSTOM_FLDS (length: 1)
        public string LoyPgmCod { get; set; } // LOY_PGM_COD (length: 10)
        public int? LoyPtsBal { get; set; } // LOY_PTS_BAL
        public int? TotLoyPtsEarnd { get; set; } // TOT_LOY_PTS_EARND
        public int? TotLoyPtsRdm { get; set; } // TOT_LOY_PTS_RDM
        public int? TotLoyPtsAdj { get; set; } // TOT_LOY_PTS_ADJ
        public DateTime? LstLoyEarnTktDat { get; set; } // LST_LOY_EARN_TKT_DAT
        public DateTime? LstLoyEarnTktTim { get; set; } // LST_LOY_EARN_TKT_TIM
        public int? LstLoyPtsEarn { get; set; } // LST_LOY_PTS_EARN
        public string LstLoyEarnTktNo { get; set; } // LST_LOY_EARN_TKT_NO (length: 15)
        public DateTime? LstLoyRdmTktDat { get; set; } // LST_LOY_RDM_TKT_DAT
        public DateTime? LstLoyRdmTktTim { get; set; } // LST_LOY_RDM_TKT_TIM
        public int? LstLoyPtsRdm { get; set; } // LST_LOY_PTS_RDM
        public string LstLoyRdmTktNo { get; set; } // LST_LOY_RDM_TKT_NO (length: 15)
        public DateTime? LstLoyAdjDat { get; set; } // LST_LOY_ADJ_DAT
        public int? LstLoyPtsAdj { get; set; } // LST_LOY_PTS_ADJ
        public string LstLoyAdjDocNo { get; set; } // LST_LOY_ADJ_DOC_NO (length: 15)
        public string LoyCardNo { get; set; } // LOY_CARD_NO (length: 30)
        public string FchCod { get; set; } // FCH_COD (length: 10)
        public DateTime? LstFchDat { get; set; } // LST_FCH_DAT
        public decimal? LstFchAmt { get; set; } // LST_FCH_AMT
        public decimal? LstFchPastDueAmt { get; set; } // LST_FCH_PAST_DUE_AMT
        public string LstFchDocNo { get; set; } // LST_FCH_DOC_NO (length: 15)
        public string ReqPoNo { get; set; } // REQ_PO_NO (length: 1)
        public DateTime? RsUtcDt { get; set; } // RS_UTC_DT
        public string CustNamTyp { get; set; } // CUST_NAM_TYP (length: 1)
        public string CustFstLstNam { get; set; } // CUST_FST_LST_NAM (length: 42)
        public DateTime? LstLoyEarnTktDt { get; set; } // LST_LOY_EARN_TKT_DT
        public DateTime? LstLoyRdmTktDt { get; set; } // LST_LOY_RDM_TKT_DT
        public long? PsHdrCustFldFrmId { get; set; } // PS_HDR_CUST_FLD_FRM_ID
        public string EmailStatement { get; set; } // EMAIL_STATEMENT (length: 1)
        public byte? RsStat { get; set; } // RS_STAT
        public string IncludeInMarketingMailouts { get; set; } // INCLUDE_IN_MARKETING_MAILOUTS (length: 1)
        public DateTime? MarketingMailoutOptInDat { get; set; } // MARKETING_MAILOUT_OPT_IN_DAT
        public string RptEmail { get; set; } // RPT_EMAIL (length: 1)
        public string MblPhone1 { get; set; } // MBL_PHONE_1 (length: 25)
        public string MblPhone2 { get; set; } // MBL_PHONE_2 (length: 25)
        public DateTime? UserDob { get; set; } // USER_DOB
        public string UserSex { get; set; } // USER_SEX (length: 1)
        public string UserHeight { get; set; } // USER_HEIGHT (length: 10)
        public string UserWeight { get; set; } // USER_WEIGHT (length: 10)
        public string UserHairColr { get; set; } // USER_HAIR_COLR (length: 10)
        public string UserEyeColr { get; set; } // USER_EYE_COLR (length: 10)
        public string UserDlNo { get; set; } // USER_DL_NO (length: 25)
        public DateTime? UserDlExp { get; set; } // USER_DL_EXP
        public DateTime? UserWaiverDat { get; set; } // USER_WAIVER_DAT
        public DateTime? UserRangeLockoutDate { get; set; } // USER_RANGE_LOCKOUT_DATE
        public string UserEthnicity { get; set; } // USER_ETHNICITY (length: 30)
        public string UserRace { get; set; } // USER_RACE (length: 30)
        public string UserPlaceOfBirth { get; set; } // USER_PLACE_OF_BIRTH (length: 80)
        public string UserCounty { get; set; } // USER_COUNTY (length: 20)
        public string UserMidNam { get; set; } // USER_MID_NAM (length: 50)
    }

}
// </auto-generated>
