// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace KyGunCo.Counterpoint.Sdk.Entities
{
    // VI_TKT_HIST_RECEIPT_LINE_ITEMS
    public class ViTktHistReceiptLineItem
    {
        public DateTime BusDat { get; set; } // BUS_DAT
        public long DocId { get; set; } // DOC_ID
        public int LinSeqNo { get; set; } // LIN_SEQ_NO
    }

}
// </auto-generated>
