// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // AI_WORK
    public class AiWorkConfiguration : IEntityTypeConfiguration<AiWork>
    {
        public void Configure(EntityTypeBuilder<AiWork> builder)
        {
            builder.ToTable("AI_WORK", "dbo");
            builder.HasKey(x => x.IdColumn).HasName("PK_AI_WORK").IsClustered();

            builder.Property(x => x.IdColumn).HasColumnName(@"ID_COLUMN").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.TextColumn).HasColumnName(@"TEXT_COLUMN").HasColumnType("varchar(4000)").IsRequired(false).IsUnicode(false).HasMaxLength(4000);
        }
    }

}
// </auto-generated>
