// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // AR_FCH_COD
    public class ArFchCodConfiguration : IEntityTypeConfiguration<ArFchCod>
    {
        public void Configure(EntityTypeBuilder<ArFchCod> builder)
        {
            builder.ToTable("AR_FCH_COD", "dbo");
            builder.HasKey(x => x.FchCod).HasName("PK_AR_FCH_COD").IsClustered();

            builder.Property(x => x.FchCod).HasColumnName(@"FCH_COD").HasColumnType("varchar(10)").IsRequired().IsUnicode(false).HasMaxLength(10).ValueGeneratedNever();
            builder.Property(x => x.Descr).HasColumnName(@"DESCR").HasColumnType("varchar(30)").IsRequired().IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.DescrUpr).HasColumnName(@"DESCR_UPR").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.FchPct1).HasColumnName(@"FCH_PCT_1").HasColumnType("decimal(9,3)").IsRequired();
            builder.Property(x => x.FchPct1Cutoff).HasColumnName(@"FCH_PCT_1_CUTOFF").HasColumnType("decimal(15,2)").IsRequired(false);
            builder.Property(x => x.NoFchPct1Cutoff).HasColumnName(@"NO_FCH_PCT_1_CUTOFF").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.FchPct2).HasColumnName(@"FCH_PCT_2").HasColumnType("decimal(9,3)").IsRequired(false);
            builder.Property(x => x.MinPastDueAmt).HasColumnName(@"MIN_PAST_DUE_AMT").HasColumnType("decimal(15,2)").IsRequired();
            builder.Property(x => x.MinFchAmt).HasColumnName(@"MIN_FCH_AMT").HasColumnType("decimal(15,2)").IsRequired();
            builder.Property(x => x.AgeBy).HasColumnName(@"AGE_BY").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.FchMinAge).HasColumnName(@"FCH_MIN_AGE").HasColumnType("int").IsRequired();
            builder.Property(x => x.CalcFchOnFch).HasColumnName(@"CALC_FCH_ON_FCH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.FchAcctNo).HasColumnName(@"FCH_ACCT_NO").HasColumnType("varchar(20)").IsRequired().IsUnicode(false).HasMaxLength(20);
            builder.Property(x => x.FchMeth).HasColumnName(@"FCH_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.LstMaintDt).HasColumnName(@"LST_MAINT_DT").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.LstMaintUsrId).HasColumnName(@"LST_MAINT_USR_ID").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.LstLckDt).HasColumnName(@"LST_LCK_DT").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.RowTs).HasColumnName(@"ROW_TS").HasColumnType("timestamp").IsRequired(false);
            builder.Property(x => x.RsUtcDt).HasColumnName(@"RS_UTC_DT").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.RsStat).HasColumnName(@"RS_STAT").HasColumnType("tinyint").IsRequired();

            builder.HasIndex(x => x.RsStat).HasDatabaseName("AR_FCH_COD_X_RS_STAT");
            builder.HasIndex(x => x.RsUtcDt).HasDatabaseName("AR_FCH_COD_X_RS_UTC_DT");
            builder.HasIndex(x => new { x.DescrUpr, x.FchCod }).HasDatabaseName("AR_FCH_COD_X1");
        }
    }

}
// </auto-generated>
