// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // DM_AGG_GRP
    public class DmAggGrpConfiguration : IEntityTypeConfiguration<DmAggGrp>
    {
        public void Configure(EntityTypeBuilder<DmAggGrp> builder)
        {
            builder.ToTable("DM_AGG_GRP", "dbo");
            builder.HasKey(x => x.AggGrpId).HasName("PK_DM_AGG_GRP").IsClustered();

            builder.Property(x => x.AggGrpId).HasColumnName(@"AGG_GRP_ID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.GrpNam).HasColumnName(@"GRP_NAM").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.GrpDescr).HasColumnName(@"GRP_DESCR").HasColumnType("varchar(7000)").IsRequired(false).IsUnicode(false).HasMaxLength(7000);
        }
    }

}
// </auto-generated>
