// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // IM_ADJ_HIST
    public class ImAdjHistConfiguration : IEntityTypeConfiguration<ImAdjHist>
    {
        public void Configure(EntityTypeBuilder<ImAdjHist> builder)
        {
            builder.ToTable("IM_ADJ_HIST", "dbo");
            builder.HasKey(x => new { x.EventNo, x.BatId, x.ItemNo, x.LocId, x.TrxDat, x.SeqNo }).HasName("PK_IM_ADJ_HIST").IsClustered();

            builder.Property(x => x.EventNo).HasColumnName(@"EVENT_NO").HasColumnType("varchar(15)").IsRequired().IsUnicode(false).HasMaxLength(15).ValueGeneratedNever();
            builder.Property(x => x.BatId).HasColumnName(@"BAT_ID").HasColumnType("varchar(10)").IsRequired().IsUnicode(false).HasMaxLength(10).ValueGeneratedNever();
            builder.Property(x => x.ItemNo).HasColumnName(@"ITEM_NO").HasColumnType("varchar(20)").IsRequired().IsUnicode(false).HasMaxLength(20).ValueGeneratedNever();
            builder.Property(x => x.LocId).HasColumnName(@"LOC_ID").HasColumnType("varchar(10)").IsRequired().IsUnicode(false).HasMaxLength(10).ValueGeneratedNever();
            builder.Property(x => x.TrxDat).HasColumnName(@"TRX_DAT").HasColumnType("datetime").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.SeqNo).HasColumnName(@"SEQ_NO").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Descr).HasColumnName(@"DESCR").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.Qty).HasColumnName(@"QTY").HasColumnType("decimal(15,4)").IsRequired();
            builder.Property(x => x.QtyUnit).HasColumnName(@"QTY_UNIT").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.QtyNumer).HasColumnName(@"QTY_NUMER").HasColumnType("decimal(11,0)").IsRequired();
            builder.Property(x => x.QtyDenom).HasColumnName(@"QTY_DENOM").HasColumnType("decimal(11,0)").IsRequired();
            builder.Property(x => x.Unit).HasColumnName(@"UNIT").HasColumnType("varchar(15)").IsRequired().IsUnicode(false).HasMaxLength(15);
            builder.Property(x => x.AcctNo).HasColumnName(@"ACCT_NO").HasColumnType("varchar(20)").IsRequired().IsUnicode(false).HasMaxLength(20);
            builder.Property(x => x.CostEntd).HasColumnName(@"COST_ENTD").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.UseNormCost).HasColumnName(@"USE_NORM_COST").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.DocNo).HasColumnName(@"DOC_NO").HasColumnType("varchar(15)").IsRequired(false).IsUnicode(false).HasMaxLength(15);
            builder.Property(x => x.Ref).HasColumnName(@"REF").HasColumnType("varchar(50)").IsRequired(false).IsUnicode(false).HasMaxLength(50);
            builder.Property(x => x.ItemTyp).HasColumnName(@"ITEM_TYP").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.TrkMeth).HasColumnName(@"TRK_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.CategCod).HasColumnName(@"CATEG_COD").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.SubcatCod).HasColumnName(@"SUBCAT_COD").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.ItemVendNo).HasColumnName(@"ITEM_VEND_NO").HasColumnType("varchar(15)").IsRequired(false).IsUnicode(false).HasMaxLength(15);
            builder.Property(x => x.QtyOnHndBefore).HasColumnName(@"QTY_ON_HND_BEFORE").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.AvgCostBefore).HasColumnName(@"AVG_COST_BEFORE").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.AvgCostAfter).HasColumnName(@"AVG_COST_AFTER").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.StdCost).HasColumnName(@"STD_COST").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.ExtCost).HasColumnName(@"EXT_COST").HasColumnType("decimal(15,2)").IsRequired(false);
            builder.Property(x => x.TotCostCorr).HasColumnName(@"TOT_COST_CORR").HasColumnType("decimal(15,2)").IsRequired(false);
            builder.Property(x => x.UnitRetlVal).HasColumnName(@"UNIT_RETL_VAL").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.Cost).HasColumnName(@"COST").HasColumnType("decimal(15,4)").IsRequired();
            builder.Property(x => x.CellDescr).HasColumnName(@"CELL_DESCR").HasColumnType("varchar(50)").IsRequired(false).IsUnicode(false).HasMaxLength(50);
            builder.Property(x => x.IsSingleCell).HasColumnName(@"IS_SINGLE_CELL").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.Dim1Upr).HasColumnName(@"DIM_1_UPR").HasColumnType("varchar(15)").IsRequired(false).IsUnicode(false).HasMaxLength(15);
            builder.Property(x => x.Dim2Upr).HasColumnName(@"DIM_2_UPR").HasColumnType("varchar(15)").IsRequired(false).IsUnicode(false).HasMaxLength(15);
            builder.Property(x => x.Dim3Upr).HasColumnName(@"DIM_3_UPR").HasColumnType("varchar(15)").IsRequired(false).IsUnicode(false).HasMaxLength(15);
            builder.Property(x => x.SerNo).HasColumnName(@"SER_NO").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.NoOfSersEntd).HasColumnName(@"NO_OF_SERS_ENTD").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.LstMaintDt).HasColumnName(@"LST_MAINT_DT").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.LstMaintUsrId).HasColumnName(@"LST_MAINT_USR_ID").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.LstLckDt).HasColumnName(@"LST_LCK_DT").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.RowTs).HasColumnName(@"ROW_TS").HasColumnType("timestamp").IsRequired(false);
            builder.Property(x => x.LinGuid).HasColumnName(@"LIN_GUID").HasColumnType("uniqueidentifier").IsRequired(false);
            builder.Property(x => x.ReasCod).HasColumnName(@"REAS_COD").HasColumnType("varchar(15)").IsRequired(false).IsUnicode(false).HasMaxLength(15);

            // Foreign keys
            builder.HasOne(a => a.ImLocHist).WithMany(b => b.ImAdjHists).HasForeignKey(c => c.LocId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_IM_ADJ_HIST_IM_LOC_HIST");

            builder.HasIndex(x => new { x.LocId, x.EventNo, x.BatId, x.ItemNo, x.TrxDat, x.SeqNo }).HasDatabaseName("IM_ADJ_HIST_X1");
            builder.HasIndex(x => new { x.TrxDat, x.EventNo, x.BatId, x.ItemNo, x.LocId, x.SeqNo }).HasDatabaseName("IM_ADJ_HIST_X2");
            builder.HasIndex(x => new { x.ItemNo, x.LocId, x.DocNo, x.LstMaintDt }).HasDatabaseName("USER_IX_IM_ADJ_HIST_ITEM_NO_LOC_ID_DOC_NO_LST_MAINT_DT");
        }
    }

}
// </auto-generated>
