// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // IM_CTL
    public class ImCtlConfiguration : IEntityTypeConfiguration<ImCtl>
    {
        public void Configure(EntityTypeBuilder<ImCtl> builder)
        {
            builder.ToTable("IM_CTL", "dbo");
            builder.HasKey(x => x.KeyId).HasName("PK_IM_CTL").IsClustered();

            builder.Property(x => x.KeyId).HasColumnName(@"KEY_ID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.BsInvMeth).HasColumnName(@"BS_INV_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.CostMeth).HasColumnName(@"COST_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.UseMultiLocPrcs).HasColumnName(@"USE_MULTI_LOC_PRCS").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.PrcRoundMeth).HasColumnName(@"PRC_ROUND_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.PrcLvls).HasColumnName(@"PRC_LVLS").HasColumnType("int").IsRequired();
            builder.Property(x => x.UseAttr1).HasColumnName(@"USE_ATTR_1").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.UseAttr2).HasColumnName(@"USE_ATTR_2").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.UseAttr3).HasColumnName(@"USE_ATTR_3").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.UseAttr4).HasColumnName(@"USE_ATTR_4").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.UseAttr5).HasColumnName(@"USE_ATTR_5").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.UseAttr6).HasColumnName(@"USE_ATTR_6").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ItemBarcodId).HasColumnName(@"ITEM_BARCOD_ID").HasColumnType("varchar(10)").IsRequired().IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.UseSerCost).HasColumnName(@"USE_SER_COST").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.CntPostCostFlg).HasColumnName(@"CNT_POST_COST_FLG").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.PhysCntJrnlMeth).HasColumnName(@"PHYS_CNT_JRNL_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.PhysCntWrkshtMeth).HasColumnName(@"PHYS_CNT_WRKSHT_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ImAdjJrnlPrtMeth).HasColumnName(@"IM_ADJ_JRNL_PRT_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.UseQxferMiscChrg).HasColumnName(@"USE_QXFER_MISC_CHRG").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.QxferMiscAcctNo).HasColumnName(@"QXFER_MISC_ACCT_NO").HasColumnType("varchar(20)").IsRequired(false).IsUnicode(false).HasMaxLength(20);
            builder.Property(x => x.QxferMiscMeth).HasColumnName(@"QXFER_MISC_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.QxferJrnlPrtMeth).HasColumnName(@"QXFER_JRNL_PRT_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ItemProfAlpha1).HasColumnName(@"ITEM_PROF_ALPHA_1").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ItemProfAlpha2).HasColumnName(@"ITEM_PROF_ALPHA_2").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ItemProfAlpha3).HasColumnName(@"ITEM_PROF_ALPHA_3").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ItemProfAlpha4).HasColumnName(@"ITEM_PROF_ALPHA_4").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ItemProfAlpha5).HasColumnName(@"ITEM_PROF_ALPHA_5").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ItemProfCod1).HasColumnName(@"ITEM_PROF_COD_1").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ItemProfCod2).HasColumnName(@"ITEM_PROF_COD_2").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ItemProfCod3).HasColumnName(@"ITEM_PROF_COD_3").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ItemProfCod4).HasColumnName(@"ITEM_PROF_COD_4").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ItemProfCod5).HasColumnName(@"ITEM_PROF_COD_5").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ItemProfDat1).HasColumnName(@"ITEM_PROF_DAT_1").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ItemProfDat2).HasColumnName(@"ITEM_PROF_DAT_2").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ItemProfDat3).HasColumnName(@"ITEM_PROF_DAT_3").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ItemProfDat4).HasColumnName(@"ITEM_PROF_DAT_4").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ItemProfDat5).HasColumnName(@"ITEM_PROF_DAT_5").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ItemProfNo1).HasColumnName(@"ITEM_PROF_NO_1").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ItemProfNo2).HasColumnName(@"ITEM_PROF_NO_2").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ItemProfNo3).HasColumnName(@"ITEM_PROF_NO_3").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ItemProfNo4).HasColumnName(@"ITEM_PROF_NO_4").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ItemProfNo5).HasColumnName(@"ITEM_PROF_NO_5").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ImAdjJrnlDist).HasColumnName(@"IM_ADJ_JRNL_DIST").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.PhysCntJrnlDist).HasColumnName(@"PHYS_CNT_JRNL_DIST").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.QxferJrnlDist).HasColumnName(@"QXFER_JRNL_DIST").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.LstMaintDt).HasColumnName(@"LST_MAINT_DT").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.LstMaintUsrId).HasColumnName(@"LST_MAINT_USR_ID").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.LstLckDt).HasColumnName(@"LST_LCK_DT").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.RowTs).HasColumnName(@"ROW_TS").HasColumnType("timestamp").IsRequired(false);
            builder.Property(x => x.XferClrMeth).HasColumnName(@"XFER_CLR_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.UseXferOutMiscChrg).HasColumnName(@"USE_XFER_OUT_MISC_CHRG").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.XferOutMiscAcctNo).HasColumnName(@"XFER_OUT_MISC_ACCT_NO").HasColumnType("varchar(20)").IsRequired(false).IsUnicode(false).HasMaxLength(20);
            builder.Property(x => x.XferOutMiscMeth).HasColumnName(@"XFER_OUT_MISC_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.UseXferInMiscChrg).HasColumnName(@"USE_XFER_IN_MISC_CHRG").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.XferInMiscAcctNo).HasColumnName(@"XFER_IN_MISC_ACCT_NO").HasColumnType("varchar(20)").IsRequired(false).IsUnicode(false).HasMaxLength(20);
            builder.Property(x => x.XferInMiscMeth).HasColumnName(@"XFER_IN_MISC_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.DfltXferReconMeth).HasColumnName(@"DFLT_XFER_RECON_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.XferPrmptForLinInfo).HasColumnName(@"XFER_PRMPT_FOR_LIN_INFO").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.XferOutJrnlPrtMeth).HasColumnName(@"XFER_OUT_JRNL_PRT_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.XferFrmPrtMeth).HasColumnName(@"XFER_FRM_PRT_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.XferInJrnlPrtMeth).HasColumnName(@"XFER_IN_JRNL_PRT_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.XferInFrmPrtMeth).HasColumnName(@"XFER_IN_FRM_PRT_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.XferReconJrnlPrtMeth).HasColumnName(@"XFER_RECON_JRNL_PRT_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.XferReconFrmPrtMeth).HasColumnName(@"XFER_RECON_FRM_PRT_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.XferConsolMeth).HasColumnName(@"XFER_CONSOL_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.XferInAllowAddLins).HasColumnName(@"XFER_IN_ALLOW_ADD_LINS").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.XferOutJrnlDist).HasColumnName(@"XFER_OUT_JRNL_DIST").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.XferInJrnlDist).HasColumnName(@"XFER_IN_JRNL_DIST").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.XferReconJrnlDist).HasColumnName(@"XFER_RECON_JRNL_DIST").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.AutoAddInvMeth).HasColumnName(@"AUTO_ADD_INV_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ShowInvSetupDlg).HasColumnName(@"SHOW_INV_SETUP_DLG").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ShowGridSetupDlg).HasColumnName(@"SHOW_GRID_SETUP_DLG").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ShowInvFrm).HasColumnName(@"SHOW_INV_FRM").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.ShowGridDefFrm).HasColumnName(@"SHOW_GRID_DEF_FRM").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.GenCellBarcod).HasColumnName(@"GEN_CELL_BARCOD").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.GenCellBarcodPrefix).HasColumnName(@"GEN_CELL_BARCOD_PREFIX").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.UseSimpleItemAof).HasColumnName(@"USE_SIMPLE_ITEM_AOF").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.DfltItemLblJob).HasColumnName(@"DFLT_ITEM_LBL_JOB").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.XferInTagsMeth).HasColumnName(@"XFER_IN_TAGS_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.XferOutTagsMeth).HasColumnName(@"XFER_OUT_TAGS_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.QxferTagsMeth).HasColumnName(@"QXFER_TAGS_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.DfltXferInLblJob).HasColumnName(@"DFLT_XFER_IN_LBL_JOB").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.DfltXferOutLblJob).HasColumnName(@"DFLT_XFER_OUT_LBL_JOB").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.DfltQxferLblJob).HasColumnName(@"DFLT_QXFER_LBL_JOB").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.UseCellPrcs).HasColumnName(@"USE_CELL_PRCS").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.UseLocCellPrcs).HasColumnName(@"USE_LOC_CELL_PRCS").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.RsUtcDt).HasColumnName(@"RS_UTC_DT").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.QassemJrnlMeth).HasColumnName(@"QASSEM_JRNL_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.QassemJrnlDist).HasColumnName(@"QASSEM_JRNL_DIST").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.DfltQassemLblJob).HasColumnName(@"DFLT_QASSEM_LBL_JOB").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.QassemTagsMeth).HasColumnName(@"QASSEM_TAGS_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.CopyItemCopyInv).HasColumnName(@"COPY_ITEM_COPY_INV").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.CopyItemPromptInv).HasColumnName(@"COPY_ITEM_PROMPT_INV").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.CopyItemCopyPrc).HasColumnName(@"COPY_ITEM_COPY_PRC").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.CopyItemPromptPrc).HasColumnName(@"COPY_ITEM_PROMPT_PRC").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.CopyItemCopyItemNote).HasColumnName(@"COPY_ITEM_COPY_ITEM_NOTE").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.CopyItemPromptItemNote).HasColumnName(@"COPY_ITEM_PROMPT_ITEM_NOTE").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.CopyItemCopySubstItem).HasColumnName(@"COPY_ITEM_COPY_SUBST_ITEM").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.CopyItemCopyVendItem).HasColumnName(@"COPY_ITEM_COPY_VEND_ITEM").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.CopyItemPromptVendItem).HasColumnName(@"COPY_ITEM_PROMPT_VEND_ITEM").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.CopyItemCopyEcItemCateg).HasColumnName(@"COPY_ITEM_COPY_EC_ITEM_CATEG").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.CopyItemPromptEcItemCateg).HasColumnName(@"COPY_ITEM_PROMPT_EC_ITEM_CATEG").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.CopyItemCopyBom).HasColumnName(@"COPY_ITEM_COPY_BOM").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.CopyItemPromptBom).HasColumnName(@"COPY_ITEM_PROMPT_BOM").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.CopyItemCopySalesKit).HasColumnName(@"COPY_ITEM_COPY_SALES_KIT").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.CopyItemPromptSalesKit).HasColumnName(@"COPY_ITEM_PROMPT_SALES_KIT").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.MrgnLessThanMinMrgnColor).HasColumnName(@"MRGN_LESS_THAN_MIN_MRGN_COLOR").HasColumnType("int").IsRequired();
            builder.Property(x => x.MrgnBtwMinAndTrgtMrgnColor).HasColumnName(@"MRGN_BTW_MIN_AND_TRGT_MRGN_COLOR").HasColumnType("int").IsRequired();
            builder.Property(x => x.MrgnMeetExceedTrgtMrgnColor).HasColumnName(@"MRGN_MEET_EXCEED_TRGT_MRGN_COLOR").HasColumnType("int").IsRequired();
            builder.Property(x => x.ImCntTrxFrzQtyMeth).HasColumnName(@"IM_CNT_TRX_FRZ_QTY_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.MrgnCostToUse).HasColumnName(@"MRGN_COST_TO_USE").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.DfltPriceSheetLblJob).HasColumnName(@"DFLT_PRICE_SHEET_LBL_JOB").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.PriceSheetTagsMeth).HasColumnName(@"PRICE_SHEET_TAGS_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.RsStat).HasColumnName(@"RS_STAT").HasColumnType("tinyint").IsRequired();
            builder.Property(x => x.DropshipInvMeth).HasColumnName(@"DROPSHIP_INV_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.UserAddSerNoBarcod).HasColumnName(@"USER_ADD_SER_NO_BARCOD").HasColumnType("varchar(1)").IsRequired(false).IsUnicode(false).HasMaxLength(1);

            builder.HasIndex(x => x.RsStat).HasDatabaseName("IM_CTL_X_RS_STAT");
            builder.HasIndex(x => x.RsUtcDt).HasDatabaseName("IM_CTL_X_RS_UTC_DT");
        }
    }

}
// </auto-generated>
