// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // IM_INV_MSD
    public class ImInvMsdConfiguration : IEntityTypeConfiguration<ImInvMsd>
    {
        public void Configure(EntityTypeBuilder<ImInvMsd> builder)
        {
            builder.ToTable("IM_INV_MSD", "dbo");
            builder.HasKey(x => new { x.SiteId, x.ItemNo, x.LocId }).HasName("PK_IM_INV_MSD").IsClustered();

            builder.Property(x => x.SiteId).HasColumnName(@"SITE_ID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ItemNo).HasColumnName(@"ITEM_NO").HasColumnType("varchar(20)").IsRequired().IsUnicode(false).HasMaxLength(20).ValueGeneratedNever();
            builder.Property(x => x.LocId).HasColumnName(@"LOC_ID").HasColumnType("varchar(10)").IsRequired().IsUnicode(false).HasMaxLength(10).ValueGeneratedNever();
            builder.Property(x => x.QtyCommit).HasColumnName(@"QTY_COMMIT").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.QtyOnHnd).HasColumnName(@"QTY_ON_HND").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.QtyOnPo).HasColumnName(@"QTY_ON_PO").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.QtyOnBo).HasColumnName(@"QTY_ON_BO").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.QtyOnXferOut).HasColumnName(@"QTY_ON_XFER_OUT").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.QtyOnXferIn).HasColumnName(@"QTY_ON_XFER_IN").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.GlVal).HasColumnName(@"GL_VAL").HasColumnType("decimal(15,2)").IsRequired(false);
            builder.Property(x => x.QtyOnOrd).HasColumnName(@"QTY_ON_ORD").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.QtyOnLwy).HasColumnName(@"QTY_ON_LWY").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.QtyOnSo).HasColumnName(@"QTY_ON_SO").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.DropshipQtyOnCustOrd).HasColumnName(@"DROPSHIP_QTY_ON_CUST_ORD").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.DropshipQtyOnPo).HasColumnName(@"DROPSHIP_QTY_ON_PO").HasColumnType("decimal(15,4)").IsRequired(false);
        }
    }

}
// </auto-generated>
