// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // IM_PRC_WRK
    public class ImPrcWrkConfiguration : IEntityTypeConfiguration<ImPrcWrk>
    {
        public void Configure(EntityTypeBuilder<ImPrcWrk> builder)
        {
            builder.ToTable("IM_PRC_WRK", "dbo");
            builder.HasKey(x => new { x.SessId, x.LinSessId }).HasName("PK_IM_PRC_WRK").IsClustered();

            builder.Property(x => x.SessId).HasColumnName(@"SESS_ID").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.LinSessId).HasColumnName(@"LIN_SESS_ID").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.StkLocId).HasColumnName(@"STK_LOC_ID").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.PrcLocId).HasColumnName(@"PRC_LOC_ID").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.StrId).HasColumnName(@"STR_ID").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.DrwId).HasColumnName(@"DRW_ID").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.SalDt).HasColumnName(@"SAL_DT").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.SalDat).HasColumnName(@"SAL_DAT").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.SalTim).HasColumnName(@"SAL_TIM").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.SalDayOfWeek).HasColumnName(@"SAL_DAY_OF_WEEK").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.OrigQty).HasColumnName(@"ORIG_QTY").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.UnitFlg).HasColumnName(@"UNIT_FLG").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.UnitNam).HasColumnName(@"UNIT_NAM").HasColumnType("varchar(15)").IsRequired(false).IsUnicode(false).HasMaxLength(15);
            builder.Property(x => x.ProfAlpha1).HasColumnName(@"PROF_ALPHA_1").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.ProfAlpha2).HasColumnName(@"PROF_ALPHA_2").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.ProfAlpha3).HasColumnName(@"PROF_ALPHA_3").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.ProfAlpha4).HasColumnName(@"PROF_ALPHA_4").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.ProfAlpha5).HasColumnName(@"PROF_ALPHA_5").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.ProfCod1).HasColumnName(@"PROF_COD_1").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.ProfCod2).HasColumnName(@"PROF_COD_2").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.ProfCod3).HasColumnName(@"PROF_COD_3").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.ProfCod4).HasColumnName(@"PROF_COD_4").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.ProfCod5).HasColumnName(@"PROF_COD_5").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.ProfDat1).HasColumnName(@"PROF_DAT_1").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ProfDat2).HasColumnName(@"PROF_DAT_2").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ProfDat3).HasColumnName(@"PROF_DAT_3").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ProfDat4).HasColumnName(@"PROF_DAT_4").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ProfDat5).HasColumnName(@"PROF_DAT_5").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ProfNo1).HasColumnName(@"PROF_NO_1").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.ProfNo2).HasColumnName(@"PROF_NO_2").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.ProfNo3).HasColumnName(@"PROF_NO_3").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.ProfNo4).HasColumnName(@"PROF_NO_4").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.ProfNo5).HasColumnName(@"PROF_NO_5").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.Barcod).HasColumnName(@"BARCOD").HasColumnType("varchar(20)").IsRequired(false).IsUnicode(false).HasMaxLength(20);
            builder.Property(x => x.AvgCost).HasColumnName(@"AVG_COST").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.LstAvgCost).HasColumnName(@"LST_AVG_COST").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.LstCost).HasColumnName(@"LST_COST").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.StdCost).HasColumnName(@"STD_COST").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.RegPrc).HasColumnName(@"REG_PRC").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.Dim1Upr).HasColumnName(@"DIM_1_UPR").HasColumnType("varchar(15)").IsRequired(false).IsUnicode(false).HasMaxLength(15);
            builder.Property(x => x.Dim2Upr).HasColumnName(@"DIM_2_UPR").HasColumnType("varchar(15)").IsRequired(false).IsUnicode(false).HasMaxLength(15);
            builder.Property(x => x.Dim3Upr).HasColumnName(@"DIM_3_UPR").HasColumnType("varchar(15)").IsRequired(false).IsUnicode(false).HasMaxLength(15);
            builder.Property(x => x.ItemNo).HasColumnName(@"ITEM_NO").HasColumnType("varchar(20)").IsRequired(false).IsUnicode(false).HasMaxLength(20);
            builder.Property(x => x.CustNo).HasColumnName(@"CUST_NO").HasColumnType("varchar(15)").IsRequired(false).IsUnicode(false).HasMaxLength(15);
            builder.Property(x => x.Prc1).HasColumnName(@"PRC_1").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.Prc2).HasColumnName(@"PRC_2").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.Prc3).HasColumnName(@"PRC_3").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.Prc4).HasColumnName(@"PRC_4").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.Prc5).HasColumnName(@"PRC_5").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.Prc6).HasColumnName(@"PRC_6").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.UnitRetlVal).HasColumnName(@"UNIT_RETL_VAL").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.Prc1Typ).HasColumnName(@"PRC_1_TYP").HasColumnType("varchar(3)").IsRequired().IsUnicode(false).HasMaxLength(3);
            builder.Property(x => x.MixMatchCod).HasColumnName(@"MIX_MATCH_COD").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.ExtWeight).HasColumnName(@"EXT_WEIGHT").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.ExtCube).HasColumnName(@"EXT_CUBE").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.OrigMixMatchGrpTot).HasColumnName(@"ORIG_MIX_MATCH_GRP_TOT").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.OrigItemTotQty).HasColumnName(@"ORIG_ITEM_TOT_QTY").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.ItemTotQty).HasColumnName(@"ITEM_TOT_QTY").HasColumnType("decimal(15,4)").IsRequired(false).ValueGeneratedOnAddOrUpdate();
            builder.Property(x => x.MixMatchGrpTot).HasColumnName(@"MIX_MATCH_GRP_TOT").HasColumnType("decimal(15,4)").IsRequired(false).ValueGeneratedOnAddOrUpdate();
            builder.Property(x => x.Qty).HasColumnName(@"QTY").HasColumnType("decimal(15,4)").IsRequired(false).ValueGeneratedOnAddOrUpdate();
            builder.Property(x => x.TotRetlVal).HasColumnName(@"TOT_RETL_VAL").HasColumnType("decimal(31,8)").IsRequired(false).ValueGeneratedOnAddOrUpdate();
            builder.Property(x => x.OrigPriorLinMixMatchGrpTot).HasColumnName(@"ORIG_PRIOR_LIN_MIX_MATCH_GRP_TOT").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.PriorLinMixMatchGrpTot).HasColumnName(@"PRIOR_LIN_MIX_MATCH_GRP_TOT").HasColumnType("decimal(15,4)").IsRequired(false).ValueGeneratedOnAddOrUpdate();
            builder.Property(x => x.OrigPriorLinItemTotQty).HasColumnName(@"ORIG_PRIOR_LIN_ITEM_TOT_QTY").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.PriorLinItemTotQty).HasColumnName(@"PRIOR_LIN_ITEM_TOT_QTY").HasColumnType("decimal(15,4)").IsRequired(false).ValueGeneratedOnAddOrUpdate();
            builder.Property(x => x.OrigLinMixMatchContrib).HasColumnName(@"ORIG_LIN_MIX_MATCH_CONTRIB").HasColumnType("decimal(15,4)").IsRequired(false);

            builder.HasIndex(x => new { x.SessId, x.ProfAlpha1 }).HasDatabaseName("USER_IX_IM_PRC_WRK_SESS_ID_PROF_ALPHA_1");
        }
    }

}
// </auto-generated>
