// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // PO_ADJ_HIST_SER
    public class PoAdjHistSerConfiguration : IEntityTypeConfiguration<PoAdjHistSer>
    {
        public void Configure(EntityTypeBuilder<PoAdjHistSer> builder)
        {
            builder.ToTable("PO_ADJ_HIST_SER", "dbo");
            builder.HasKey(x => new { x.EventNo, x.RecvrNo, x.SeqNo, x.SerNo }).HasName("PK_PO_ADJ_HIST_SER").IsClustered();

            builder.Property(x => x.EventNo).HasColumnName(@"EVENT_NO").HasColumnType("varchar(15)").IsRequired().IsUnicode(false).HasMaxLength(15).ValueGeneratedNever();
            builder.Property(x => x.RecvrNo).HasColumnName(@"RECVR_NO").HasColumnType("varchar(15)").IsRequired().IsUnicode(false).HasMaxLength(15).ValueGeneratedNever();
            builder.Property(x => x.SeqNo).HasColumnName(@"SEQ_NO").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.SerNo).HasColumnName(@"SER_NO").HasColumnType("varchar(30)").IsRequired().IsUnicode(false).HasMaxLength(30).ValueGeneratedNever();
            builder.Property(x => x.CostBefore).HasColumnName(@"COST_BEFORE").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.CostAfter).HasColumnName(@"COST_AFTER").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.LstMaintDt).HasColumnName(@"LST_MAINT_DT").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.LstMaintUsrId).HasColumnName(@"LST_MAINT_USR_ID").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.LstLckDt).HasColumnName(@"LST_LCK_DT").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.RowTs).HasColumnName(@"ROW_TS").HasColumnType("timestamp").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.PoAdjHistLin).WithMany(b => b.PoAdjHistSers).HasForeignKey(c => new { c.EventNo, c.RecvrNo, c.SeqNo }).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_PO_ADJ_HIST_SER_PO_ADJ_HIST_LIN");
        }
    }

}
// </auto-generated>
