// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // PO_ADJ_HIST_LIN_LOC
    public class PoAdjHistLinLocConfiguration : IEntityTypeConfiguration<PoAdjHistLinLoc>
    {
        public void Configure(EntityTypeBuilder<PoAdjHistLinLoc> builder)
        {
            builder.ToTable("PO_ADJ_HIST_LIN_LOC", "dbo");
            builder.HasKey(x => new { x.EventNo, x.RecvrNo, x.SeqNo, x.LocId }).HasName("PK_PO_ADJ_HIST_LIN_LOC").IsClustered();

            builder.Property(x => x.EventNo).HasColumnName(@"EVENT_NO").HasColumnType("varchar(15)").IsRequired().IsUnicode(false).HasMaxLength(15).ValueGeneratedNever();
            builder.Property(x => x.RecvrNo).HasColumnName(@"RECVR_NO").HasColumnType("varchar(15)").IsRequired().IsUnicode(false).HasMaxLength(15).ValueGeneratedNever();
            builder.Property(x => x.SeqNo).HasColumnName(@"SEQ_NO").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.LocId).HasColumnName(@"LOC_ID").HasColumnType("varchar(10)").IsRequired().IsUnicode(false).HasMaxLength(10).ValueGeneratedNever();
            builder.Property(x => x.QtyRecvd).HasColumnName(@"QTY_RECVD").HasColumnType("decimal(15,4)").IsRequired();
            builder.Property(x => x.QtyAdj).HasColumnName(@"QTY_ADJ").HasColumnType("decimal(15,4)").IsRequired();
            builder.Property(x => x.LstMaintDt).HasColumnName(@"LST_MAINT_DT").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.LstMaintUsrId).HasColumnName(@"LST_MAINT_USR_ID").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.LstLckDt).HasColumnName(@"LST_LCK_DT").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.RowTs).HasColumnName(@"ROW_TS").HasColumnType("timestamp").IsRequired(false).ValueGeneratedOnAddOrUpdate();
            builder.Property(x => x.BsInvAdjAmt).HasColumnName(@"BS_INV_ADJ_AMT").HasColumnType("decimal(15,2)").IsRequired();
            builder.Property(x => x.CogsAdjAmt).HasColumnName(@"COGS_ADJ_AMT").HasColumnType("decimal(15,2)").IsRequired(false);
            builder.Property(x => x.MiscItemAdjAmt).HasColumnName(@"MISC_ITEM_ADJ_AMT").HasColumnType("decimal(15,2)").IsRequired(false);
            builder.Property(x => x.AvgCostBefore).HasColumnName(@"AVG_COST_BEFORE").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.AvgCostAfter).HasColumnName(@"AVG_COST_AFTER").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.StdCost).HasColumnName(@"STD_COST").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.TotCostCorr).HasColumnName(@"TOT_COST_CORR").HasColumnType("decimal(15,2)").IsRequired(false);
            builder.Property(x => x.LinAdjMeth).HasColumnName(@"LIN_ADJ_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);

            // Foreign keys
            builder.HasOne(a => a.PoAdjHistLin).WithMany(b => b.PoAdjHistLinLocs).HasForeignKey(c => new { c.EventNo, c.RecvrNo, c.SeqNo }).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_PO_ADJ_HIST_LIN_LOC_PO_ADJ_HIST_LIN");
        }
    }

}
// </auto-generated>
