// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // PS_DOC_LIN_LOY
    public class PsDocLinLoyConfiguration : IEntityTypeConfiguration<PsDocLinLoy>
    {
        public void Configure(EntityTypeBuilder<PsDocLinLoy> builder)
        {
            builder.ToTable("PS_DOC_LIN_LOY", "dbo");
            builder.HasKey(x => new { x.DocId, x.LinSeqNo }).HasName("PK_PS_DOC_LIN_LOY").IsClustered();

            builder.Property(x => x.DocId).HasColumnName(@"DOC_ID").HasColumnType("bigint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.LinSeqNo).HasColumnName(@"LIN_SEQ_NO").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.LinLoyPtsEarnd).HasColumnName(@"LIN_LOY_PTS_EARND").HasColumnType("money").IsRequired();
            builder.Property(x => x.LoyPgmRdmElig).HasColumnName(@"LOY_PGM_RDM_ELIG").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.LoyPgmAmtPdWithPts).HasColumnName(@"LOY_PGM_AMT_PD_WITH_PTS").HasColumnType("decimal(15,2)").IsRequired();
            builder.Property(x => x.LoyPtEarnRulDescr).HasColumnName(@"LOY_PT_EARN_RUL_DESCR").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.LoyPtEarnRulSeqNo).HasColumnName(@"LOY_PT_EARN_RUL_SEQ_NO").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.LoyPtRdmRulDescr).HasColumnName(@"LOY_PT_RDM_RUL_DESCR").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.LoyPtRdmRulSeqNo).HasColumnName(@"LOY_PT_RDM_RUL_SEQ_NO").HasColumnType("int").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.PsDocLin).WithOne(b => b.PsDocLinLoy).HasForeignKey<PsDocLinLoy>(c => new { c.DocId, c.LinSeqNo }).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_PS_DOC_LIN_LOY_PS_DOC_LIN");
        }
    }

}
// </auto-generated>
