// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // PS_DRW_SESSION_CHKSUM
    public class PsDrwSessionChksumConfiguration : IEntityTypeConfiguration<PsDrwSessionChksum>
    {
        public void Configure(EntityTypeBuilder<PsDrwSessionChksum> builder)
        {
            builder.ToTable("PS_DRW_SESSION_CHKSUM", "dbo");
            builder.HasKey(x => new { x.StrId, x.DrwId, x.DrwSessionId, x.StaId }).HasName("PK_PS_DRW_SESSION_CHKSUM").IsClustered();

            builder.Property(x => x.StrId).HasColumnName(@"STR_ID").HasColumnType("varchar(10)").IsRequired().IsUnicode(false).HasMaxLength(10).ValueGeneratedNever();
            builder.Property(x => x.DrwId).HasColumnName(@"DRW_ID").HasColumnType("varchar(10)").IsRequired().IsUnicode(false).HasMaxLength(10).ValueGeneratedNever();
            builder.Property(x => x.DrwSessionId).HasColumnName(@"DRW_SESSION_ID").HasColumnType("bigint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.StaId).HasColumnName(@"STA_ID").HasColumnType("varchar(10)").IsRequired().IsUnicode(false).HasMaxLength(10).ValueGeneratedNever();
            builder.Property(x => x.TotDocAmt).HasColumnName(@"TOT_DOC_AMT").HasColumnType("decimal(15,2)").IsRequired();
            builder.Property(x => x.DocCnt).HasColumnName(@"DOC_CNT").HasColumnType("int").IsRequired();
            builder.Property(x => x.DocLinCnt).HasColumnName(@"DOC_LIN_CNT").HasColumnType("int").IsRequired();
            builder.Property(x => x.RsUtcDt).HasColumnName(@"RS_UTC_DT").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.RsStat).HasColumnName(@"RS_STAT").HasColumnType("tinyint").IsRequired();

            builder.HasIndex(x => x.RsStat).HasDatabaseName("PS_DRW_SESSION_CHKSUM_X_RS_STAT");
            builder.HasIndex(x => x.RsUtcDt).HasDatabaseName("PS_DRW_SESSION_CHKSUM_X_RS_UTC_DT");
        }
    }

}
// </auto-generated>
