// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // PS_FRM_GRP_FRM
    public class PsFrmGrpFrmConfiguration : IEntityTypeConfiguration<PsFrmGrpFrm>
    {
        public void Configure(EntityTypeBuilder<PsFrmGrpFrm> builder)
        {
            builder.ToTable("PS_FRM_GRP_FRM", "dbo");
            builder.HasKey(x => new { x.FrmGrpId, x.SeqNo }).HasName("PK_PS_FRM_GRP_FRM").IsClustered();

            builder.Property(x => x.FrmGrpId).HasColumnName(@"FRM_GRP_ID").HasColumnType("varchar(10)").IsRequired().IsUnicode(false).HasMaxLength(10).ValueGeneratedNever();
            builder.Property(x => x.SeqNo).HasColumnName(@"SEQ_NO").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.FrmFil).HasColumnName(@"FRM_FIL").HasColumnType("varchar(100)").IsRequired().IsUnicode(false).HasMaxLength(100);
            builder.Property(x => x.Commnt).HasColumnName(@"COMMNT").HasColumnType("varchar(50)").IsRequired(false).IsUnicode(false).HasMaxLength(50);
            builder.Property(x => x.PrtrMeth).HasColumnName(@"PRTR_METH").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.PrtrNam).HasColumnName(@"PRTR_NAM").HasColumnType("varchar(100)").IsRequired(false).IsUnicode(false).HasMaxLength(100);
            builder.Property(x => x.MsgBefore).HasColumnName(@"MSG_BEFORE").HasColumnType("varchar(250)").IsRequired(false).IsUnicode(false).HasMaxLength(250);
            builder.Property(x => x.BtnLblYes).HasColumnName(@"BTN_LBL_YES").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.BtnLblNo).HasColumnName(@"BTN_LBL_NO").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.BtnLblCancel).HasColumnName(@"BTN_LBL_CANCEL").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.MsgAfter).HasColumnName(@"MSG_AFTER").HasColumnType("varchar(250)").IsRequired(false).IsUnicode(false).HasMaxLength(250);
            builder.Property(x => x.CutPaper).HasColumnName(@"CUT_PAPER").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.FiltTbl).HasColumnName(@"FILT_TBL").HasColumnType("varchar(100)").IsRequired().IsUnicode(false).HasMaxLength(100);
            builder.Property(x => x.Filt).HasColumnName(@"FILT").HasColumnType("text(2147483647)").IsRequired(false).IsUnicode(false).HasMaxLength(2147483647);
            builder.Property(x => x.FiltTmplt).HasColumnName(@"FILT_TMPLT").HasColumnType("text(2147483647)").IsRequired(false).IsUnicode(false).HasMaxLength(2147483647);
            builder.Property(x => x.LstMaintDt).HasColumnName(@"LST_MAINT_DT").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.LstMaintUsrId).HasColumnName(@"LST_MAINT_USR_ID").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.LstLckDt).HasColumnName(@"LST_LCK_DT").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.RowTs).HasColumnName(@"ROW_TS").HasColumnType("timestamp").IsRequired(false);
            builder.Property(x => x.FiltText).HasColumnName(@"FILT_TEXT").HasColumnType("text(2147483647)").IsRequired(false).IsUnicode(false).HasMaxLength(2147483647);
            builder.Property(x => x.IsAdmTkts).HasColumnName(@"IS_ADM_TKTS").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.PrtIfNeedSig).HasColumnName(@"PRT_IF_NEED_SIG").HasColumnType("varchar(1)").IsRequired().IsUnicode(false).HasMaxLength(1);

            // Foreign keys
            builder.HasOne(a => a.PsFrmGrp).WithMany(b => b.PsFrmGrpFrms).HasForeignKey(c => c.FrmGrpId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_PS_FRM_GRP_FRM_PS_FRM_GRP");
        }
    }

}
// </auto-generated>
