// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // PS_TKT_HIST_PMT_EXT
    public class PsTktHistPmtExtConfiguration : IEntityTypeConfiguration<PsTktHistPmtExt>
    {
        public void Configure(EntityTypeBuilder<PsTktHistPmtExt> builder)
        {
            builder.ToTable("PS_TKT_HIST_PMT_EXT", "dbo");
            builder.HasKey(x => new { x.BusDatExt, x.DocIdExt, x.PmtSeqNoExt }).HasName("PK_PS_TKT_HIST_PMT_EXT").IsClustered();

            builder.Property(x => x.BusDatExt).HasColumnName(@"BUS_DAT_EXT").HasColumnType("smalldatetime").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.DocIdExt).HasColumnName(@"DOC_ID_EXT").HasColumnType("bigint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.PmtSeqNoExt).HasColumnName(@"PMT_SEQ_NO_EXT").HasColumnType("int").IsRequired().ValueGeneratedNever();

            // Foreign keys
            builder.HasOne(a => a.PsTktHistPmt).WithOne(b => b.PsTktHistPmtExt).HasForeignKey<PsTktHistPmtExt>(c => new { c.BusDatExt, c.DocIdExt, c.PmtSeqNoExt }).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_PS_TKT_HIST_PMT_EXT_PS_TKT_HIST_PMT");
        }
    }

}
// </auto-generated>
