// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // RS_DEL_SY_CUSTOM_FRM
    public class RsDelSyCustomFrmConfiguration : IEntityTypeConfiguration<RsDelSyCustomFrm>
    {
        public void Configure(EntityTypeBuilder<RsDelSyCustomFrm> builder)
        {
            builder.ToTable("RS_DEL_SY_CUSTOM_FRM", "dbo");
            builder.HasKey(x => x.DelId).HasName("PK_RS_DEL_SY_CUSTOM_FRM").IsClustered();

            builder.Property(x => x.DelId).HasColumnName(@"DEL_ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.RsStat).HasColumnName(@"RS_STAT").HasColumnType("tinyint").IsRequired(false);
            builder.Property(x => x.DeleteDt).HasColumnName(@"DELETE_DT").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.FrmId).HasColumnName(@"FRM_ID").HasColumnType("bigint").IsRequired(false);
        }
    }

}
// </auto-generated>
