// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // RS_DEL_SY_GFC_COD
    public class RsDelSyGfcCodConfiguration : IEntityTypeConfiguration<RsDelSyGfcCod>
    {
        public void Configure(EntityTypeBuilder<RsDelSyGfcCod> builder)
        {
            builder.ToTable("RS_DEL_SY_GFC_COD", "dbo");
            builder.HasKey(x => x.DelId).HasName("PK_RS_DEL_SY_GFC_COD").IsClustered();

            builder.Property(x => x.DelId).HasColumnName(@"DEL_ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.RsStat).HasColumnName(@"RS_STAT").HasColumnType("tinyint").IsRequired(false);
            builder.Property(x => x.DeleteDt).HasColumnName(@"DELETE_DT").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.GfcCod).HasColumnName(@"GFC_COD").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
        }
    }

}
// </auto-generated>
