// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // SY_COLOR_PALETTE
    public class SyColorPaletteConfiguration : IEntityTypeConfiguration<SyColorPalette>
    {
        public void Configure(EntityTypeBuilder<SyColorPalette> builder)
        {
            builder.ToTable("SY_COLOR_PALETTE", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_SY_COLOR_PALETTE").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.SeqNo).HasColumnName(@"SEQ_NO").HasColumnType("int").IsRequired();
            builder.Property(x => x.ColorNam).HasColumnName(@"COLOR_NAM").HasColumnType("varchar(40)").IsRequired().IsUnicode(false).HasMaxLength(40);
            builder.Property(x => x.RsStat).HasColumnName(@"RS_STAT").HasColumnType("tinyint").IsRequired();
            builder.Property(x => x.RsUtcDt).HasColumnName(@"RS_UTC_DT").HasColumnType("datetime").IsRequired(false);

            builder.HasIndex(x => x.RsStat).HasDatabaseName("SY_COLOR_PALETTE_X_RS_STAT");
            builder.HasIndex(x => x.RsUtcDt).HasDatabaseName("SY_COLOR_PALETTE_X_RS_UTC_DT");
        }
    }

}
// </auto-generated>
