// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // USER_BOUND_BOOK_LOCAL_ATF
    public class UserBoundBookLocalAtfConfiguration : IEntityTypeConfiguration<UserBoundBookLocalAtf>
    {
        public void Configure(EntityTypeBuilder<UserBoundBookLocalAtf> builder)
        {
            builder.ToTable("USER_BOUND_BOOK_LOCAL_ATF", "dbo");
            builder.HasKey(x => x.Nam).HasName("PK_USER_BOUND_BOOK_LOCAL_ATF").IsClustered();

            builder.Property(x => x.Nam).HasColumnName(@"NAM").HasColumnType("varchar(40)").IsRequired().IsUnicode(false).HasMaxLength(40).ValueGeneratedNever();
            builder.Property(x => x.Address1).HasColumnName(@"ADDRESS_1").HasColumnType("varchar(40)").IsRequired(false).IsUnicode(false).HasMaxLength(40);
            builder.Property(x => x.City).HasColumnName(@"CITY").HasColumnType("varchar(20)").IsRequired(false).IsUnicode(false).HasMaxLength(20);
            builder.Property(x => x.State).HasColumnName(@"STATE").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.ZipCod).HasColumnName(@"ZIP_COD").HasColumnType("varchar(15)").IsRequired(false).IsUnicode(false).HasMaxLength(15);
        }
    }

}
// </auto-generated>
