// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // USER_VI_PAY_OUT_EXPORT
    public class UserViPayOutExportConfiguration : IEntityTypeConfiguration<UserViPayOutExport>
    {
        public void Configure(EntityTypeBuilder<UserViPayOutExport> builder)
        {
            builder.ToView("USER_VI_PAY_OUT_EXPORT", "dbo");
            builder.HasNoKey();

            builder.Property(x => x.BusDat).HasColumnName(@"BUS_DAT").HasColumnType("smalldatetime").IsRequired();
            builder.Property(x => x.DocId).HasColumnName(@"DOC_ID").HasColumnType("bigint").IsRequired();
            builder.Property(x => x.TktNo).HasColumnName(@"TKT_NO").HasColumnType("varchar(15)").IsRequired().IsUnicode(false).HasMaxLength(15);
            builder.Property(x => x.TktDt).HasColumnName(@"TKT_DT").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.Ref).HasColumnName(@"REF").HasColumnType("varchar(50)").IsRequired(false).IsUnicode(false).HasMaxLength(50);
            builder.Property(x => x.DocDescr).HasColumnName(@"DOC_DESCR").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.PayAmt).HasColumnName(@"PAY_AMT").HasColumnType("decimal(15,2)").IsRequired(false);
        }
    }

}
// </auto-generated>
