// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // USER_BOUND_BOOK_IMPORT
    public class UserBoundBookImportConfiguration : IEntityTypeConfiguration<UserBoundBookImport>
    {
        public void Configure(EntityTypeBuilder<UserBoundBookImport> builder)
        {
            builder.ToTable("USER_BOUND_BOOK_IMPORT", "dbo");
            builder.HasKey(x => new { x.AcqDocNo, x.AcqTransType, x.ItemNo, x.SerNo, x.LocId, x.Descr, x.LstUpdateDt, x.LstUpdateUsrId, x.BoundBookSeqNo });

            builder.Property(x => x.AcqDocNo).HasColumnName(@"ACQ_DOC_NO").HasColumnType("varchar(max)").IsRequired().IsUnicode(false).ValueGeneratedNever();
            builder.Property(x => x.AcqTransType).HasColumnName(@"ACQ_TRANS_TYPE").HasColumnType("varchar(max)").IsRequired().IsUnicode(false).ValueGeneratedNever();
            builder.Property(x => x.ItemNo).HasColumnName(@"ITEM_NO").HasColumnType("varchar(max)").IsRequired().IsUnicode(false).ValueGeneratedNever();
            builder.Property(x => x.SerNo).HasColumnName(@"SER_NO").HasColumnType("varchar(max)").IsRequired().IsUnicode(false).ValueGeneratedNever();
            builder.Property(x => x.LocId).HasColumnName(@"LOC_ID").HasColumnType("varchar(max)").IsRequired().IsUnicode(false).ValueGeneratedNever();
            builder.Property(x => x.Descr).HasColumnName(@"DESCR").HasColumnType("varchar(max)").IsRequired().IsUnicode(false).ValueGeneratedNever();
            builder.Property(x => x.UserManufacturer).HasColumnName(@"USER_MANUFACTURER").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.UserImporter).HasColumnName(@"USER_IMPORTER").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.UserModel).HasColumnName(@"USER_MODEL").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.UserAction).HasColumnName(@"USER_ACTION").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.UserCaliberGauge).HasColumnName(@"USER_CALIBER_GAUGE").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.UserAtfType).HasColumnName(@"USER_ATF_TYPE").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.UserStateType).HasColumnName(@"USER_STATE_TYPE").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.AcqDate).HasColumnName(@"ACQ_DATE").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.AcqVendNo).HasColumnName(@"ACQ_VEND_NO").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.AcqCustNo).HasColumnName(@"ACQ_CUST_NO").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.AcqName).HasColumnName(@"ACQ_NAME").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.AcqAdrs1).HasColumnName(@"ACQ_ADRS_1").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.AcqAdrs2).HasColumnName(@"ACQ_ADRS_2").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.AcqCity).HasColumnName(@"ACQ_CITY").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.AcqState).HasColumnName(@"ACQ_STATE").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.AcqZipCode).HasColumnName(@"ACQ_ZIP_CODE").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.AcqFfl).HasColumnName(@"ACQ_FFL").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.AcqDojVerificationNo).HasColumnName(@"ACQ_DOJ_VERIFICATION_NO").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.AcqUsrId).HasColumnName(@"ACQ_USR_ID").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.DispDocNo).HasColumnName(@"DISP_DOC_NO").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.DispTransType).HasColumnName(@"DISP_TRANS_TYPE").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.DispDate).HasColumnName(@"DISP_DATE").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.DispVendNo).HasColumnName(@"DISP_VEND_NO").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.DispCustNo).HasColumnName(@"DISP_CUST_NO").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.DispName).HasColumnName(@"DISP_NAME").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.DispAdrs1).HasColumnName(@"DISP_ADRS_1").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.DispAdrs2).HasColumnName(@"DISP_ADRS_2").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.DispCity).HasColumnName(@"DISP_CITY").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.DispState).HasColumnName(@"DISP_STATE").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.DispZipCode).HasColumnName(@"DISP_ZIP_CODE").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.DispFfl).HasColumnName(@"DISP_FFL").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.Disp4473).HasColumnName(@"DISP_4473").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.DispApprovalNo).HasColumnName(@"DISP_APPROVAL_NO").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.DispDob).HasColumnName(@"DISP_DOB").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.DispUsrId).HasColumnName(@"DISP_USR_ID").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.ChangeNotes).HasColumnName(@"CHANGE_NOTES").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.LstUpdateDt).HasColumnName(@"LST_UPDATE_DT").HasColumnType("datetime").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.LstUpdateUsrId).HasColumnName(@"LST_UPDATE_USR_ID").HasColumnType("varchar(max)").IsRequired().IsUnicode(false).ValueGeneratedNever();
            builder.Property(x => x.BoundBookSeqNo).HasColumnName(@"BOUND_BOOK_SEQ_NO").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.BoundBookLocSeqNo).HasColumnName(@"BOUND_BOOK_LOC_SEQ_NO").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.BoundBookPageNo).HasColumnName(@"BOUND_BOOK_PAGE_NO").HasColumnType("int").IsRequired(false).ValueGeneratedOnAddOrUpdate();
            builder.Property(x => x.BoundBookPageSeqNo).HasColumnName(@"BOUND_BOOK_PAGE_SEQ_NO").HasColumnType("int").IsRequired(false).ValueGeneratedOnAddOrUpdate();
            builder.Property(x => x.UserCountryOfOrigin).HasColumnName(@"USER_COUNTRY_OF_ORIGIN").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.CorSerNo).HasColumnName(@"COR_SER_NO").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.BoundBookType).HasColumnName(@"BOUND_BOOK_TYPE").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.BoundBookTypeLocSeqNo).HasColumnName(@"BOUND_BOOK_TYPE_LOC_SEQ_NO").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
        }
    }

}
// </auto-generated>
