// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // USER_ITEM_IMPORT
    public class UserItemImportConfiguration : IEntityTypeConfiguration<UserItemImport>
    {
        public void Configure(EntityTypeBuilder<UserItemImport> builder)
        {
            builder.ToTable("USER_ITEM_IMPORT", "dbo");
            builder.HasKey(x => x.ItemNo).HasName("PK_USER_ITEM_IMPORT").IsClustered();

            builder.Property(x => x.ItemNo).HasColumnName(@"ITEM_NO").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Descr).HasColumnName(@"DESCR").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.LongDescr).HasColumnName(@"LONG_DESCR").HasColumnType("varchar(50)").IsRequired(false).IsUnicode(false).HasMaxLength(50);
            builder.Property(x => x.AddlDescr1).HasColumnName(@"ADDL_DESCR_1").HasColumnType("varchar(80)").IsRequired(false).IsUnicode(false).HasMaxLength(80);
            builder.Property(x => x.AddlDescr2).HasColumnName(@"ADDL_DESCR_2").HasColumnType("varchar(80)").IsRequired(false).IsUnicode(false).HasMaxLength(80);
            builder.Property(x => x.ItemTyp).HasColumnName(@"ITEM_TYP").HasColumnType("varchar(1)").IsRequired(false).IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.Prc1).HasColumnName(@"PRC_1").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.Prc2).HasColumnName(@"PRC_2").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.Prc3).HasColumnName(@"PRC_3").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.RegPrc).HasColumnName(@"REG_PRC").HasColumnType("decimal(15,2)").IsRequired(false);
            builder.Property(x => x.StkUnit).HasColumnName(@"STK_UNIT").HasColumnType("varchar(15)").IsRequired(false).IsUnicode(false).HasMaxLength(15);
            builder.Property(x => x.LstCost).HasColumnName(@"LST_COST").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.IsTxbl).HasColumnName(@"IS_TXBL").HasColumnType("varchar(1)").IsRequired(false).IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.CategDescr).HasColumnName(@"CATEG_DESCR").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.SubcatDescr).HasColumnName(@"SUBCAT_DESCR").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.VendorNam).HasColumnName(@"VENDOR_NAM").HasColumnType("varchar(40)").IsRequired(false).IsUnicode(false).HasMaxLength(40);
            builder.Property(x => x.VendItemNo).HasColumnName(@"VEND_ITEM_NO").HasColumnType("varchar(20)").IsRequired(false).IsUnicode(false).HasMaxLength(20);
            builder.Property(x => x.Alt1Unit).HasColumnName(@"ALT_1_UNIT").HasColumnType("varchar(15)").IsRequired(false).IsUnicode(false).HasMaxLength(15);
            builder.Property(x => x.Alt1Numer).HasColumnName(@"ALT_1_NUMER").HasColumnType("decimal(11,0)").IsRequired(false);
            builder.Property(x => x.Alt1Denom).HasColumnName(@"ALT_1_DENOM").HasColumnType("decimal(11,0)").IsRequired(false);
            builder.Property(x => x.Alt1Prc1).HasColumnName(@"ALT_1_PRC_1").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.Alt2Unit).HasColumnName(@"ALT_2_UNIT").HasColumnType("varchar(15)").IsRequired(false).IsUnicode(false).HasMaxLength(15);
            builder.Property(x => x.Alt2Numer).HasColumnName(@"ALT_2_NUMER").HasColumnType("decimal(11,0)").IsRequired(false);
            builder.Property(x => x.Alt2Denom).HasColumnName(@"ALT_2_DENOM").HasColumnType("decimal(11,0)").IsRequired(false);
            builder.Property(x => x.Alt2Prc1).HasColumnName(@"ALT_2_PRC_1").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.Alt3Unit).HasColumnName(@"ALT_3_UNIT").HasColumnType("varchar(15)").IsRequired(false).IsUnicode(false).HasMaxLength(15);
            builder.Property(x => x.Alt3Numer).HasColumnName(@"ALT_3_NUMER").HasColumnType("decimal(11,0)").IsRequired(false);
            builder.Property(x => x.Alt3Demon).HasColumnName(@"ALT_3_DEMON").HasColumnType("decimal(11,0)").IsRequired(false);
            builder.Property(x => x.Alt3Prc1).HasColumnName(@"ALT_3_PRC_1").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.Barcod1).HasColumnName(@"BARCOD1").HasColumnType("varchar(20)").IsRequired(false).IsUnicode(false).HasMaxLength(20);
            builder.Property(x => x.Barcod2).HasColumnName(@"BARCOD2").HasColumnType("varchar(20)").IsRequired(false).IsUnicode(false).HasMaxLength(20);
            builder.Property(x => x.Barcod3).HasColumnName(@"BARCOD3").HasColumnType("varchar(20)").IsRequired(false).IsUnicode(false).HasMaxLength(20);
            builder.Property(x => x.Dim1Tag).HasColumnName(@"DIM_1_TAG").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.Dim2Tag).HasColumnName(@"DIM_2_TAG").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.Dim3Tag).HasColumnName(@"DIM_3_TAG").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.Dim1).HasColumnName(@"DIM_1").HasColumnType("varchar(15)").IsRequired(false).IsUnicode(false).HasMaxLength(15);
            builder.Property(x => x.Dim2).HasColumnName(@"DIM_2").HasColumnType("varchar(15)").IsRequired(false).IsUnicode(false).HasMaxLength(15);
            builder.Property(x => x.Dim3).HasColumnName(@"DIM_3").HasColumnType("varchar(15)").IsRequired(false).IsUnicode(false).HasMaxLength(15);
            builder.Property(x => x.Weight).HasColumnName(@"WEIGHT").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.FreightCharge).HasColumnName(@"FREIGHT_CHARGE").HasColumnType("varchar(1)").IsRequired(false).IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.TrackingMethod).HasColumnName(@"TRACKING_METHOD").HasColumnType("varchar(1)").IsRequired(false).IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.IsWebItem).HasColumnName(@"IS_WEB_ITEM").HasColumnType("varchar(1)").IsRequired(false).IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.StyleId).HasColumnName(@"STYLE_ID").HasColumnType("int").IsRequired();
            builder.Property(x => x.CaliberGauge).HasColumnName(@"CALIBER_GAUGE").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.UserAction).HasColumnName(@"USER_ACTION").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.MagCapacity).HasColumnName(@"MAG_CAPACITY").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.BarrelLength).HasColumnName(@"BARREL_LENGTH").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.IsFirearm).HasColumnName(@"IS_FIREARM").HasColumnType("varchar(1)").IsRequired(false).IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.UserModel).HasColumnName(@"USER_MODEL").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.UserImporter).HasColumnName(@"USER_IMPORTER").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.UserManufacturer).HasColumnName(@"USER_MANUFACTURER").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.UserStateType).HasColumnName(@"USER_STATE_TYPE").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.UserAtfType).HasColumnName(@"USER_ATF_TYPE").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.Attr1Cod).HasColumnName(@"ATTR_1_COD").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.Attr1CodDescr).HasColumnName(@"ATTR_1_COD_DESCR").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.Attr2Cod).HasColumnName(@"ATTR_2_COD").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.Attr2CodDescr).HasColumnName(@"ATTR_2_COD_DESCR").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.Attr3Cod).HasColumnName(@"ATTR_3_COD").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.Attr3CodDescr).HasColumnName(@"ATTR_3_COD_DESCR").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.Attr4Cod).HasColumnName(@"ATTR_4_COD").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.Attr4CodDescr).HasColumnName(@"ATTR_4_COD_DESCR").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.CategCod).HasColumnName(@"CATEG_COD").HasColumnType("varchar(100)").IsRequired(false).IsUnicode(false).HasMaxLength(100);
            builder.Property(x => x.SubcatCod).HasColumnName(@"SUBCAT_COD").HasColumnType("varchar(100)").IsRequired(false).IsUnicode(false).HasMaxLength(100);
            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.ItemVendNo).HasColumnName(@"ITEM_VEND_NO").HasColumnType("varchar(15)").IsRequired(false).IsUnicode(false).HasMaxLength(15);
        }
    }

}
// </auto-generated>
