// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // USER_BRAND_ABBRV
    public class UserBrandAbbrvConfiguration : IEntityTypeConfiguration<UserBrandAbbrv>
    {
        public void Configure(EntityTypeBuilder<UserBrandAbbrv> builder)
        {
            builder.ToTable("USER_BRAND_ABBRV", "dbo");
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Brand).HasColumnName(@"BRAND").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.Abbrv).HasColumnName(@"ABBRV").HasColumnType("varchar(11)").IsRequired(false).IsUnicode(false).HasMaxLength(11);
            builder.Property(x => x.RowId).HasColumnName(@"ROW_ID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
        }
    }

}
// </auto-generated>
