// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // VI_COPY_FROM_USR
    public class ViCopyFromUsrConfiguration : IEntityTypeConfiguration<ViCopyFromUsr>
    {
        public void Configure(EntityTypeBuilder<ViCopyFromUsr> builder)
        {
            builder.ToView("VI_COPY_FROM_USR", "dbo");
            builder.HasNoKey();

            builder.Property(x => x.UsrId).HasColumnName(@"USR_ID").HasColumnType("varchar(10)").IsRequired().IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.Nam).HasColumnName(@"NAM").HasColumnType("varchar(40)").IsRequired().IsUnicode(false).HasMaxLength(40);
            builder.Property(x => x.Initials).HasColumnName(@"INITIALS").HasColumnType("varchar(5)").IsRequired(false).IsUnicode(false).HasMaxLength(5);
            builder.Property(x => x.WrkgrpId).HasColumnName(@"WRKGRP_ID").HasColumnType("varchar(10)").IsRequired().IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.Dept).HasColumnName(@"DEPT").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.EmpNo).HasColumnName(@"EMP_NO").HasColumnType("varchar(15)").IsRequired(false).IsUnicode(false).HasMaxLength(15);
            builder.Property(x => x.BatCnt).HasColumnName(@"BAT_CNT").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.PsDrwCnt).HasColumnName(@"PS_DRW_CNT").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.HasUsrPref).HasColumnName(@"HAS_USR_PREF").HasColumnType("varchar(1)").IsRequired(false).IsUnicode(false).HasMaxLength(1);
        }
    }

}
// </auto-generated>
