// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // VI_DM_TARGET_STR_MNTH
    public class ViDmTargetStrMnthConfiguration : IEntityTypeConfiguration<ViDmTargetStrMnth>
    {
        public void Configure(EntityTypeBuilder<ViDmTargetStrMnth> builder)
        {
            builder.ToView("VI_DM_TARGET_STR_MNTH", "dbo");
            builder.HasNoKey();

            builder.Property(x => x.StrId).HasColumnName(@"STR_ID").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.YrId).HasColumnName(@"YR_ID").HasColumnType("int").IsRequired();
            builder.Property(x => x.CalndrId).HasColumnName(@"CALNDR_ID").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.MnthId).HasColumnName(@"MNTH_ID").HasColumnType("int").IsRequired();
            builder.Property(x => x.MnthNam).HasColumnName(@"MNTH_NAM").HasColumnType("varchar(5)").IsRequired(false).IsUnicode(false).HasMaxLength(5);
            builder.Property(x => x.MnthOfYr).HasColumnName(@"MNTH_OF_YR").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.BegDat).HasColumnName(@"BEG_DAT").HasColumnType("smalldatetime").IsRequired();
            builder.Property(x => x.EndDat).HasColumnName(@"END_DAT").HasColumnType("smalldatetime").IsRequired();
            builder.Property(x => x.MetricId).HasColumnName(@"METRIC_ID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.LowThresholdVal).HasColumnName(@"LOW_THRESHOLD_VAL").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.HighThresholdVal).HasColumnName(@"HIGH_THRESHOLD_VAL").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.LowThresholdSrc).HasColumnName(@"LOW_THRESHOLD_SRC").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.HighThresholdSrc).HasColumnName(@"HIGH_THRESHOLD_SRC").HasColumnType("decimal(15,4)").IsRequired(false);
            builder.Property(x => x.LstMaintDt).HasColumnName(@"LST_MAINT_DT").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.LstMaintUsrId).HasColumnName(@"LST_MAINT_USR_ID").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.LstLckDt).HasColumnName(@"LST_LCK_DT").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.RowTs).HasColumnName(@"ROW_TS").HasColumnType("timestamp").IsRequired(false).ValueGeneratedOnAddOrUpdate();
        }
    }

}
// </auto-generated>
