// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // VI_DM_MB_ITEM_STR_DAY
    public class ViDmMbItemStrDayConfiguration : IEntityTypeConfiguration<ViDmMbItemStrDay>
    {
        public void Configure(EntityTypeBuilder<ViDmMbItemStrDay> builder)
        {
            builder.ToView("VI_DM_MB_ITEM_STR_DAY", "dbo");
            builder.HasNoKey();

            builder.Property(x => x.PostDat).HasColumnName(@"POST_DAT").HasColumnType("smalldatetime").IsRequired();
            builder.Property(x => x.StrId).HasColumnName(@"STR_ID").HasColumnType("varchar(10)").IsRequired().IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.ItemNo).HasColumnName(@"ITEM_NO").HasColumnType("varchar(20)").IsRequired().IsUnicode(false).HasMaxLength(20);
            builder.Property(x => x.RelatedItemNo).HasColumnName(@"RELATED_ITEM_NO").HasColumnType("varchar(20)").IsRequired().IsUnicode(false).HasMaxLength(20);
            builder.Property(x => x.PartTktCnt).HasColumnName(@"PART_TKT_CNT").HasColumnType("int").IsRequired();
            builder.Property(x => x.SlsQty).HasColumnName(@"SLS_QTY").HasColumnType("decimal(15,4)").IsRequired();
            builder.Property(x => x.SlsExtPrc).HasColumnName(@"SLS_EXT_PRC").HasColumnType("decimal(15,2)").IsRequired();
            builder.Property(x => x.SlsLinCnt).HasColumnName(@"SLS_LIN_CNT").HasColumnType("int").IsRequired();
            builder.Property(x => x.RtnQty).HasColumnName(@"RTN_QTY").HasColumnType("decimal(15,4)").IsRequired();
            builder.Property(x => x.RtnExtPrc).HasColumnName(@"RTN_EXT_PRC").HasColumnType("decimal(15,2)").IsRequired();
            builder.Property(x => x.RtnLinCnt).HasColumnName(@"RTN_LIN_CNT").HasColumnType("int").IsRequired();
            builder.Property(x => x.TotExtCost).HasColumnName(@"TOT_EXT_COST").HasColumnType("decimal(15,2)").IsRequired();
            builder.Property(x => x.TotExtCalcPrc).HasColumnName(@"TOT_EXT_CALC_PRC").HasColumnType("decimal(15,2)").IsRequired();
            builder.Property(x => x.TotExtRetlVal).HasColumnName(@"TOT_EXT_RETL_VAL").HasColumnType("decimal(15,2)").IsRequired();
            builder.Property(x => x.TotExtRegPrc).HasColumnName(@"TOT_EXT_REG_PRC").HasColumnType("decimal(15,2)").IsRequired();
            builder.Property(x => x.TotExtPrc1).HasColumnName(@"TOT_EXT_PRC_1").HasColumnType("decimal(15,2)").IsRequired();
            builder.Property(x => x.RelatedPartTktCnt).HasColumnName(@"RELATED_PART_TKT_CNT").HasColumnType("int").IsRequired();
            builder.Property(x => x.RelatedSlsQty).HasColumnName(@"RELATED_SLS_QTY").HasColumnType("decimal(15,4)").IsRequired();
            builder.Property(x => x.RelatedSlsExtPrc).HasColumnName(@"RELATED_SLS_EXT_PRC").HasColumnType("decimal(15,2)").IsRequired();
            builder.Property(x => x.RelatedSlsLinCnt).HasColumnName(@"RELATED_SLS_LIN_CNT").HasColumnType("int").IsRequired();
            builder.Property(x => x.RelatedRtnQty).HasColumnName(@"RELATED_RTN_QTY").HasColumnType("decimal(15,4)").IsRequired();
            builder.Property(x => x.RelatedRtnExtPrc).HasColumnName(@"RELATED_RTN_EXT_PRC").HasColumnType("decimal(15,2)").IsRequired();
            builder.Property(x => x.RelatedRtnLinCnt).HasColumnName(@"RELATED_RTN_LIN_CNT").HasColumnType("int").IsRequired();
            builder.Property(x => x.RelatedTotExtCost).HasColumnName(@"RELATED_TOT_EXT_COST").HasColumnType("decimal(15,2)").IsRequired();
            builder.Property(x => x.RelatedTotExtCalcPrc).HasColumnName(@"RELATED_TOT_EXT_CALC_PRC").HasColumnType("decimal(15,2)").IsRequired();
            builder.Property(x => x.RelatedTotExtRetlVal).HasColumnName(@"RELATED_TOT_EXT_RETL_VAL").HasColumnType("decimal(15,2)").IsRequired();
            builder.Property(x => x.RelatedTotExtRegPrc).HasColumnName(@"RELATED_TOT_EXT_REG_PRC").HasColumnType("decimal(15,2)").IsRequired();
            builder.Property(x => x.RelatedTotExtPrc1).HasColumnName(@"RELATED_TOT_EXT_PRC_1").HasColumnType("decimal(15,2)").IsRequired();
            builder.Property(x => x.RowTs).HasColumnName(@"ROW_TS").HasColumnType("timestamp").IsRequired(false).ValueGeneratedOnAddOrUpdate();
            builder.Property(x => x.SlsAvgPrc).HasColumnName(@"SLS_AVG_PRC").HasColumnType("decimal(35,18)").IsRequired(false);
            builder.Property(x => x.TotQtySold).HasColumnName(@"TOT_QTY_SOLD").HasColumnType("decimal(16,4)").IsRequired(false);
            builder.Property(x => x.TotExtPrc).HasColumnName(@"TOT_EXT_PRC").HasColumnType("decimal(16,2)").IsRequired(false);
            builder.Property(x => x.TotLinCnt).HasColumnName(@"TOT_LIN_CNT").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.TotPft).HasColumnName(@"TOT_PFT").HasColumnType("decimal(17,2)").IsRequired(false);
            builder.Property(x => x.TotDiscCalc).HasColumnName(@"TOT_DISC_CALC").HasColumnType("decimal(17,2)").IsRequired(false);
            builder.Property(x => x.TotDiscRetl).HasColumnName(@"TOT_DISC_RETL").HasColumnType("decimal(17,2)").IsRequired(false);
            builder.Property(x => x.TotDiscReg).HasColumnName(@"TOT_DISC_REG").HasColumnType("decimal(17,2)").IsRequired(false);
            builder.Property(x => x.TotDiscPrc1).HasColumnName(@"TOT_DISC_PRC_1").HasColumnType("decimal(17,2)").IsRequired(false);
            builder.Property(x => x.TotPftPct).HasColumnName(@"TOT_PFT_PCT").HasColumnType("decimal(38,17)").IsRequired(false);
            builder.Property(x => x.TotRtnPctQty).HasColumnName(@"TOT_RTN_PCT_QTY").HasColumnType("decimal(35,20)").IsRequired(false);
            builder.Property(x => x.TotRtnPctPrc).HasColumnName(@"TOT_RTN_PCT_PRC").HasColumnType("decimal(33,18)").IsRequired(false);
            builder.Property(x => x.RelatedSlsAvgPrc).HasColumnName(@"RELATED_SLS_AVG_PRC").HasColumnType("decimal(35,18)").IsRequired(false);
            builder.Property(x => x.RelatedTotQtySold).HasColumnName(@"RELATED_TOT_QTY_SOLD").HasColumnType("decimal(16,4)").IsRequired(false);
            builder.Property(x => x.RelatedTotExtPrc).HasColumnName(@"RELATED_TOT_EXT_PRC").HasColumnType("decimal(16,2)").IsRequired(false);
            builder.Property(x => x.RelatedTotLinCnt).HasColumnName(@"RELATED_TOT_LIN_CNT").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.RelatedTotPft).HasColumnName(@"RELATED_TOT_PFT").HasColumnType("decimal(17,2)").IsRequired(false);
            builder.Property(x => x.RelatedTotDiscCalc).HasColumnName(@"RELATED_TOT_DISC_CALC").HasColumnType("decimal(17,2)").IsRequired(false);
            builder.Property(x => x.RelatedTotDiscRetl).HasColumnName(@"RELATED_TOT_DISC_RETL").HasColumnType("decimal(17,2)").IsRequired(false);
            builder.Property(x => x.RelatedTotDiscReg).HasColumnName(@"RELATED_TOT_DISC_REG").HasColumnType("decimal(17,2)").IsRequired(false);
            builder.Property(x => x.RelatedTotDiscPrc1).HasColumnName(@"RELATED_TOT_DISC_PRC_1").HasColumnType("decimal(17,2)").IsRequired(false);
            builder.Property(x => x.RelatedTotPftPct).HasColumnName(@"RELATED_TOT_PFT_PCT").HasColumnType("decimal(38,17)").IsRequired(false);
            builder.Property(x => x.RelatedTotRtnPctQty).HasColumnName(@"RELATED_TOT_RTN_PCT_QTY").HasColumnType("decimal(35,20)").IsRequired(false);
            builder.Property(x => x.RelatedTotRtnPctPrc).HasColumnName(@"RELATED_TOT_RTN_PCT_PRC").HasColumnType("decimal(33,18)").IsRequired(false);
        }
    }

}
// </auto-generated>
