// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // VI_PS_PRIOR_MONTHS
    public class ViPsPriorMonthConfiguration : IEntityTypeConfiguration<ViPsPriorMonth>
    {
        public void Configure(EntityTypeBuilder<ViPsPriorMonth> builder)
        {
            builder.ToView("VI_PS_PRIOR_MONTHS", "dbo");
            builder.HasNoKey();

            builder.Property(x => x.PriorMonths).HasColumnName(@"PriorMonths").HasColumnType("int").IsRequired();
            builder.Property(x => x.MonthName).HasColumnName(@"MonthName").HasColumnType("nvarchar(40)").IsRequired(false).HasMaxLength(40);
            builder.Property(x => x.Bom).HasColumnName(@"BOM").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.Bonm).HasColumnName(@"BONM").HasColumnType("datetime").IsRequired(false);
        }
    }

}
// </auto-generated>
