// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // VI_PS_CUST_MONTHLY_HIST
    public class ViPsCustMonthlyHistConfiguration : IEntityTypeConfiguration<ViPsCustMonthlyHist>
    {
        public void Configure(EntityTypeBuilder<ViPsCustMonthlyHist> builder)
        {
            builder.ToView("VI_PS_CUST_MONTHLY_HIST", "dbo");
            builder.HasNoKey();

            builder.Property(x => x.CustNo).HasColumnName(@"CUST_NO").HasColumnType("varchar(15)").IsRequired().IsUnicode(false).HasMaxLength(15);
            builder.Property(x => x.MonthAndYear).HasColumnName(@"Month_and_Year").HasColumnType("nvarchar(40)").IsRequired(false).HasMaxLength(40);
            builder.Property(x => x.Sales).HasColumnName(@"Sales").HasColumnType("decimal(38,2)").IsRequired(false);
            builder.Property(x => x.Tickets).HasColumnName(@"Tickets").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.AvgTicket).HasColumnName(@"Avg_Ticket").HasColumnType("decimal(15,2)").IsRequired(false);
            builder.Property(x => x.PriorMonths).HasColumnName(@"PriorMonths").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
