// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // VI_SA_PRC_RED
    public class ViSaPrcRedConfiguration : IEntityTypeConfiguration<ViSaPrcRed>
    {
        public void Configure(EntityTypeBuilder<ViSaPrcRed> builder)
        {
            builder.ToView("VI_SA_PRC_RED", "dbo");
            builder.HasNoKey();

            builder.Property(x => x.BusDat).HasColumnName(@"BUS_DAT").HasColumnType("smalldatetime").IsRequired();
            builder.Property(x => x.DocId).HasColumnName(@"DOC_ID").HasColumnType("bigint").IsRequired();
            builder.Property(x => x.LinSeqNo).HasColumnName(@"LIN_SEQ_NO").HasColumnType("int").IsRequired();
            builder.Property(x => x.StrId).HasColumnName(@"STR_ID").HasColumnType("varchar(10)").IsRequired().IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.ItemNo).HasColumnName(@"ITEM_NO").HasColumnType("varchar(20)").IsRequired().IsUnicode(false).HasMaxLength(20);
            builder.Property(x => x.CategCod).HasColumnName(@"CATEG_COD").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.SubcatCod).HasColumnName(@"SUBCAT_COD").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.Qty).HasColumnName(@"QTY").HasColumnType("decimal(38,15)").IsRequired(false);
            builder.Property(x => x.ExtRetlVal).HasColumnName(@"EXT_RETL_VAL").HasColumnType("decimal(35,8)").IsRequired(false);
            builder.Property(x => x.TempMkdn).HasColumnName(@"TEMP_MKDN").HasColumnType("decimal(36,8)").IsRequired(false);
            builder.Property(x => x.KitComp).HasColumnName(@"KIT_COMP").HasColumnType("numeric(38,6)").IsRequired(false);
            builder.Property(x => x.AltUnit).HasColumnName(@"ALT_UNIT").HasColumnType("decimal(35,8)").IsRequired(false);
            builder.Property(x => x.PrcOvrd).HasColumnName(@"PRC_OVRD").HasColumnType("decimal(16,2)").IsRequired(false);
            builder.Property(x => x.UsrDisc).HasColumnName(@"USR_DISC").HasColumnType("decimal(38,2)").IsRequired(false);
            builder.Property(x => x.ExtPrc).HasColumnName(@"EXT_PRC").HasColumnType("decimal(15,2)").IsRequired();
        }
    }

}
// </auto-generated>
