// <auto-generated>

using KyGunCo.Counterpoint.Sdk.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KyGunCo.Counterpoint.Sdk.Configuration
{
    // VI_TKT_HIST_SLS_REP
    public class ViTktHistSlsRepConfiguration : IEntityTypeConfiguration<ViTktHistSlsRep>
    {
        public void Configure(EntityTypeBuilder<ViTktHistSlsRep> builder)
        {
            builder.ToView("VI_TKT_HIST_SLS_REP", "dbo");
            builder.HasNoKey();

            builder.Property(x => x.StrId).HasColumnName(@"STR_ID").HasColumnType("varchar(10)").IsRequired().IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.SlsRep).HasColumnName(@"SLS_REP").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.Nam).HasColumnName(@"NAM").HasColumnType("varchar(40)").IsRequired(false).IsUnicode(false).HasMaxLength(40);
            builder.Property(x => x.PostDat).HasColumnName(@"POST_DAT").HasColumnType("smalldatetime").IsRequired();
            builder.Property(x => x.TktCount).HasColumnName(@"TKT_COUNT").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.SalSubTot).HasColumnName(@"SAL_SUB_TOT").HasColumnType("decimal(38,2)").IsRequired(false);
            builder.Property(x => x.SalTotCost).HasColumnName(@"SAL_TOT_COST").HasColumnType("decimal(38,2)").IsRequired(false);
            builder.Property(x => x.SalLins).HasColumnName(@"SAL_LINS").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.RetLins).HasColumnName(@"RET_LINS").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.MultSals).HasColumnName(@"MULT_SALS").HasColumnType("int").IsRequired(false);
        }
    }

}
// </auto-generated>
